// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package pro

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"github.com/jamf/jamfplatform-go-sdk/internal/client"
)

// ListAccountGroupsV1 get account groups.
//
// Required privileges: account-groups:read. Legacy Jamf Pro privilege name(s): Read Account Groups.
//
// Parameters:
//   - sort: Sorting criteria in the format: property:asc/desc. Default sort is name:asc. Multiple sort criteria
//     are supported and must be separated with a comma. Accepts fields: id, name, siteId, ldapServerId.
//   - filter: Query in the RSQL format to filter account groups collection. An empty query returns all results for
//     the requested page. Supported fields: id, name, siteId, ldapServerId. Multiple conditions can be
//     combined using logical operators. This parameter can be used with paging and sorting parameters.
//     Example: name=="Admins" and siteId==-1.
func (c *Client) ListAccountGroupsV1(ctx context.Context, sort []string, filter string) ([]AccountGroupV1, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	return client.ListAllPages(ctx, 2000, func(ctx context.Context, page, pageSize int) ([]AccountGroupV1, bool, error) {
		params := url.Values{}
		params.Set("page", strconv.Itoa(page))
		params.Set("page-size", strconv.Itoa(pageSize))
		if len(sort) > 0 {
			params.Set("sort", strings.Join(sort, ","))
		}
		if filter != "" {
			params.Set("filter", filter)
		}

		endpoint := prefix + "/account-groups"
		if encoded := params.Encode(); encoded != "" {
			endpoint += "?" + encoded
		}
		var result struct {
			TotalCount int              `json:"totalCount"`
			Results    []AccountGroupV1 `json:"results"`
		}
		if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
			return nil, false, err
		}
		hasNext := (page+1)*pageSize < result.TotalCount
		return result.Results, hasNext, nil
	})
}

// GetAccountGroupV1 gets the account group.
//
// Required privileges: account-groups:read. Legacy Jamf Pro privilege name(s): Read Account Groups.
//
// Parameters:
//   - id: id of target account group.
func (c *Client) GetAccountGroupV1(ctx context.Context, id string) (*AccountGroupV1, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result AccountGroupV1
	endpoint := fmt.Sprintf("%s/account-groups/%s", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetAccountGroupV1(%s): %w", id, err)
	}
	return &result, nil
}

// ResolveAccountGroupV1IDByName looks up a AccountGroupV1 by its name field and returns the ID. Returns *APIResponseError with HasStatus(404) when no match exists, or *AmbiguousMatchError when multiple resources share the name.
func (c *Client) ResolveAccountGroupV1IDByName(ctx context.Context, name string) (string, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	listPath := prefix + "/account-groups"
	id, _, err := c.transport.ResolveByNameFiltered(ctx, listPath, "", "name", "name", "id", name)
	if err != nil {
		return "", fmt.Errorf("ResolveAccountGroupV1IDByName(%s): %w", name, err)
	}
	return id, nil
}

// ResolveAccountGroupV1ByName looks up a AccountGroupV1 by its name field and returns the decoded resource. Shares the same HTTP call as the ID-only variant; error semantics are identical.
func (c *Client) ResolveAccountGroupV1ByName(ctx context.Context, name string) (*AccountGroupV1, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	listPath := prefix + "/account-groups"
	_, raw, err := c.transport.ResolveByNameFiltered(ctx, listPath, "", "name", "name", "id", name)
	if err != nil {
		return nil, fmt.Errorf("ResolveAccountGroupV1ByName(%s): %w", name, err)
	}
	var out AccountGroupV1
	if err := json.Unmarshal(raw, &out); err != nil {
		return nil, fmt.Errorf("ResolveAccountGroupV1ByName(%s): decoding matched element: %w", name, err)
	}
	return &out, nil
}
