// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package pro

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"github.com/jamf/jamfplatform-go-sdk/internal/client"
)

// UpdateActivationCodeV1 updates Activation Code.
//
// Required privileges: activation-code:update. Legacy Jamf Pro privilege name(s): Update License Information.
func (c *Client) UpdateActivationCodeV1(ctx context.Context, request *ActivationCode) error {
	prefix := c.transport.APIPrefix("pro", "v1")
	endpoint := prefix + "/activation-code"
	if err := c.transport.DoWithContentType(ctx, http.MethodPut, endpoint, request, "application/json", http.StatusAccepted, nil); err != nil {
		return fmt.Errorf("UpdateActivationCodeV1: %w", err)
	}
	return nil
}

// ListActivationCodeHistoryV1 get Activation Code history object.
//
// Required privileges: activation-code:read. Legacy Jamf Pro privilege name(s): Read License Information.
//
// Parameters:
//   - sort: Sorting criteria in the format: property:asc/desc. Default sort is date:desc. Fields allowed in the
//     query: id, username, date, note, details Multiple sort criteria are supported and must be separated
//     with a comma. Example: sort=date:desc,note:asc.
//   - filter: Query in the RSQL format, allowing to filter history notes collection. Default filter is empty query
//   - returning all results for the requested page. Fields allowed in the query: id, username, date,
//     note, details. This param can be combined with paging and sorting. Example: filter=username!=admin
//     and details==*disabled* and date<2019-12-15.
func (c *Client) ListActivationCodeHistoryV1(ctx context.Context, sort []string, filter string) ([]ObjectHistory, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	return client.ListAllPages(ctx, 2000, func(ctx context.Context, page, pageSize int) ([]ObjectHistory, bool, error) {
		params := url.Values{}
		params.Set("page", strconv.Itoa(page))
		params.Set("page-size", strconv.Itoa(pageSize))
		if len(sort) > 0 {
			params.Set("sort", strings.Join(sort, ","))
		}
		if filter != "" {
			params.Set("filter", filter)
		}

		endpoint := prefix + "/activation-code/history"
		if encoded := params.Encode(); encoded != "" {
			endpoint += "?" + encoded
		}
		var result struct {
			TotalCount int             `json:"totalCount"`
			Results    []ObjectHistory `json:"results"`
		}
		if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
			return nil, false, err
		}
		hasNext := (page+1)*pageSize < result.TotalCount
		return result.Results, hasNext, nil
	})
}

// CreateActivationCodeHistoryNoteV1 add Activation Code object note.
//
// Required privileges: activation-code:update. Legacy Jamf Pro privilege name(s): Update License Information.
func (c *Client) CreateActivationCodeHistoryNoteV1(ctx context.Context, request *ObjectHistoryNote) (*ObjectHistory, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result ObjectHistory
	endpoint := prefix + "/activation-code/history"
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("CreateActivationCodeHistoryNoteV1: %w", err)
	}
	return &result, nil
}

// ExportActivationCodeHistoryV1 export history object collection in specified format for Activation Code.
//
// Required privileges: activation-code:read. Legacy Jamf Pro privilege name(s): Read License Information.
func (c *Client) ExportActivationCodeHistoryV1(ctx context.Context, request *ExportParameters) ([]byte, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result []byte
	endpoint := prefix + "/activation-code/history/export"
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusOK, &result); err != nil {
		return nil, fmt.Errorf("ExportActivationCodeHistoryV1: %w", err)
	}
	return result, nil
}

// UpdateActivationCodeOrganizationNameV1 updates Organization Name.
//
// Required privileges: activation-code:update. Legacy Jamf Pro privilege name(s): Update License Information.
func (c *Client) UpdateActivationCodeOrganizationNameV1(ctx context.Context, request *OrganizationName) error {
	prefix := c.transport.APIPrefix("pro", "v1")
	endpoint := prefix + "/activation-code/organization-name"
	if err := c.transport.DoWithContentType(ctx, http.MethodPatch, endpoint, request, "application/json", http.StatusAccepted, nil); err != nil {
		return fmt.Errorf("UpdateActivationCodeOrganizationNameV1: %w", err)
	}
	return nil
}
