// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package pro

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"

	"github.com/jamf/jamfplatform-go-sdk/internal/client"
)

// ListAdvancedUserContentSearchesV1 get All Advanced User Content Search objects.
//
// Required privileges: advanced-user-searches:read. Legacy Jamf Pro privilege name(s): Read Advanced User Content Searches.
func (c *Client) ListAdvancedUserContentSearchesV1(ctx context.Context) (*AdvancedUserContentSearchSearchResults, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result AdvancedUserContentSearchSearchResults
	endpoint := prefix + "/advanced-user-content-searches"
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("ListAdvancedUserContentSearchesV1: %w", err)
	}
	return &result, nil
}

// CreateAdvancedUserContentSearchV1 create Advanced User Content Search object.
//
// Required privileges: advanced-user-searches:create. Legacy Jamf Pro privilege name(s): Create Advanced User Content Searches.
func (c *Client) CreateAdvancedUserContentSearchV1(ctx context.Context, request *AdvancedUserContentSearch) (*HrefResponse, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result HrefResponse
	endpoint := prefix + "/advanced-user-content-searches"
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("CreateAdvancedUserContentSearchV1: %w", err)
	}
	return &result, nil
}

// GetAdvancedUserContentSearchV1 get Specified Advanced User Content Search object.
//
// Required privileges: advanced-user-searches:read. Legacy Jamf Pro privilege name(s): Read Advanced User Content Searches.
//
// Parameters:
//   - id: id of target Advanced User Content Search.
func (c *Client) GetAdvancedUserContentSearchV1(ctx context.Context, id string) (*AdvancedUserContentSearch, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result AdvancedUserContentSearch
	endpoint := fmt.Sprintf("%s/advanced-user-content-searches/%s", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetAdvancedUserContentSearchV1(%s): %w", id, err)
	}
	return &result, nil
}

// UpdateAdvancedUserContentSearchV1 get Specified Advanced User Content Search object.
//
// Required privileges: advanced-user-searches:update. Legacy Jamf Pro privilege name(s): Update Advanced User Content Searches.
//
// Parameters:
//   - id: id of target Advanced User Content Search.
func (c *Client) UpdateAdvancedUserContentSearchV1(ctx context.Context, id string, request *AdvancedUserContentSearch) (*AdvancedUserContentSearch, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result AdvancedUserContentSearch
	endpoint := fmt.Sprintf("%s/advanced-user-content-searches/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoWithContentType(ctx, http.MethodPut, endpoint, request, "application/json", http.StatusOK, &result); err != nil {
		return nil, fmt.Errorf("UpdateAdvancedUserContentSearchV1(%s): %w", id, err)
	}
	return &result, nil
}

// DeleteAdvancedUserContentSearchV1 remove specified Advanced User Content Search object.
//
// Required privileges: advanced-user-searches:delete. Legacy Jamf Pro privilege name(s): Delete Advanced User Content Searches.
//
// Parameters:
//   - id: instance id of Advanced User Content Search record.
func (c *Client) DeleteAdvancedUserContentSearchV1(ctx context.Context, id string) error {
	prefix := c.transport.APIPrefix("pro", "v1")
	endpoint := fmt.Sprintf("%s/advanced-user-content-searches/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusNoContent, nil); err != nil {
		return fmt.Errorf("DeleteAdvancedUserContentSearchV1(%s): %w", id, err)
	}
	return nil
}

// ResolveAdvancedUserContentSearchV1IDByName looks up a AdvancedUserContentSearchV1 by its name field and returns the ID. Returns *APIResponseError with HasStatus(404) when no match exists, or *AmbiguousMatchError when multiple resources share the name.
func (c *Client) ResolveAdvancedUserContentSearchV1IDByName(ctx context.Context, name string) (string, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	listPath := prefix + "/advanced-user-content-searches"
	id, _, err := c.transport.ResolveByNameClient(ctx, listPath, "", "", "name", "id", name)
	if err != nil {
		return "", fmt.Errorf("ResolveAdvancedUserContentSearchV1IDByName(%s): %w", name, err)
	}
	return id, nil
}

// ResolveAdvancedUserContentSearchV1ByName looks up a AdvancedUserContentSearchV1 by its name field and returns the decoded resource. Shares the same HTTP call as the ID-only variant; error semantics are identical.
func (c *Client) ResolveAdvancedUserContentSearchV1ByName(ctx context.Context, name string) (*AdvancedUserContentSearch, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	listPath := prefix + "/advanced-user-content-searches"
	_, raw, err := c.transport.ResolveByNameClient(ctx, listPath, "", "", "name", "id", name)
	if err != nil {
		return nil, fmt.Errorf("ResolveAdvancedUserContentSearchV1ByName(%s): %w", name, err)
	}
	var out AdvancedUserContentSearch
	if err := json.Unmarshal(raw, &out); err != nil {
		return nil, fmt.Errorf("ResolveAdvancedUserContentSearchV1ByName(%s): decoding matched element: %w", name, err)
	}
	return &out, nil
}

// ApplyAdvancedUserContentSearchV1 creates or updates a AdvancedUserContentSearchV1 by name. If a resource with the specified name exists, it is updated; if not found, a new resource is created. Returns the resource ID, whether it was created (true) or updated (false), and any error. An *AmbiguousMatchError is returned if multiple resources match the name.
func (c *Client) ApplyAdvancedUserContentSearchV1(ctx context.Context, request *AdvancedUserContentSearch) (string, bool, error) {
	name := request.Name
	if name == "" {
		return "", false, fmt.Errorf("ApplyAdvancedUserContentSearchV1: Name must not be empty")
	}
	id, err := c.ResolveAdvancedUserContentSearchV1IDByName(ctx, name)
	if err != nil {
		if apiErr := client.AsAPIError(err); apiErr != nil && apiErr.HasStatus(404) {
			resp, createErr := c.CreateAdvancedUserContentSearchV1(ctx, request)
			if createErr != nil {
				return "", false, fmt.Errorf("ApplyAdvancedUserContentSearchV1: create: %w", createErr)
			}
			return resp.ID, true, nil
		}
		return "", false, fmt.Errorf("ApplyAdvancedUserContentSearchV1: resolve: %w", err)
	}
	_, err = c.UpdateAdvancedUserContentSearchV1(ctx, id, request)
	if err != nil {
		return "", false, fmt.Errorf("ApplyAdvancedUserContentSearchV1: update(%s): %w", id, err)
	}
	return id, false, nil
}
