// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package pro

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"github.com/jamf/jamfplatform-go-sdk/internal/client"
)

// ListApnsClientPushStatusesV1 search for clients with push notifications disabled.
//
// Required privileges: device-actions:read. Legacy Jamf Pro privilege name(s): View MDM command information in Jamf Pro API.
//
// Parameters:
//   - sort: Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort
//     criteria are supported. Sortable fields: pushDisabledTime, deviceType, managementId.
//   - filter: Query in the RSQL format, allowing to filter results. Fields allowed in the query: deviceType,
//     disabledAt, managementId. This param can be combined with paging and sorting.
//     Example: filter=deviceType=="MOBILE_DEVICE" Example: filter=disabledAt>2024-11-01T00:00:00Z Example:
//     filter=deviceType=="COMPUTER";disabledAt>2024-01-01T00:00:00Z.
func (c *Client) ListApnsClientPushStatusesV1(ctx context.Context, sort []string, filter string) ([]ApnsClientPushStatus, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	return client.ListAllPages(ctx, 2000, func(ctx context.Context, page, pageSize int) ([]ApnsClientPushStatus, bool, error) {
		params := url.Values{}
		params.Set("page", strconv.Itoa(page))
		params.Set("page-size", strconv.Itoa(pageSize))
		if len(sort) > 0 {
			params.Set("sort", strings.Join(sort, ","))
		}
		if filter != "" {
			params.Set("filter", filter)
		}

		endpoint := prefix + "/apns-client-push-status"
		if encoded := params.Encode(); encoded != "" {
			endpoint += "?" + encoded
		}
		var result struct {
			TotalCount int                    `json:"totalCount"`
			Results    []ApnsClientPushStatus `json:"results"`
		}
		if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
			return nil, false, err
		}
		hasNext := (page+1)*pageSize < result.TotalCount
		return result.Results, hasNext, nil
	})
}

// EnableAllApnsClientsV1 enable push notifications for all clients.
//
// Required privileges: device-actions:execute. Legacy Jamf Pro privilege name(s): Send MDM command information in Jamf Pro API.
func (c *Client) EnableAllApnsClientsV1(ctx context.Context) error {
	prefix := c.transport.APIPrefix("pro", "v1")
	endpoint := prefix + "/apns-client-push-status/enable-all-clients"
	if err := c.transport.DoExpect(ctx, http.MethodPost, endpoint, nil, http.StatusAccepted, nil); err != nil {
		return fmt.Errorf("EnableAllApnsClientsV1: %w", err)
	}
	return nil
}

// GetEnableAllApnsClientsStatusV1 get status of enable all clients request.
//
// Required privileges: device-actions:read. Legacy Jamf Pro privilege name(s): View MDM command information in Jamf Pro API.
func (c *Client) GetEnableAllApnsClientsStatusV1(ctx context.Context) (*ApnsPushEnableRequest, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result ApnsPushEnableRequest
	endpoint := prefix + "/apns-client-push-status/enable-all-clients/status"
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetEnableAllApnsClientsStatusV1: %w", err)
	}
	return &result, nil
}

// EnableApnsClientV1 enable push notifications for a single client.
//
// Required privileges: device-actions:execute. Legacy Jamf Pro privilege name(s): Send MDM command information in Jamf Pro API.
func (c *Client) EnableApnsClientV1(ctx context.Context, request *EnablePushRequest) error {
	prefix := c.transport.APIPrefix("pro", "v1")
	endpoint := prefix + "/apns-client-push-status/enable-client"
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusNoContent, nil); err != nil {
		return fmt.Errorf("EnableApnsClientV1: %w", err)
	}
	return nil
}
