// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package pro

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"

	"github.com/jamf/jamfplatform-go-sdk/internal/client"
)

// ListAppRequestFormInputFieldsV1 search for Form Input Fields.
//
// Required privileges: app-request:read. Legacy Jamf Pro privilege name(s): Read App Request Settings.
func (c *Client) ListAppRequestFormInputFieldsV1(ctx context.Context) (*AppRequestFormInputFieldSearchResults, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result AppRequestFormInputFieldSearchResults
	endpoint := prefix + "/app-request/form-input-fields"
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("ListAppRequestFormInputFieldsV1: %w", err)
	}
	return &result, nil
}

// CreateAppRequestFormInputFieldV1 create Form Input Field record.
//
// Required privileges: app-request:update. Legacy Jamf Pro privilege name(s): Update App Request Settings.
func (c *Client) CreateAppRequestFormInputFieldV1(ctx context.Context, request *AppRequestFormInputField) (*AppRequestFormInputField, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result AppRequestFormInputField
	endpoint := prefix + "/app-request/form-input-fields"
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusOK, &result); err != nil {
		return nil, fmt.Errorf("CreateAppRequestFormInputFieldV1: %w", err)
	}
	return &result, nil
}

// ReorderAppRequestFormInputFieldsV1 replace all Form Input Fields.
//
// Required privileges: app-request:update. Legacy Jamf Pro privilege name(s): Update App Request Settings.
func (c *Client) ReorderAppRequestFormInputFieldsV1(ctx context.Context, request *[]AppRequestFormInputField) ([]AppRequestFormInputField, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result []AppRequestFormInputField
	endpoint := prefix + "/app-request/form-input-fields"
	if err := c.transport.DoWithContentType(ctx, http.MethodPut, endpoint, request, "application/json", http.StatusOK, &result); err != nil {
		return nil, fmt.Errorf("ReorderAppRequestFormInputFieldsV1: %w", err)
	}
	return result, nil
}

// GetAppRequestFormInputFieldV1 get specified Form Input Field object.
//
// Required privileges: app-request:read. Legacy Jamf Pro privilege name(s): Read App Request Settings.
//
// Parameters:
//   - id: Instance id of form input field record.
func (c *Client) GetAppRequestFormInputFieldV1(ctx context.Context, id string) (*AppRequestFormInputField, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result AppRequestFormInputField
	endpoint := fmt.Sprintf("%s/app-request/form-input-fields/%s", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetAppRequestFormInputFieldV1(%s): %w", id, err)
	}
	return &result, nil
}

// UpdateAppRequestFormInputFieldV1 update specified Form Input Field object.
//
// Required privileges: app-request:update. Legacy Jamf Pro privilege name(s): Update App Request Settings.
//
// Parameters:
//   - id: Instance id of form input field record.
func (c *Client) UpdateAppRequestFormInputFieldV1(ctx context.Context, id string, request *AppRequestFormInputField) (*AppRequestFormInputField, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result AppRequestFormInputField
	endpoint := fmt.Sprintf("%s/app-request/form-input-fields/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoWithContentType(ctx, http.MethodPut, endpoint, request, "application/json", http.StatusOK, &result); err != nil {
		return nil, fmt.Errorf("UpdateAppRequestFormInputFieldV1(%s): %w", id, err)
	}
	return &result, nil
}

// DeleteAppRequestFormInputFieldV1 remove specified Form Input Field record.
//
// Required privileges: app-request:update. Legacy Jamf Pro privilege name(s): Update App Request Settings.
//
// Parameters:
//   - id: Instance id of form input field record.
func (c *Client) DeleteAppRequestFormInputFieldV1(ctx context.Context, id string) error {
	prefix := c.transport.APIPrefix("pro", "v1")
	endpoint := fmt.Sprintf("%s/app-request/form-input-fields/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusNoContent, nil); err != nil {
		return fmt.Errorf("DeleteAppRequestFormInputFieldV1(%s): %w", id, err)
	}
	return nil
}

// GetAppRequestSettingsV1 get Applicastion Request Settings.
//
// Required privileges: app-request:read. Legacy Jamf Pro privilege name(s): Read App Request Settings.
func (c *Client) GetAppRequestSettingsV1(ctx context.Context) (*AppRequestSettings, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result AppRequestSettings
	endpoint := prefix + "/app-request/settings"
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetAppRequestSettingsV1: %w", err)
	}
	return &result, nil
}

// UpdateAppRequestSettingsV1 update Application Request Settings.
//
// Required privileges: app-request:update. Legacy Jamf Pro privilege name(s): Update App Request Settings.
func (c *Client) UpdateAppRequestSettingsV1(ctx context.Context, request *AppRequestSettings) (*AppRequestSettings, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result AppRequestSettings
	endpoint := prefix + "/app-request/settings"
	if err := c.transport.DoWithContentType(ctx, http.MethodPut, endpoint, request, "application/json", http.StatusOK, &result); err != nil {
		return nil, fmt.Errorf("UpdateAppRequestSettingsV1: %w", err)
	}
	return &result, nil
}

// ResolveAppRequestFormInputFieldV1IDByName looks up a AppRequestFormInputFieldV1 by its title field and returns the ID. Returns *APIResponseError with HasStatus(404) when no match exists, or *AmbiguousMatchError when multiple resources share the name.
func (c *Client) ResolveAppRequestFormInputFieldV1IDByName(ctx context.Context, name string) (string, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	listPath := prefix + "/app-request/form-input-fields"
	id, _, err := c.transport.ResolveByNameClient(ctx, listPath, "", "", "title", "id", name)
	if err != nil {
		return "", fmt.Errorf("ResolveAppRequestFormInputFieldV1IDByName(%s): %w", name, err)
	}
	return id, nil
}

// ResolveAppRequestFormInputFieldV1ByName looks up a AppRequestFormInputFieldV1 by its title field and returns the decoded resource. Shares the same HTTP call as the ID-only variant; error semantics are identical.
func (c *Client) ResolveAppRequestFormInputFieldV1ByName(ctx context.Context, name string) (*AppRequestFormInputField, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	listPath := prefix + "/app-request/form-input-fields"
	_, raw, err := c.transport.ResolveByNameClient(ctx, listPath, "", "", "title", "id", name)
	if err != nil {
		return nil, fmt.Errorf("ResolveAppRequestFormInputFieldV1ByName(%s): %w", name, err)
	}
	var out AppRequestFormInputField
	if err := json.Unmarshal(raw, &out); err != nil {
		return nil, fmt.Errorf("ResolveAppRequestFormInputFieldV1ByName(%s): decoding matched element: %w", name, err)
	}
	return &out, nil
}

// ApplyAppRequestFormInputFieldV1 creates or updates a AppRequestFormInputFieldV1 by name. If a resource with the specified name exists, it is updated; if not found, a new resource is created. Returns the resource ID, whether it was created (true) or updated (false), and any error. An *AmbiguousMatchError is returned if multiple resources match the name.
func (c *Client) ApplyAppRequestFormInputFieldV1(ctx context.Context, request *AppRequestFormInputField) (string, bool, error) {
	name := request.Title
	if name == "" {
		return "", false, fmt.Errorf("ApplyAppRequestFormInputFieldV1: Title must not be empty")
	}
	id, err := c.ResolveAppRequestFormInputFieldV1IDByName(ctx, name)
	if err != nil {
		if apiErr := client.AsAPIError(err); apiErr != nil && apiErr.HasStatus(404) {
			resp, createErr := c.CreateAppRequestFormInputFieldV1(ctx, request)
			if createErr != nil {
				return "", false, fmt.Errorf("ApplyAppRequestFormInputFieldV1: create: %w", createErr)
			}
			return fmt.Sprintf("%d", *resp.ID), true, nil
		}
		return "", false, fmt.Errorf("ApplyAppRequestFormInputFieldV1: resolve: %w", err)
	}
	_, err = c.UpdateAppRequestFormInputFieldV1(ctx, id, request)
	if err != nil {
		return "", false, fmt.Errorf("ApplyAppRequestFormInputFieldV1: update(%s): %w", id, err)
	}
	return id, false, nil
}
