// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package pro

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"github.com/jamf/jamfplatform-go-sdk/internal/client"
)

// ListCategoriesV1 get Category objects.
//
// Required privileges: categories:read, self-service:read. Legacy Jamf Pro privilege name(s): Read Categories, Read Self Service.
// All of them are required, not alternatives.
// The scoped and legacy lists are independent sets, not pairs: do not match them by position.
//
// Parameters:
//   - sort: Sorting criteria in the format: property:asc/desc. Default sort is id:asc. Multiple sort criteria
//     are supported and must be separated with a comma. Example: sort=date:desc,name:asc.
//   - filter: Query in the RSQL format, allowing to filter categories collection. Default filter is empty query -
//     returning all results for the requested page. Fields allowed in the query: name, priority. This
//     param can be combined with paging and sorting. Example: filter=name=="Apps*" and priority>=5.
func (c *Client) ListCategoriesV1(ctx context.Context, sort []string, filter string) ([]Category, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	return client.ListAllPages(ctx, 2000, func(ctx context.Context, page, pageSize int) ([]Category, bool, error) {
		params := url.Values{}
		params.Set("page", strconv.Itoa(page))
		params.Set("page-size", strconv.Itoa(pageSize))
		if len(sort) > 0 {
			params.Set("sort", strings.Join(sort, ","))
		}
		if filter != "" {
			params.Set("filter", filter)
		}

		endpoint := prefix + "/categories"
		if encoded := params.Encode(); encoded != "" {
			endpoint += "?" + encoded
		}
		var result struct {
			TotalCount int        `json:"totalCount"`
			Results    []Category `json:"results"`
		}
		if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
			return nil, false, err
		}
		hasNext := (page+1)*pageSize < result.TotalCount
		return result.Results, hasNext, nil
	})
}

// CreateCategoryV1 create Category record.
//
// Required privileges: categories:create. Legacy Jamf Pro privilege name(s): Create Categories.
func (c *Client) CreateCategoryV1(ctx context.Context, request *Category) (*HrefResponse, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result HrefResponse
	endpoint := prefix + "/categories"
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("CreateCategoryV1: %w", err)
	}
	return &result, nil
}

// DeleteMultipleCategoriesV1 delete multiple Categories by their IDs.
//
// Required privileges: categories:delete. Legacy Jamf Pro privilege name(s): Delete Categories.
func (c *Client) DeleteMultipleCategoriesV1(ctx context.Context, request *Ids) error {
	prefix := c.transport.APIPrefix("pro", "v1")
	endpoint := prefix + "/categories/delete-multiple"
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusNoContent, nil); err != nil {
		return fmt.Errorf("DeleteMultipleCategoriesV1: %w", err)
	}
	return nil
}

// GetCategoryV1 get specified Category object.
//
// Required privileges: categories:read. Legacy Jamf Pro privilege name(s): Read Categories.
//
// Parameters:
//   - id: instance id of category record.
func (c *Client) GetCategoryV1(ctx context.Context, id string) (*Category, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result Category
	endpoint := fmt.Sprintf("%s/categories/%s", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetCategoryV1(%s): %w", id, err)
	}
	return &result, nil
}

// UpdateCategoryV1 update specified Category object.
//
// Required privileges: categories:update. Legacy Jamf Pro privilege name(s): Update Categories.
//
// Parameters:
//   - id: instance id of category record.
func (c *Client) UpdateCategoryV1(ctx context.Context, id string, request *Category) (*Category, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result Category
	endpoint := fmt.Sprintf("%s/categories/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoWithContentType(ctx, http.MethodPut, endpoint, request, "application/json", http.StatusOK, &result); err != nil {
		return nil, fmt.Errorf("UpdateCategoryV1(%s): %w", id, err)
	}
	return &result, nil
}

// DeleteCategoryV1 remove specified Category record.
//
// Required privileges: categories:delete. Legacy Jamf Pro privilege name(s): Delete Categories.
//
// Parameters:
//   - id: instance id of category record.
func (c *Client) DeleteCategoryV1(ctx context.Context, id string) error {
	prefix := c.transport.APIPrefix("pro", "v1")
	endpoint := fmt.Sprintf("%s/categories/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusNoContent, nil); err != nil {
		return fmt.Errorf("DeleteCategoryV1(%s): %w", id, err)
	}
	return nil
}

// ListCategoryHistoryV1 get specified Category history object.
//
// Required privileges: categories:read. Legacy Jamf Pro privilege name(s): Read Categories.
//
// Parameters:
//   - id: instance id of category history record.
//   - sort: Sorting criteria in the format: property:asc/desc. Default sort is id:asc. Multiple sort criteria
//     are supported and must be separated with a comma. Example: sort=date:desc,name:asc.
//   - filter: Query in the RSQL format, allowing to filter history notes collection. Default filter is empty query
//   - returning all results for the requested page. Fields allowed in the query: username, date, note,
//     details. This param can be combined with paging and sorting. Example: filter=username!=admin and
//     details==*disabled* and date<2019-12-15.
func (c *Client) ListCategoryHistoryV1(ctx context.Context, id string, sort []string, filter string) ([]ObjectHistory, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	return client.ListAllPages(ctx, 2000, func(ctx context.Context, page, pageSize int) ([]ObjectHistory, bool, error) {
		params := url.Values{}
		params.Set("page", strconv.Itoa(page))
		params.Set("page-size", strconv.Itoa(pageSize))
		if len(sort) > 0 {
			params.Set("sort", strings.Join(sort, ","))
		}
		if filter != "" {
			params.Set("filter", filter)
		}

		endpoint := fmt.Sprintf("%s/categories/%s/history", prefix, url.PathEscape(id))
		if encoded := params.Encode(); encoded != "" {
			endpoint += "?" + encoded
		}
		var result struct {
			TotalCount int             `json:"totalCount"`
			Results    []ObjectHistory `json:"results"`
		}
		if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
			return nil, false, err
		}
		hasNext := (page+1)*pageSize < result.TotalCount
		return result.Results, hasNext, nil
	})
}

// CreateCategoryHistoryNoteV1 add specified Category history object notes.
//
// Required privileges: categories:update. Legacy Jamf Pro privilege name(s): Update Categories.
//
// Parameters:
//   - id: instance id of category history record.
func (c *Client) CreateCategoryHistoryNoteV1(ctx context.Context, id string, request *ObjectHistoryNote) (*ObjectHistory, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result ObjectHistory
	endpoint := fmt.Sprintf("%s/categories/%s/history", prefix, url.PathEscape(id))
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusOK, &result); err != nil {
		return nil, fmt.Errorf("CreateCategoryHistoryNoteV1(%s): %w", id, err)
	}
	return &result, nil
}

// ResolveCategoryV1IDByName looks up a CategoryV1 by its name field and returns the ID. Returns *APIResponseError with HasStatus(404) when no match exists, or *AmbiguousMatchError when multiple resources share the name.
func (c *Client) ResolveCategoryV1IDByName(ctx context.Context, name string) (string, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	listPath := prefix + "/categories"
	id, _, err := c.transport.ResolveByNameFiltered(ctx, listPath, "", "name", "name", "id", name)
	if err != nil {
		return "", fmt.Errorf("ResolveCategoryV1IDByName(%s): %w", name, err)
	}
	return id, nil
}

// ResolveCategoryV1ByName looks up a CategoryV1 by its name field and returns the decoded resource. Shares the same HTTP call as the ID-only variant; error semantics are identical.
func (c *Client) ResolveCategoryV1ByName(ctx context.Context, name string) (*Category, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	listPath := prefix + "/categories"
	_, raw, err := c.transport.ResolveByNameFiltered(ctx, listPath, "", "name", "name", "id", name)
	if err != nil {
		return nil, fmt.Errorf("ResolveCategoryV1ByName(%s): %w", name, err)
	}
	var out Category
	if err := json.Unmarshal(raw, &out); err != nil {
		return nil, fmt.Errorf("ResolveCategoryV1ByName(%s): decoding matched element: %w", name, err)
	}
	return &out, nil
}

// ApplyCategoryV1 creates or updates a CategoryV1 by name. If a resource with the specified name exists, it is updated; if not found, a new resource is created. Returns the resource ID, whether it was created (true) or updated (false), and any error. An *AmbiguousMatchError is returned if multiple resources match the name.
func (c *Client) ApplyCategoryV1(ctx context.Context, request *Category) (string, bool, error) {
	name := request.Name
	if name == "" {
		return "", false, fmt.Errorf("ApplyCategoryV1: Name must not be empty")
	}
	id, err := c.ResolveCategoryV1IDByName(ctx, name)
	if err != nil {
		if apiErr := client.AsAPIError(err); apiErr != nil && apiErr.HasStatus(404) {
			resp, createErr := c.CreateCategoryV1(ctx, request)
			if createErr != nil {
				return "", false, fmt.Errorf("ApplyCategoryV1: create: %w", createErr)
			}
			return resp.ID, true, nil
		}
		return "", false, fmt.Errorf("ApplyCategoryV1: resolve: %w", err)
	}
	_, err = c.UpdateCategoryV1(ctx, id, request)
	if err != nil {
		return "", false, fmt.Errorf("ApplyCategoryV1: update(%s): %w", id, err)
	}
	return id, false, nil
}
