// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

// Package pro provides typed access to Jamf Platform pro API endpoints.
package pro

import (
	"github.com/jamf/jamfplatform-go-sdk/internal/client"
	"github.com/jamf/jamfplatform-go-sdk/jamfplatform"
)

// Client provides typed methods for pro operations.
type Client struct {
	transport *client.Transport
}

// New creates a pro client that shares the authenticated transport of the
// given root client.
func New(base *jamfplatform.Client) *Client {
	return &Client{transport: base.Transport()}
}
