// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package pro

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"github.com/jamf/jamfplatform-go-sdk/internal/client"
)

// ListComputerGroupsV1 returns the list of all computer groups.
//
// Required privileges: device-groups:read. Legacy Jamf Pro privilege name(s): Read Smart Computer Groups, Read Static Computer Groups.
// The scoped and legacy lists are independent sets, not pairs: do not match them by position.
func (c *Client) ListComputerGroupsV1(ctx context.Context) ([]ComputerGroup, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result []ComputerGroup
	endpoint := prefix + "/computer-groups"
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("ListComputerGroupsV1: %w", err)
	}
	return result, nil
}

// ListSmartComputerGroupsV3 search for Smart Computer Groups.
//
// Required privileges: device-groups:read. Legacy Jamf Pro privilege name(s): Read Smart Computer Groups.
//
// Parameters:
//   - sort: Sorting criteria in the format: property:asc/desc. Default sort is id:asc. Multiple sort criteria
//     are supported and must be separated with a comma. Example: sort=name:asc.
//   - filter: Query in the RSQL format, allowing to filter smart computer group collection. Default filter is
//     empty query - returning all results for the requested page. Fields allowed in the query: id, name,
//     siteId. The siteId field can only be filtered by admins with full access. Any sited admin will have
//     siteId filtered automatically. Example: name=="*group*".
func (c *Client) ListSmartComputerGroupsV3(ctx context.Context, sort []string, filter string) ([]SmartComputerGroupSearch, error) {
	prefix := c.transport.APIPrefix("pro", "v3")
	return client.ListAllPages(ctx, 2000, func(ctx context.Context, page, pageSize int) ([]SmartComputerGroupSearch, bool, error) {
		params := url.Values{}
		params.Set("page", strconv.Itoa(page))
		params.Set("page-size", strconv.Itoa(pageSize))
		if len(sort) > 0 {
			params.Set("sort", strings.Join(sort, ","))
		}
		if filter != "" {
			params.Set("filter", filter)
		}

		endpoint := prefix + "/computer-groups/smart-groups"
		if encoded := params.Encode(); encoded != "" {
			endpoint += "?" + encoded
		}
		var result struct {
			TotalCount int                        `json:"totalCount"`
			Results    []SmartComputerGroupSearch `json:"results"`
		}
		if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
			return nil, false, err
		}
		hasNext := (page+1)*pageSize < result.TotalCount
		return result.Results, hasNext, nil
	})
}

// CreateSmartComputerGroupV3 create a Smart Computer Group.
//
// Required privileges: device-groups:create. Legacy Jamf Pro privilege name(s): Create Smart Computer Groups.
//
// Parameters:
//   - platform: Optional. Return platform identifiers instead of internal identifiers when set to true.
func (c *Client) CreateSmartComputerGroupV3(ctx context.Context, request *SmartComputerGroupV3, platform bool) (*HrefResponse, error) {
	prefix := c.transport.APIPrefix("pro", "v3")
	var result HrefResponse
	endpoint := prefix + "/computer-groups/smart-groups"
	params := url.Values{}
	if platform {
		params.Set("platform", "true")
	}
	if encoded := params.Encode(); encoded != "" {
		endpoint += "?" + encoded
	}
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("CreateSmartComputerGroupV3: %w", err)
	}
	return &result, nil
}

// GetSmartComputerGroupV3 get Smart Computer Group by Id.
//
// Required privileges: device-groups:read. Legacy Jamf Pro privilege name(s): Read Smart Computer Groups.
//
// Parameters:
//   - id: instance id of smart computer group.
func (c *Client) GetSmartComputerGroupV3(ctx context.Context, id string) (*SmartComputerGroupV3, error) {
	prefix := c.transport.APIPrefix("pro", "v3")
	var result SmartComputerGroupV3
	endpoint := fmt.Sprintf("%s/computer-groups/smart-groups/%s", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetSmartComputerGroupV3(%s): %w", id, err)
	}
	return &result, nil
}

// UpdateSmartComputerGroupV3 update a Smart Computer Group.
//
// Required privileges: device-groups:update. Legacy Jamf Pro privilege name(s): Update Smart Computer Groups.
//
// Parameters:
//   - id: id of target Smart Computer Group.
func (c *Client) UpdateSmartComputerGroupV3(ctx context.Context, id string, request *SmartComputerGroupV3) (*SmartComputerGroupV3, error) {
	prefix := c.transport.APIPrefix("pro", "v3")
	var result SmartComputerGroupV3
	endpoint := fmt.Sprintf("%s/computer-groups/smart-groups/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoWithContentType(ctx, http.MethodPut, endpoint, request, "application/json", http.StatusAccepted, &result); err != nil {
		return nil, fmt.Errorf("UpdateSmartComputerGroupV3(%s): %w", id, err)
	}
	return &result, nil
}

// DeleteSmartComputerGroupV3 remove specified Smart Computer Group.
//
// Required privileges: device-groups:delete. Legacy Jamf Pro privilege name(s): Delete Smart Computer Groups.
//
// Parameters:
//   - id: id of target Smart Computer Group.
func (c *Client) DeleteSmartComputerGroupV3(ctx context.Context, id string) error {
	prefix := c.transport.APIPrefix("pro", "v3")
	endpoint := fmt.Sprintf("%s/computer-groups/smart-groups/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusNoContent, nil); err != nil {
		return fmt.Errorf("DeleteSmartComputerGroupV3(%s): %w", id, err)
	}
	return nil
}

// GetSmartComputerGroupMembershipV3 get the membership of a Smart Computer Group.
//
// Required privileges: device-groups:read. Legacy Jamf Pro privilege name(s): Read Smart Computer Groups.
//
// Parameters:
//   - id: id of the Smart Computer Group.
func (c *Client) GetSmartComputerGroupMembershipV3(ctx context.Context, id string) (*SmartGroupMembership, error) {
	prefix := c.transport.APIPrefix("pro", "v3")
	var result SmartGroupMembership
	endpoint := fmt.Sprintf("%s/computer-groups/smart-group-membership/%s", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetSmartComputerGroupMembershipV3(%s): %w", id, err)
	}
	return &result, nil
}

// ListStaticComputerGroupsV3 search for Static Computer Groups.
//
// Required privileges: device-groups:read. Legacy Jamf Pro privilege name(s): Read Static Computer Groups.
//
// Parameters:
//   - sort: Sorting criteria in the format: property:asc/desc. Default sort is id:asc. Multiple sort criteria
//     are supported and must be separated with a comma. Example: sort=name:asc.
//   - filter: Query in the RSQL format, allowing to filter static computer group collection. Default filter is
//     empty query - returning all results for the requested page. Fields allowed in the query: id, name,
//     siteId. The siteId field can only be filtered by admins with full access. Any sited admin will have
//     siteId filtered automatically. Example: name=="*group*".
func (c *Client) ListStaticComputerGroupsV3(ctx context.Context, sort []string, filter string) ([]StaticComputerGroupSummary, error) {
	prefix := c.transport.APIPrefix("pro", "v3")
	return client.ListAllPages(ctx, 2000, func(ctx context.Context, page, pageSize int) ([]StaticComputerGroupSummary, bool, error) {
		params := url.Values{}
		params.Set("page", strconv.Itoa(page))
		params.Set("page-size", strconv.Itoa(pageSize))
		if len(sort) > 0 {
			params.Set("sort", strings.Join(sort, ","))
		}
		if filter != "" {
			params.Set("filter", filter)
		}

		endpoint := prefix + "/computer-groups/static-groups"
		if encoded := params.Encode(); encoded != "" {
			endpoint += "?" + encoded
		}
		var result struct {
			TotalCount int                          `json:"totalCount"`
			Results    []StaticComputerGroupSummary `json:"results"`
		}
		if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
			return nil, false, err
		}
		hasNext := (page+1)*pageSize < result.TotalCount
		return result.Results, hasNext, nil
	})
}

// CreateStaticComputerGroupV3 create membership of a static computer group.
//
// Required privileges: device-groups:create. Legacy Jamf Pro privilege name(s): Create Static Computer Groups.
//
// Parameters:
//   - platform: Optional. Return platform identifiers instead of internal identifiers when set to true.
func (c *Client) CreateStaticComputerGroupV3(ctx context.Context, request *StaticComputerGroupAssignment, platform bool) (*HrefResponse, error) {
	prefix := c.transport.APIPrefix("pro", "v3")
	var result HrefResponse
	endpoint := prefix + "/computer-groups/static-groups"
	params := url.Values{}
	if platform {
		params.Set("platform", "true")
	}
	if encoded := params.Encode(); encoded != "" {
		endpoint += "?" + encoded
	}
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("CreateStaticComputerGroupV3: %w", err)
	}
	return &result, nil
}

// GetStaticComputerGroupV3 get Static Computer Group by Id.
//
// Required privileges: device-groups:read. Legacy Jamf Pro privilege name(s): Read Static Computer Groups.
//
// Parameters:
//   - id: instance id of static computer group.
func (c *Client) GetStaticComputerGroupV3(ctx context.Context, id string) (*StaticComputerGroup, error) {
	prefix := c.transport.APIPrefix("pro", "v3")
	var result StaticComputerGroup
	endpoint := fmt.Sprintf("%s/computer-groups/static-groups/%s", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetStaticComputerGroupV3(%s): %w", id, err)
	}
	return &result, nil
}

// UpdateStaticComputerGroupV3 update membership of a static computer group.
//
// Required privileges: device-groups:update. Legacy Jamf Pro privilege name(s): Update Static Computer Groups.
//
// Parameters:
//   - id: instance id of a static computer group.
func (c *Client) UpdateStaticComputerGroupV3(ctx context.Context, id string, request *StaticComputerGroupAssignment) (*StaticComputerGroupAssignment, error) {
	prefix := c.transport.APIPrefix("pro", "v3")
	var result StaticComputerGroupAssignment
	endpoint := fmt.Sprintf("%s/computer-groups/static-groups/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoWithContentType(ctx, http.MethodPut, endpoint, request, "application/json", http.StatusAccepted, &result); err != nil {
		return nil, fmt.Errorf("UpdateStaticComputerGroupV3(%s): %w", id, err)
	}
	return &result, nil
}

// DeleteStaticComputerGroupV3 remove Static Computer Group by Id.
//
// Required privileges: device-groups:delete. Legacy Jamf Pro privilege name(s): Delete Static Computer Groups.
//
// Parameters:
//   - id: instance id of static computer group.
func (c *Client) DeleteStaticComputerGroupV3(ctx context.Context, id string) error {
	prefix := c.transport.APIPrefix("pro", "v3")
	endpoint := fmt.Sprintf("%s/computer-groups/static-groups/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusNoContent, nil); err != nil {
		return fmt.Errorf("DeleteStaticComputerGroupV3(%s): %w", id, err)
	}
	return nil
}

// ResolveComputerGroupV1IDByName looks up a ComputerGroupV1 by its name field and returns the ID. Returns *APIResponseError with HasStatus(404) when no match exists, or *AmbiguousMatchError when multiple resources share the name.
func (c *Client) ResolveComputerGroupV1IDByName(ctx context.Context, name string) (string, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	listPath := prefix + "/computer-groups"
	id, _, err := c.transport.ResolveByNameClient(ctx, listPath, "", "", "name", "id", name)
	if err != nil {
		return "", fmt.Errorf("ResolveComputerGroupV1IDByName(%s): %w", name, err)
	}
	return id, nil
}

// ResolveComputerGroupV1ByName looks up a ComputerGroupV1 by its name field and returns the decoded resource. Shares the same HTTP call as the ID-only variant; error semantics are identical.
func (c *Client) ResolveComputerGroupV1ByName(ctx context.Context, name string) (*ComputerGroup, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	listPath := prefix + "/computer-groups"
	_, raw, err := c.transport.ResolveByNameClient(ctx, listPath, "", "", "name", "id", name)
	if err != nil {
		return nil, fmt.Errorf("ResolveComputerGroupV1ByName(%s): %w", name, err)
	}
	var out ComputerGroup
	if err := json.Unmarshal(raw, &out); err != nil {
		return nil, fmt.Errorf("ResolveComputerGroupV1ByName(%s): decoding matched element: %w", name, err)
	}
	return &out, nil
}

// ResolveSmartComputerGroupV3IDByName looks up a SmartComputerGroupV3 by its name field and returns the ID. Returns *APIResponseError with HasStatus(404) when no match exists, or *AmbiguousMatchError when multiple resources share the name.
func (c *Client) ResolveSmartComputerGroupV3IDByName(ctx context.Context, name string) (string, error) {
	prefix := c.transport.APIPrefix("pro", "v3")
	listPath := prefix + "/computer-groups/smart-groups"
	id, _, err := c.transport.ResolveByNameFiltered(ctx, listPath, "", "name", "name", "id", name)
	if err != nil {
		return "", fmt.Errorf("ResolveSmartComputerGroupV3IDByName(%s): %w", name, err)
	}
	return id, nil
}

// ResolveSmartComputerGroupV3ByName looks up a SmartComputerGroupV3 by its name field and returns the decoded resource. Shares the same HTTP call as the ID-only variant; error semantics are identical.
func (c *Client) ResolveSmartComputerGroupV3ByName(ctx context.Context, name string) (*SmartComputerGroupSearch, error) {
	prefix := c.transport.APIPrefix("pro", "v3")
	listPath := prefix + "/computer-groups/smart-groups"
	_, raw, err := c.transport.ResolveByNameFiltered(ctx, listPath, "", "name", "name", "id", name)
	if err != nil {
		return nil, fmt.Errorf("ResolveSmartComputerGroupV3ByName(%s): %w", name, err)
	}
	var out SmartComputerGroupSearch
	if err := json.Unmarshal(raw, &out); err != nil {
		return nil, fmt.Errorf("ResolveSmartComputerGroupV3ByName(%s): decoding matched element: %w", name, err)
	}
	return &out, nil
}

// ResolveStaticComputerGroupV3IDByName looks up a StaticComputerGroupV3 by its name field and returns the ID. Returns *APIResponseError with HasStatus(404) when no match exists, or *AmbiguousMatchError when multiple resources share the name.
func (c *Client) ResolveStaticComputerGroupV3IDByName(ctx context.Context, name string) (string, error) {
	prefix := c.transport.APIPrefix("pro", "v3")
	listPath := prefix + "/computer-groups/static-groups"
	id, _, err := c.transport.ResolveByNameFiltered(ctx, listPath, "", "name", "name", "id", name)
	if err != nil {
		return "", fmt.Errorf("ResolveStaticComputerGroupV3IDByName(%s): %w", name, err)
	}
	return id, nil
}

// ResolveStaticComputerGroupV3ByName looks up a StaticComputerGroupV3 by its name field and returns the decoded resource. Shares the same HTTP call as the ID-only variant; error semantics are identical.
func (c *Client) ResolveStaticComputerGroupV3ByName(ctx context.Context, name string) (*StaticComputerGroupSummary, error) {
	prefix := c.transport.APIPrefix("pro", "v3")
	listPath := prefix + "/computer-groups/static-groups"
	_, raw, err := c.transport.ResolveByNameFiltered(ctx, listPath, "", "name", "name", "id", name)
	if err != nil {
		return nil, fmt.Errorf("ResolveStaticComputerGroupV3ByName(%s): %w", name, err)
	}
	var out StaticComputerGroupSummary
	if err := json.Unmarshal(raw, &out); err != nil {
		return nil, fmt.Errorf("ResolveStaticComputerGroupV3ByName(%s): decoding matched element: %w", name, err)
	}
	return &out, nil
}

// ApplySmartComputerGroupV3 creates or updates a SmartComputerGroupV3 by name. If a resource with the specified name exists, it is updated; if not found, a new resource is created. Returns the resource ID, whether it was created (true) or updated (false), and any error. An *AmbiguousMatchError is returned if multiple resources match the name.
func (c *Client) ApplySmartComputerGroupV3(ctx context.Context, request *SmartComputerGroupV3, platform bool) (string, bool, error) {
	name := request.Name
	if name == "" {
		return "", false, fmt.Errorf("ApplySmartComputerGroupV3: Name must not be empty")
	}
	id, err := c.ResolveSmartComputerGroupV3IDByName(ctx, name)
	if err != nil {
		if apiErr := client.AsAPIError(err); apiErr != nil && apiErr.HasStatus(404) {
			resp, createErr := c.CreateSmartComputerGroupV3(ctx, request, platform)
			if createErr != nil {
				return "", false, fmt.Errorf("ApplySmartComputerGroupV3: create: %w", createErr)
			}
			return resp.ID, true, nil
		}
		return "", false, fmt.Errorf("ApplySmartComputerGroupV3: resolve: %w", err)
	}
	_, err = c.UpdateSmartComputerGroupV3(ctx, id, request)
	if err != nil {
		return "", false, fmt.Errorf("ApplySmartComputerGroupV3: update(%s): %w", id, err)
	}
	return id, false, nil
}

// ApplyStaticComputerGroupV3 creates or updates a StaticComputerGroupV3 by name. If a resource with the specified name exists, it is updated; if not found, a new resource is created. Returns the resource ID, whether it was created (true) or updated (false), and any error. An *AmbiguousMatchError is returned if multiple resources match the name.
func (c *Client) ApplyStaticComputerGroupV3(ctx context.Context, request *StaticComputerGroupAssignment, platform bool) (string, bool, error) {
	name := request.Name
	if name == "" {
		return "", false, fmt.Errorf("ApplyStaticComputerGroupV3: Name must not be empty")
	}
	id, err := c.ResolveStaticComputerGroupV3IDByName(ctx, name)
	if err != nil {
		if apiErr := client.AsAPIError(err); apiErr != nil && apiErr.HasStatus(404) {
			resp, createErr := c.CreateStaticComputerGroupV3(ctx, request, platform)
			if createErr != nil {
				return "", false, fmt.Errorf("ApplyStaticComputerGroupV3: create: %w", createErr)
			}
			return resp.ID, true, nil
		}
		return "", false, fmt.Errorf("ApplyStaticComputerGroupV3: resolve: %w", err)
	}
	_, err = c.UpdateStaticComputerGroupV3(ctx, id, request)
	if err != nil {
		return "", false, fmt.Errorf("ApplyStaticComputerGroupV3: update(%s): %w", id, err)
	}
	return id, false, nil
}
