// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package pro

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"github.com/jamf/jamfplatform-go-sdk/internal/client"
)

// ListDepartmentsV1 search for Departments.
//
// Required privileges: departments:read. Legacy Jamf Pro privilege name(s): Read Departments.
//
// Parameters:
//   - sort: Sorting criteria in the format: property:asc/desc. Default sort is id:asc. Multiple sort criteria
//     are supported and must be separated with a comma. Example: sort=date:desc,name:asc.
//   - filter: Query in the RSQL format, allowing to filter department collection. Default filter is empty query -
//     returning all results for the requested page. Fields allowed in the query: id, name. Example:
//     name=="*department*".
func (c *Client) ListDepartmentsV1(ctx context.Context, sort []string, filter string) ([]Department, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	return client.ListAllPages(ctx, 2000, func(ctx context.Context, page, pageSize int) ([]Department, bool, error) {
		params := url.Values{}
		params.Set("page", strconv.Itoa(page))
		params.Set("page-size", strconv.Itoa(pageSize))
		if len(sort) > 0 {
			params.Set("sort", strings.Join(sort, ","))
		}
		if filter != "" {
			params.Set("filter", filter)
		}

		endpoint := prefix + "/departments"
		if encoded := params.Encode(); encoded != "" {
			endpoint += "?" + encoded
		}
		var result struct {
			TotalCount int          `json:"totalCount"`
			Results    []Department `json:"results"`
		}
		if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
			return nil, false, err
		}
		hasNext := (page+1)*pageSize < result.TotalCount
		return result.Results, hasNext, nil
	})
}

// CreateDepartmentV1 create department record.
//
// Required privileges: departments:create. Legacy Jamf Pro privilege name(s): Create Departments.
func (c *Client) CreateDepartmentV1(ctx context.Context, request *Department) (*HrefResponse, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result HrefResponse
	endpoint := prefix + "/departments"
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("CreateDepartmentV1: %w", err)
	}
	return &result, nil
}

// DeleteMultipleDepartmentsV1 deletes all departments by ids passed in body.
//
// Required privileges: departments:delete. Legacy Jamf Pro privilege name(s): Delete Departments.
func (c *Client) DeleteMultipleDepartmentsV1(ctx context.Context, request *Ids) error {
	prefix := c.transport.APIPrefix("pro", "v1")
	endpoint := prefix + "/departments/delete-multiple"
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusNoContent, nil); err != nil {
		return fmt.Errorf("DeleteMultipleDepartmentsV1: %w", err)
	}
	return nil
}

// GetDepartmentV1 get specified Department object.
//
// Required privileges: departments:read. Legacy Jamf Pro privilege name(s): Read Departments.
//
// Parameters:
//   - id: instance id of department record.
func (c *Client) GetDepartmentV1(ctx context.Context, id string) (*Department, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result Department
	endpoint := fmt.Sprintf("%s/departments/%s", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetDepartmentV1(%s): %w", id, err)
	}
	return &result, nil
}

// UpdateDepartmentV1 update specified department object.
//
// Required privileges: departments:update. Legacy Jamf Pro privilege name(s): Update Departments.
//
// Parameters:
//   - id: instance id of department record.
func (c *Client) UpdateDepartmentV1(ctx context.Context, id string, request *Department) (*Department, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result Department
	endpoint := fmt.Sprintf("%s/departments/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoWithContentType(ctx, http.MethodPut, endpoint, request, "application/json", http.StatusOK, &result); err != nil {
		return nil, fmt.Errorf("UpdateDepartmentV1(%s): %w", id, err)
	}
	return &result, nil
}

// DeleteDepartmentV1 remove specified department record.
//
// Required privileges: departments:delete. Legacy Jamf Pro privilege name(s): Delete Departments.
//
// Parameters:
//   - id: instance id of department record.
func (c *Client) DeleteDepartmentV1(ctx context.Context, id string) error {
	prefix := c.transport.APIPrefix("pro", "v1")
	endpoint := fmt.Sprintf("%s/departments/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusNoContent, nil); err != nil {
		return fmt.Errorf("DeleteDepartmentV1(%s): %w", id, err)
	}
	return nil
}

// ListDepartmentHistoryV1 get specified Department history object.
//
// Required privileges: departments:read. Legacy Jamf Pro privilege name(s): Read Departments.
//
// Parameters:
//   - id: instance id of department history record.
//   - sort: Sorting criteria in the format: property:asc/desc. Default sort is date:desc. Multiple sort criteria
//     are supported and must be separated with a comma. Example: sort=date:desc,name:asc.
//   - filter: Query in the RSQL format, allowing to filter history notes collection. Default filter is empty query
//   - returning all results for the requested page. Fields allowed in the query: username, date, note,
//     details. This param can be combined with paging and sorting. Example: filter=username!=admin and
//     details==*disabled* and date<2019-12-15.
func (c *Client) ListDepartmentHistoryV1(ctx context.Context, id string, sort []string, filter string) ([]ObjectHistory, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	return client.ListAllPages(ctx, 2000, func(ctx context.Context, page, pageSize int) ([]ObjectHistory, bool, error) {
		params := url.Values{}
		params.Set("page", strconv.Itoa(page))
		params.Set("page-size", strconv.Itoa(pageSize))
		if len(sort) > 0 {
			params.Set("sort", strings.Join(sort, ","))
		}
		if filter != "" {
			params.Set("filter", filter)
		}

		endpoint := fmt.Sprintf("%s/departments/%s/history", prefix, url.PathEscape(id))
		if encoded := params.Encode(); encoded != "" {
			endpoint += "?" + encoded
		}
		var result struct {
			TotalCount int             `json:"totalCount"`
			Results    []ObjectHistory `json:"results"`
		}
		if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
			return nil, false, err
		}
		hasNext := (page+1)*pageSize < result.TotalCount
		return result.Results, hasNext, nil
	})
}

// CreateDepartmentHistoryNoteV1 add specified Department history object notes.
//
// Required privileges: departments:update. Legacy Jamf Pro privilege name(s): Update Departments.
//
// Parameters:
//   - id: instance id of department history record.
func (c *Client) CreateDepartmentHistoryNoteV1(ctx context.Context, id string, request *ObjectHistoryNote) (*HrefResponse, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result HrefResponse
	endpoint := fmt.Sprintf("%s/departments/%s/history", prefix, url.PathEscape(id))
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("CreateDepartmentHistoryNoteV1(%s): %w", id, err)
	}
	return &result, nil
}

// ResolveDepartmentV1IDByName looks up a DepartmentV1 by its name field and returns the ID. Returns *APIResponseError with HasStatus(404) when no match exists, or *AmbiguousMatchError when multiple resources share the name.
func (c *Client) ResolveDepartmentV1IDByName(ctx context.Context, name string) (string, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	listPath := prefix + "/departments"
	id, _, err := c.transport.ResolveByNameFiltered(ctx, listPath, "", "name", "name", "id", name)
	if err != nil {
		return "", fmt.Errorf("ResolveDepartmentV1IDByName(%s): %w", name, err)
	}
	return id, nil
}

// ResolveDepartmentV1ByName looks up a DepartmentV1 by its name field and returns the decoded resource. Shares the same HTTP call as the ID-only variant; error semantics are identical.
func (c *Client) ResolveDepartmentV1ByName(ctx context.Context, name string) (*Department, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	listPath := prefix + "/departments"
	_, raw, err := c.transport.ResolveByNameFiltered(ctx, listPath, "", "name", "name", "id", name)
	if err != nil {
		return nil, fmt.Errorf("ResolveDepartmentV1ByName(%s): %w", name, err)
	}
	var out Department
	if err := json.Unmarshal(raw, &out); err != nil {
		return nil, fmt.Errorf("ResolveDepartmentV1ByName(%s): decoding matched element: %w", name, err)
	}
	return &out, nil
}

// ApplyDepartmentV1 creates or updates a DepartmentV1 by name. If a resource with the specified name exists, it is updated; if not found, a new resource is created. Returns the resource ID, whether it was created (true) or updated (false), and any error. An *AmbiguousMatchError is returned if multiple resources match the name.
func (c *Client) ApplyDepartmentV1(ctx context.Context, request *Department) (string, bool, error) {
	name := request.Name
	if name == "" {
		return "", false, fmt.Errorf("ApplyDepartmentV1: Name must not be empty")
	}
	id, err := c.ResolveDepartmentV1IDByName(ctx, name)
	if err != nil {
		if apiErr := client.AsAPIError(err); apiErr != nil && apiErr.HasStatus(404) {
			resp, createErr := c.CreateDepartmentV1(ctx, request)
			if createErr != nil {
				return "", false, fmt.Errorf("ApplyDepartmentV1: create: %w", createErr)
			}
			return resp.ID, true, nil
		}
		return "", false, fmt.Errorf("ApplyDepartmentV1: resolve: %w", err)
	}
	_, err = c.UpdateDepartmentV1(ctx, id, request)
	if err != nil {
		return "", false, fmt.Errorf("ApplyDepartmentV1: update(%s): %w", id, err)
	}
	return id, false, nil
}
