// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package pro

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"github.com/jamf/jamfplatform-go-sdk/internal/client"
)

// GetDeviceCommunicationSettingsV1 retrieves all settings for device communication.
//
// Required privileges: mdm-profile-renewal-settings:read. Legacy Jamf Pro privilege name(s): Read Automatically Renew MDM Profile Settings.
func (c *Client) GetDeviceCommunicationSettingsV1(ctx context.Context) (*DeviceCommunicationSettings, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result DeviceCommunicationSettings
	endpoint := prefix + "/device-communication-settings"
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetDeviceCommunicationSettingsV1: %w", err)
	}
	return &result, nil
}

// UpdateDeviceCommunicationSettingsV1 update device communication settings.
//
// Required privileges: mdm-profile-renewal-settings:update. Legacy Jamf Pro privilege name(s): Update Automatically Renew MDM Profile Settings.
func (c *Client) UpdateDeviceCommunicationSettingsV1(ctx context.Context, request *DeviceCommunicationSettings) (*DeviceCommunicationSettings, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result DeviceCommunicationSettings
	endpoint := prefix + "/device-communication-settings"
	if err := c.transport.DoWithContentType(ctx, http.MethodPut, endpoint, request, "application/json", http.StatusOK, &result); err != nil {
		return nil, fmt.Errorf("UpdateDeviceCommunicationSettingsV1: %w", err)
	}
	return &result, nil
}

// ListDeviceCommunicationSettingsHistoryV1 get Device Communication settings history.
//
// Required privileges: mdm-profile-renewal-settings:read. Legacy Jamf Pro privilege name(s): Read Automatically Renew MDM Profile Settings.
//
// Parameters:
//   - sort: Sorting criteria in the format: property:asc/desc. Default sort is date:desc. Multiple sort criteria
//     are supported and must be separated with a comma. Example: sort=date:desc,name:asc.
//   - filter: Query in the RSQL format, allowing to filter history notes collection. Default filter is empty query
//   - returning all results for the requested page. Fields allowed in the query: username, date, note,
//     details. This param can be combined with paging and sorting. Example: filter=username!=admin and
//     details==*disabled* and date<2019-12-15.
func (c *Client) ListDeviceCommunicationSettingsHistoryV1(ctx context.Context, sort []string, filter string) ([]ObjectHistory, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	return client.ListAllPages(ctx, 2000, func(ctx context.Context, page, pageSize int) ([]ObjectHistory, bool, error) {
		params := url.Values{}
		params.Set("page", strconv.Itoa(page))
		params.Set("page-size", strconv.Itoa(pageSize))
		if len(sort) > 0 {
			params.Set("sort", strings.Join(sort, ","))
		}
		if filter != "" {
			params.Set("filter", filter)
		}

		endpoint := prefix + "/device-communication-settings/history"
		if encoded := params.Encode(); encoded != "" {
			endpoint += "?" + encoded
		}
		var result struct {
			TotalCount int             `json:"totalCount"`
			Results    []ObjectHistory `json:"results"`
		}
		if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
			return nil, false, err
		}
		hasNext := (page+1)*pageSize < result.TotalCount
		return result.Results, hasNext, nil
	})
}

// CreateDeviceCommunicationSettingsHistoryNoteV1 add Device Communication Settings history notes.
//
// Required privileges: mdm-profile-renewal-settings:update. Legacy Jamf Pro privilege name(s): Update Automatically Renew MDM Profile Settings.
func (c *Client) CreateDeviceCommunicationSettingsHistoryNoteV1(ctx context.Context, request *ObjectHistoryNote) (*ObjectHistory, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result ObjectHistory
	endpoint := prefix + "/device-communication-settings/history"
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("CreateDeviceCommunicationSettingsHistoryNoteV1: %w", err)
	}
	return &result, nil
}
