// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package pro

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"github.com/jamf/jamfplatform-go-sdk/internal/client"
)

// ListAvailableOsUpdatesV1 retrieve available macOS and iOS Managed Software Updates.
//
// Required privileges: the spec declares none.
func (c *Client) ListAvailableOsUpdatesV1(ctx context.Context) (*AvailableOsUpdates, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result AvailableOsUpdates
	endpoint := prefix + "/managed-software-updates/available-updates"
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("ListAvailableOsUpdatesV1: %w", err)
	}
	return &result, nil
}

// ListManagedSoftwareUpdatePlansV1 retrieve Managed Software Update Plans.
//
// Required privileges: devices:read, managed-software-updates:read. Legacy Jamf Pro privilege name(s): Read Managed Software Updates, Read Computers, Read Mobile Devices.
// All of them are required, not alternatives.
// The scoped and legacy lists are independent sets, not pairs: do not match them by position.
//
// Parameters:
//   - sort: Sorting criteria in the format: property:asc/desc. Default sort is planUuid:asc. Multiple sort
//     criteria are supported and must be separated with a comma.
//   - filter: Query in the RSQL format, allowing to filter Managed Software Updates collection. Default filter is
//     empty query - returning all results for the requested page. Fields allowed in the query: planUuid,
//     device.deviceId, device.objectType, updateAction, versionType, specificVersion, maxDeferrals,
//     recipeId, forceInstallLocalDateTime, state.
func (c *Client) ListManagedSoftwareUpdatePlansV1(ctx context.Context, sort []string, filter string) ([]ManagedSoftwareUpdatePlan, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	return client.ListAllPages(ctx, 2000, func(ctx context.Context, page, pageSize int) ([]ManagedSoftwareUpdatePlan, bool, error) {
		params := url.Values{}
		params.Set("page", strconv.Itoa(page))
		params.Set("page-size", strconv.Itoa(pageSize))
		if len(sort) > 0 {
			params.Set("sort", strings.Join(sort, ","))
		}
		if filter != "" {
			params.Set("filter", filter)
		}

		endpoint := prefix + "/managed-software-updates/plans"
		if encoded := params.Encode(); encoded != "" {
			endpoint += "?" + encoded
		}
		var result struct {
			TotalCount int                         `json:"totalCount"`
			Results    []ManagedSoftwareUpdatePlan `json:"results"`
		}
		if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
			return nil, false, err
		}
		hasNext := (page+1)*pageSize < result.TotalCount
		return result.Results, hasNext, nil
	})
}

// CreateManagedSoftwareUpdatePlanV1 create a Managed Software Update Plan.
//
// This endpoint is rate-limited. The transport automatically retries a 429 with backoff (honoring a server-supplied Retry-After when present, clamped to a ceiling), giving up only after exhausting its retry budget — at which point the 429 surfaces as an APIResponseError so the caller can apply its own backoff policy.
//
// Required privileges: device-actions:execute, devices:read, managed-software-updates:create. Legacy Jamf Pro privilege name(s): Create Managed Software Updates, Read Computers, Read Mobile Devices, Send Computer Remote Command to Download and Install OS X Update, Send Mobile Device Remote Command to Download and Install iOS Update.
// All of them are required, not alternatives.
// The scoped and legacy lists are independent sets, not pairs: do not match them by position.
func (c *Client) CreateManagedSoftwareUpdatePlanV1(ctx context.Context, request *ManagedSoftwareUpdatePlanPost) (*ManagedSoftwareUpdatePlanPostResponse, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result ManagedSoftwareUpdatePlanPostResponse
	endpoint := prefix + "/managed-software-updates/plans"
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("CreateManagedSoftwareUpdatePlanV1: %w", err)
	}
	return &result, nil
}

// GetManagedSoftwareUpdateFeatureToggleV1 retrieve current value of the Feature Toggle.
//
// Required privileges: managed-software-updates:read. Legacy Jamf Pro privilege name(s): Read Managed Software Updates.
func (c *Client) GetManagedSoftwareUpdateFeatureToggleV1(ctx context.Context) (*ManagedSoftwareUpdatePlanToggle, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result ManagedSoftwareUpdatePlanToggle
	endpoint := prefix + "/managed-software-updates/plans/feature-toggle"
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetManagedSoftwareUpdateFeatureToggleV1: %w", err)
	}
	return &result, nil
}

// UpdateManagedSoftwareUpdateFeatureToggleV1 updates Feature Toggle Value.
//
// Required privileges: managed-software-updates:create, managed-software-updates:read, managed-software-updates:update. Legacy Jamf Pro privilege name(s): Read Managed Software Updates, Create Managed Software Updates, Update Managed Software Updates.
// All of them are required, not alternatives.
// The scoped and legacy lists are independent sets, not pairs: do not match them by position.
func (c *Client) UpdateManagedSoftwareUpdateFeatureToggleV1(ctx context.Context, request *ManagedSoftwareUpdatePlanToggle) (*ManagedSoftwareUpdatePlanToggle, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result ManagedSoftwareUpdatePlanToggle
	endpoint := prefix + "/managed-software-updates/plans/feature-toggle"
	if err := c.transport.DoWithContentType(ctx, http.MethodPut, endpoint, request, "application/json", http.StatusOK, &result); err != nil {
		return nil, fmt.Errorf("UpdateManagedSoftwareUpdateFeatureToggleV1: %w", err)
	}
	return &result, nil
}

// AbandonManagedSoftwareUpdateFeatureToggleV1 force stops any ongoing or stalled feature-toggle processes.
//
// Required privileges: managed-software-updates:create, managed-software-updates:read, managed-software-updates:update. Legacy Jamf Pro privilege name(s): Read Managed Software Updates, Create Managed Software Updates, Update Managed Software Updates.
// All of them are required, not alternatives.
// The scoped and legacy lists are independent sets, not pairs: do not match them by position.
func (c *Client) AbandonManagedSoftwareUpdateFeatureToggleV1(ctx context.Context) error {
	prefix := c.transport.APIPrefix("pro", "v1")
	endpoint := prefix + "/managed-software-updates/plans/feature-toggle/abandon"
	if err := c.transport.DoExpect(ctx, http.MethodPost, endpoint, nil, http.StatusNoContent, nil); err != nil {
		return fmt.Errorf("AbandonManagedSoftwareUpdateFeatureToggleV1: %w", err)
	}
	return nil
}

// GetManagedSoftwareUpdateFeatureToggleStatusV1 retrieves background status of the Feature Toggle.
//
// Required privileges: managed-software-updates:read. Legacy Jamf Pro privilege name(s): Read Managed Software Updates.
func (c *Client) GetManagedSoftwareUpdateFeatureToggleStatusV1(ctx context.Context) (*ManagedSoftwareUpdatePlanToggleStatusWrapper, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result ManagedSoftwareUpdatePlanToggleStatusWrapper
	endpoint := prefix + "/managed-software-updates/plans/feature-toggle/status"
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetManagedSoftwareUpdateFeatureToggleStatusV1: %w", err)
	}
	return &result, nil
}

// CreateManagedSoftwareUpdateGroupPlanV1 create Managed Software Update Plans for a Group.
//
// This endpoint is rate-limited. The transport automatically retries a 429 with backoff (honoring a server-supplied Retry-After when present, clamped to a ceiling), giving up only after exhausting its retry budget — at which point the 429 surfaces as an APIResponseError so the caller can apply its own backoff policy.
//
// Required privileges: device-actions:execute, device-groups:read, devices:read, managed-software-updates:create. Legacy Jamf Pro privilege name(s): Create Managed Software Updates, Read Computers, Read Mobile Devices, Read Smart Computer Groups, Read Static Computer Groups, Read Smart Mobile Device Groups, Read Static Mobile Device Groups, Send Computer Remote Command to Download and Install OS X Update, Send Mobile Device Remote Command to Download and Install iOS Update.
// All of them are required, not alternatives.
// The scoped and legacy lists are independent sets, not pairs: do not match them by position.
func (c *Client) CreateManagedSoftwareUpdateGroupPlanV1(ctx context.Context, request *ManagedSoftwareUpdatePlanGroupPost) (*ManagedSoftwareUpdatePlanPostResponse, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result ManagedSoftwareUpdatePlanPostResponse
	endpoint := prefix + "/managed-software-updates/plans/group"
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("CreateManagedSoftwareUpdateGroupPlanV1: %w", err)
	}
	return &result, nil
}

// GetManagedSoftwareUpdateGroupPlansV1 retrieve Managed Software Update Plans for a Group.
//
// Required privileges: device-groups:read, devices:read, managed-software-updates:read. Legacy Jamf Pro privilege name(s): Read Managed Software Updates, Read Computers, Read Smart Computer Groups, Read Static Computer Groups, Read Mobile Devices, Read Smart Mobile Device Groups, Read Static Mobile Device Groups.
// All of them are required, not alternatives.
// The scoped and legacy lists are independent sets, not pairs: do not match them by position.
//
// Parameters:
//   - id: Managed Software Update Group Id.
//   - groupType: Managed Software Update Group Type, Available options are "COMPUTER_GROUP" or "MOBILE_DEVICE_GROUP".
//     Allowed values: "COMPUTER_GROUP", "MOBILE_DEVICE_GROUP".
func (c *Client) GetManagedSoftwareUpdateGroupPlansV1(ctx context.Context, id string, groupType string) (*ManagedSoftwareUpdatePlans, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result ManagedSoftwareUpdatePlans
	endpoint := fmt.Sprintf("%s/managed-software-updates/plans/group/%s", prefix, url.PathEscape(id))
	params := url.Values{}
	params.Set("group-type", groupType)
	if encoded := params.Encode(); encoded != "" {
		endpoint += "?" + encoded
	}
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetManagedSoftwareUpdateGroupPlansV1(%s): %w", id, err)
	}
	return &result, nil
}

// GetManagedSoftwareUpdatePlanV1 retrieve a Managed Software Update Plan.
//
// Required privileges: devices:read, managed-software-updates:read. Legacy Jamf Pro privilege name(s): Read Managed Software Updates, Read Computers, Read Mobile Devices.
// All of them are required, not alternatives.
// The scoped and legacy lists are independent sets, not pairs: do not match them by position.
//
// Parameters:
//   - id: Managed Software Update Plan Uuid.
func (c *Client) GetManagedSoftwareUpdatePlanV1(ctx context.Context, id string) (*ManagedSoftwareUpdatePlan, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result ManagedSoftwareUpdatePlan
	endpoint := fmt.Sprintf("%s/managed-software-updates/plans/%s", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetManagedSoftwareUpdatePlanV1(%s): %w", id, err)
	}
	return &result, nil
}

// GetManagedSoftwareUpdatePlanDeclarationsV1 retrieve all Declarations associated with a Managed Software Update Plan.
//
// Required privileges: devices:read, managed-software-updates:read. Legacy Jamf Pro privilege name(s): Read Managed Software Updates, Read Computers, Read Mobile Devices.
// All of them are required, not alternatives.
// The scoped and legacy lists are independent sets, not pairs: do not match them by position.
//
// Parameters:
//   - id: Managed Software Update Plan Uuid.
func (c *Client) GetManagedSoftwareUpdatePlanDeclarationsV1(ctx context.Context, id string) (*DssDeclarations, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result DssDeclarations
	endpoint := fmt.Sprintf("%s/managed-software-updates/plans/%s/declarations", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetManagedSoftwareUpdatePlanDeclarationsV1(%s): %w", id, err)
	}
	return &result, nil
}

// GetManagedSoftwareUpdatePlanEventsV1 retrieve a Managed Software Update Plan Event Store.
//
// Required privileges: devices:read, managed-software-updates:read. Legacy Jamf Pro privilege name(s): Read Managed Software Updates, Read Computers, Read Mobile Devices.
// All of them are required, not alternatives.
// The scoped and legacy lists are independent sets, not pairs: do not match them by position.
//
// Parameters:
//   - id: Managed Software Update Plan Uuid.
func (c *Client) GetManagedSoftwareUpdatePlanEventsV1(ctx context.Context, id string) (*ManagedSoftwareUpdatePlanEventStore, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result ManagedSoftwareUpdatePlanEventStore
	endpoint := fmt.Sprintf("%s/managed-software-updates/plans/%s/events", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetManagedSoftwareUpdatePlanEventsV1(%s): %w", id, err)
	}
	return &result, nil
}

// ListManagedSoftwareUpdateStatusesV1 retrieve Managed Software Update Statuses.
//
// Required privileges: devices:read. Legacy Jamf Pro privilege name(s): Read Computers, Read Mobile Devices.
// The scoped and legacy lists are independent sets, not pairs: do not match them by position.
//
// Parameters:
//   - filter: Query in the RSQL format, allowing to filter Managed Software Updates collection. Default filter is
//     empty query - returning all results for the requested page. Fields allowed in the query:
//     osUpdatesStatusId, device.deviceId, device.objectType, downloaded, downloadPercentComplete,
//     productKey, status, deferralsRemaining, maxDeferrals, nextScheduledInstall, created and updated.
func (c *Client) ListManagedSoftwareUpdateStatusesV1(ctx context.Context, filter string) (*ManagedSoftwareUpdateStatuses, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result ManagedSoftwareUpdateStatuses
	endpoint := prefix + "/managed-software-updates/update-statuses"
	params := url.Values{}
	if filter != "" {
		params.Set("filter", filter)
	}
	if encoded := params.Encode(); encoded != "" {
		endpoint += "?" + encoded
	}
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("ListManagedSoftwareUpdateStatusesV1: %w", err)
	}
	return &result, nil
}

// GetManagedSoftwareUpdateStatusesForComputerGroupV1 retrieve Managed Software Update Statuses for Computer Groups.
//
// Required privileges: device-groups:read, devices:read. Legacy Jamf Pro privilege name(s): Read Computers, Read Smart Computer Groups, Read Static Computer Groups.
// All of them are required, not alternatives.
// The scoped and legacy lists are independent sets, not pairs: do not match them by position.
//
// Parameters:
//   - id: Computer Group identifier.
func (c *Client) GetManagedSoftwareUpdateStatusesForComputerGroupV1(ctx context.Context, id string) (*ManagedSoftwareUpdateStatuses, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result ManagedSoftwareUpdateStatuses
	endpoint := fmt.Sprintf("%s/managed-software-updates/update-statuses/computer-groups/%s", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetManagedSoftwareUpdateStatusesForComputerGroupV1(%s): %w", id, err)
	}
	return &result, nil
}

// GetManagedSoftwareUpdateStatusesForComputerV1 retrieve Managed Software Update Statuses for Computers.
//
// Required privileges: managed-software-updates:read. Legacy Jamf Pro privilege name(s): Read Computers.
//
// Parameters:
//   - id: Computer identifier.
func (c *Client) GetManagedSoftwareUpdateStatusesForComputerV1(ctx context.Context, id string) (*ManagedSoftwareUpdateStatuses, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result ManagedSoftwareUpdateStatuses
	endpoint := fmt.Sprintf("%s/managed-software-updates/update-statuses/computers/%s", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetManagedSoftwareUpdateStatusesForComputerV1(%s): %w", id, err)
	}
	return &result, nil
}

// GetManagedSoftwareUpdateStatusesForMobileDeviceGroupV1 retrieve Managed Software Update Statuses for Mobile Device Groups.
//
// Required privileges: device-groups:read, devices:read. Legacy Jamf Pro privilege name(s): Read Mobile Devices, Read Smart Mobile Device Groups, Read Static Mobile Device Groups.
// All of them are required, not alternatives.
// The scoped and legacy lists are independent sets, not pairs: do not match them by position.
//
// Parameters:
//   - id: Mobile Device Group identifier.
func (c *Client) GetManagedSoftwareUpdateStatusesForMobileDeviceGroupV1(ctx context.Context, id string) (*ManagedSoftwareUpdateStatuses, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result ManagedSoftwareUpdateStatuses
	endpoint := fmt.Sprintf("%s/managed-software-updates/update-statuses/mobile-device-groups/%s", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetManagedSoftwareUpdateStatusesForMobileDeviceGroupV1(%s): %w", id, err)
	}
	return &result, nil
}

// GetManagedSoftwareUpdateStatusesForMobileDeviceV1 retrieve Managed Software Update Statuses for Mobile Devices.
//
// Required privileges: managed-software-updates:read. Legacy Jamf Pro privilege name(s): Read Mobile Devices.
//
// Parameters:
//   - id: Mobile Device identifier.
func (c *Client) GetManagedSoftwareUpdateStatusesForMobileDeviceV1(ctx context.Context, id string) (*ManagedSoftwareUpdateStatuses, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result ManagedSoftwareUpdateStatuses
	endpoint := fmt.Sprintf("%s/managed-software-updates/update-statuses/mobile-devices/%s", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetManagedSoftwareUpdateStatusesForMobileDeviceV1(%s): %w", id, err)
	}
	return &result, nil
}
