// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package pro

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"github.com/jamf/jamfplatform-go-sdk/internal/client"
)

// ListMobileDeviceExtensionAttributesV1 retrieve Mobile Device Extension Attributes.
//
// Required privileges: extension-attributes:read. Legacy Jamf Pro privilege name(s): Read Mobile Device Extension Attributes.
//
// Parameters:
//   - sort: Sorts results by one or more criteria, following the format property:asc/desc. Default sort is
//     name:asc. If using multiple criteria, separate with commas. Allows sort for id and name.
//   - filter: Filters results. Use RSQL format for query. Allows for many fields, including ID, name, etc. Can be
//     combined with paging and sorting. Fields allowed in the query: id, name Default filter is an empty
//     query and returns all results from the requested page.
func (c *Client) ListMobileDeviceExtensionAttributesV1(ctx context.Context, sort []string, filter string) ([]MobileDeviceExtensionAttributes, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	return client.ListAllPages(ctx, 2000, func(ctx context.Context, page, pageSize int) ([]MobileDeviceExtensionAttributes, bool, error) {
		params := url.Values{}
		params.Set("page", strconv.Itoa(page))
		params.Set("page-size", strconv.Itoa(pageSize))
		if len(sort) > 0 {
			params.Set("sort", strings.Join(sort, ","))
		}
		if filter != "" {
			params.Set("filter", filter)
		}

		endpoint := prefix + "/mobile-device-extension-attributes"
		if encoded := params.Encode(); encoded != "" {
			endpoint += "?" + encoded
		}
		var result struct {
			TotalCount int                               `json:"totalCount"`
			Results    []MobileDeviceExtensionAttributes `json:"results"`
		}
		if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
			return nil, false, err
		}
		hasNext := (page+1)*pageSize < result.TotalCount
		return result.Results, hasNext, nil
	})
}

// CreateMobileDeviceExtensionAttributeV1 create Mobile Device Extension Attribute.
//
// Required privileges: extension-attributes:create. Legacy Jamf Pro privilege name(s): Create Mobile Device Extension Attributes.
func (c *Client) CreateMobileDeviceExtensionAttributeV1(ctx context.Context, request *MobileDeviceExtensionAttributes) (*HrefResponse, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result HrefResponse
	endpoint := prefix + "/mobile-device-extension-attributes"
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("CreateMobileDeviceExtensionAttributeV1: %w", err)
	}
	return &result, nil
}

// GetMobileDeviceExtensionAttributeV1 get specified Mobile Device Extension Attribute object.
//
// Required privileges: extension-attributes:read. Legacy Jamf Pro privilege name(s): Read Mobile Device Extension Attributes.
//
// Parameters:
//   - id: Unique ID of Mobile Device Extension Attribute.
func (c *Client) GetMobileDeviceExtensionAttributeV1(ctx context.Context, id string) (*MobileDeviceExtensionAttributes, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result MobileDeviceExtensionAttributes
	endpoint := fmt.Sprintf("%s/mobile-device-extension-attributes/%s", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetMobileDeviceExtensionAttributeV1(%s): %w", id, err)
	}
	return &result, nil
}

// UpdateMobileDeviceExtensionAttributeV1 update specified Mobile Device Extension Attribute object.
//
// Required privileges: extension-attributes:update. Legacy Jamf Pro privilege name(s): Update Mobile Device Extension Attributes.
//
// Parameters:
//   - id: Unique ID of Mobile Device Extension Attribute.
func (c *Client) UpdateMobileDeviceExtensionAttributeV1(ctx context.Context, id string, request *MobileDeviceExtensionAttributes) (*MobileDeviceExtensionAttributes, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result MobileDeviceExtensionAttributes
	endpoint := fmt.Sprintf("%s/mobile-device-extension-attributes/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoWithContentType(ctx, http.MethodPut, endpoint, request, "application/json", http.StatusAccepted, &result); err != nil {
		return nil, fmt.Errorf("UpdateMobileDeviceExtensionAttributeV1(%s): %w", id, err)
	}
	return &result, nil
}

// DeleteMobileDeviceExtensionAttributeV1 delete a Mobile Device Extension Attribute by ID.
//
// Required privileges: extension-attributes:delete. Legacy Jamf Pro privilege name(s): Delete Mobile Device Extension Attributes.
//
// Parameters:
//   - id: Unique ID of Mobile Device Extension Attribute.
func (c *Client) DeleteMobileDeviceExtensionAttributeV1(ctx context.Context, id string) error {
	prefix := c.transport.APIPrefix("pro", "v1")
	endpoint := fmt.Sprintf("%s/mobile-device-extension-attributes/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusNoContent, nil); err != nil {
		return fmt.Errorf("DeleteMobileDeviceExtensionAttributeV1(%s): %w", id, err)
	}
	return nil
}

// GetMobileDeviceExtensionAttributeDataDependencyV1 get smart group dependent object for a specified mobile device extension attribute.
//
// Required privileges: extension-attributes:read. Legacy Jamf Pro privilege name(s): Read Mobile Device Extension Attributes.
//
// Parameters:
//   - id: Unique ID of mobile device extension attribute.
func (c *Client) GetMobileDeviceExtensionAttributeDataDependencyV1(ctx context.Context, id string) (*DependencyObjectResults, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result DependencyObjectResults
	endpoint := fmt.Sprintf("%s/mobile-device-extension-attributes/%s/data-dependency", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetMobileDeviceExtensionAttributeDataDependencyV1(%s): %w", id, err)
	}
	return &result, nil
}

// ListMobileDeviceExtensionAttributeHistoryV1 get specified Mobile Device Extension Attribute History object.
//
// Required privileges: extension-attributes:read. Legacy Jamf Pro privilege name(s): Read Mobile Device Extension Attributes.
//
// Parameters:
//   - id: Instance ID of Mobile Device Extension Attribute.
//   - sort: Sorts results by one or more criteria, following the format property:asc/desc. Default sort is
//     ID:asc. If using multiple criteria, separate with commas.
//   - filter: Filters results. Use RSQL format for query. Allows for many fields, including ID, name, etc. Can be
//     combined with paging and sorting. Default filter is an empty query and returns all results from the
//     requested page.
func (c *Client) ListMobileDeviceExtensionAttributeHistoryV1(ctx context.Context, id string, sort []string, filter string) ([]ObjectHistory, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	return client.ListAllPages(ctx, 2000, func(ctx context.Context, page, pageSize int) ([]ObjectHistory, bool, error) {
		params := url.Values{}
		params.Set("page", strconv.Itoa(page))
		params.Set("page-size", strconv.Itoa(pageSize))
		if len(sort) > 0 {
			params.Set("sort", strings.Join(sort, ","))
		}
		if filter != "" {
			params.Set("filter", filter)
		}

		endpoint := fmt.Sprintf("%s/mobile-device-extension-attributes/%s/history", prefix, url.PathEscape(id))
		if encoded := params.Encode(); encoded != "" {
			endpoint += "?" + encoded
		}
		var result struct {
			TotalCount int             `json:"totalCount"`
			Results    []ObjectHistory `json:"results"`
		}
		if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
			return nil, false, err
		}
		hasNext := (page+1)*pageSize < result.TotalCount
		return result.Results, hasNext, nil
	})
}

// CreateMobileDeviceExtensionAttributeHistoryNoteV1 add specified Mobile Device Extension Attribute history object notes.
//
// Required privileges: extension-attributes:update. Legacy Jamf Pro privilege name(s): Update Mobile Device Extension Attributes.
//
// Parameters:
//   - id: Instance ID of Mobile Device Extension Attribute.
func (c *Client) CreateMobileDeviceExtensionAttributeHistoryNoteV1(ctx context.Context, id string, request *ObjectHistoryNote) (*ObjectHistory, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result ObjectHistory
	endpoint := fmt.Sprintf("%s/mobile-device-extension-attributes/%s/history", prefix, url.PathEscape(id))
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("CreateMobileDeviceExtensionAttributeHistoryNoteV1(%s): %w", id, err)
	}
	return &result, nil
}

// ListDeviceExtensionAttributesPreview get Mobile Device Extension Attribute values placed in select paramter.
//
// Required privileges: extension-attributes:read. Legacy Jamf Pro privilege name(s): Read Mobile Device Extension Attributes.
//
// Parameters:
//   - selectAttr: Acceptable values currently include: * name.
func (c *Client) ListDeviceExtensionAttributesPreview(ctx context.Context, selectAttr string) (*MobileDeviceExtensionAttributeResults, error) {
	prefix := c.transport.APIPrefix("pro", "")
	var result MobileDeviceExtensionAttributeResults
	endpoint := prefix + "/devices/extensionAttributes"
	params := url.Values{}
	if selectAttr != "" {
		params.Set("select", selectAttr)
	}
	if encoded := params.Encode(); encoded != "" {
		endpoint += "?" + encoded
	}
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("ListDeviceExtensionAttributesPreview: %w", err)
	}
	return &result, nil
}

// ResolveMobileDeviceExtensionAttributeV1IDByName looks up a MobileDeviceExtensionAttributeV1 by its name field and returns the ID. Returns *APIResponseError with HasStatus(404) when no match exists, or *AmbiguousMatchError when multiple resources share the name.
func (c *Client) ResolveMobileDeviceExtensionAttributeV1IDByName(ctx context.Context, name string) (string, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	listPath := prefix + "/mobile-device-extension-attributes"
	id, _, err := c.transport.ResolveByNameFiltered(ctx, listPath, "", "name", "name", "id", name)
	if err != nil {
		return "", fmt.Errorf("ResolveMobileDeviceExtensionAttributeV1IDByName(%s): %w", name, err)
	}
	return id, nil
}

// ResolveMobileDeviceExtensionAttributeV1ByName looks up a MobileDeviceExtensionAttributeV1 by its name field and returns the decoded resource. Shares the same HTTP call as the ID-only variant; error semantics are identical.
func (c *Client) ResolveMobileDeviceExtensionAttributeV1ByName(ctx context.Context, name string) (*MobileDeviceExtensionAttributes, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	listPath := prefix + "/mobile-device-extension-attributes"
	_, raw, err := c.transport.ResolveByNameFiltered(ctx, listPath, "", "name", "name", "id", name)
	if err != nil {
		return nil, fmt.Errorf("ResolveMobileDeviceExtensionAttributeV1ByName(%s): %w", name, err)
	}
	var out MobileDeviceExtensionAttributes
	if err := json.Unmarshal(raw, &out); err != nil {
		return nil, fmt.Errorf("ResolveMobileDeviceExtensionAttributeV1ByName(%s): decoding matched element: %w", name, err)
	}
	return &out, nil
}

// ApplyMobileDeviceExtensionAttributeV1 creates or updates a MobileDeviceExtensionAttributeV1 by name. If a resource with the specified name exists, it is updated; if not found, a new resource is created. Returns the resource ID, whether it was created (true) or updated (false), and any error. An *AmbiguousMatchError is returned if multiple resources match the name.
func (c *Client) ApplyMobileDeviceExtensionAttributeV1(ctx context.Context, request *MobileDeviceExtensionAttributes) (string, bool, error) {
	name := request.Name
	if name == "" {
		return "", false, fmt.Errorf("ApplyMobileDeviceExtensionAttributeV1: Name must not be empty")
	}
	id, err := c.ResolveMobileDeviceExtensionAttributeV1IDByName(ctx, name)
	if err != nil {
		if apiErr := client.AsAPIError(err); apiErr != nil && apiErr.HasStatus(404) {
			resp, createErr := c.CreateMobileDeviceExtensionAttributeV1(ctx, request)
			if createErr != nil {
				return "", false, fmt.Errorf("ApplyMobileDeviceExtensionAttributeV1: create: %w", createErr)
			}
			return resp.ID, true, nil
		}
		return "", false, fmt.Errorf("ApplyMobileDeviceExtensionAttributeV1: resolve: %w", err)
	}
	_, err = c.UpdateMobileDeviceExtensionAttributeV1(ctx, id, request)
	if err != nil {
		return "", false, fmt.Errorf("ApplyMobileDeviceExtensionAttributeV1: update(%s): %w", id, err)
	}
	return id, false, nil
}
