// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package pro

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"github.com/Jamf-Concepts/jamfplatform-go-sdk/internal/client"
)

// ListMobileDevicesDetailV2 return paginated Mobile Device Inventory records.
//
// Required privileges: devices:read. Legacy Jamf Pro privilege name(s): Read Mobile Devices.
//
// Parameters:
//   - section: section of mobile device details, if not specified, General section data is returned. Multiple
//     section parameters are supported, e.g. section=GENERAL&section=HARDWARE.
//     Allowed values: see the MobileDeviceSection constants.
//   - sort: Sorting criteria in the format: property:asc/desc. Default sort is displayName:asc. Multiple sort
//     criteria are supported and must be separated with a comma.
//     Fields allowed in the sort: `airPlayPassword`, `appAnalyticsEnabled`, `assetTag`,
//     `availableSpaceMb`, `batteryLevel`, `batteryHealth`, `bluetoothLowEnergyCapable`,
//     `bluetoothMacAddress`, `capacityMb`, `lostModeEnabledDate`, `declarativeDeviceManagementEnabled`,
//     `deviceId`, `deviceLocatorServiceEnabled`, `devicePhoneNumber`,
//     `diagnosticAndUsageReportingEnabled`, `displayName`, `doNotDisturbEnabled`,
//     `enrollmentSessionTokenValid`, `exchangeDeviceId`, `cloudBackupEnabled`, `osBuild`,
//     `osSupplementalBuildVersion`, `osVersion`, `osRapidSecurityResponse`, `ipAddress`,
//     `itunesStoreAccountActive`, `mobileDeviceId`, `managementId`, `languages`, `lastBackupDate`,
//     `lastContactDate`, `lastEnrolledDate`, `lastCloudBackupDate`, `lastInventoryUpdateDate`, `locales`,
//     `locationServicesForSelfServiceMobileEnabled`, `lostModeEnabled`, `managed`,
//     `mdmProfileExpirationDate`, `model`, `modelIdentifier`, `modelNumber`, `modemFirmwareVersion`,
//     `preferredVoiceNumber`, `quotaSize`, `residentUsers`, `serialNumber`, `sharedIpad`, `supervised`,
//     `tethered`, `timeZone`, `udid`, `usedSpacePercentage`, `wifiMacAddress`, `deviceOwnershipType`,
//     `building`, `department`, `emailAddress`, `fullName`, `userPhoneNumber`, `position`, `room`,
//     `username`, `appleCareId`, `leaseExpirationDate`,`lifeExpectancyYears`, `poDate`, `poNumber`,
//     `purchasePrice`, `purchasedOrLeased`, `purchasingAccount`, `purchasingContact`, `vendor`,
//     `warrantyExpirationDate`, `activationLockEnabled`, `blockEncryptionCapable`, `dataProtection`,
//     `fileEncryptionCapable`, `hardwareEncryptionSupported`, `jailbreakStatus`, `passcodeCompliant`,
//     `passcodeCompliantWithProfile`, `passcodeLockGracePeriodEnforcedSeconds`, `passcodePresent`,
//     `carrierSettingsVersion`, `cellularTechnology`, `currentCarrierNetwork`, `currentMobileCountryCode`,
//     `currentMobileNetworkCode`, `dataRoamingEnabled`, `eid`, `network`, `homeMobileCountryCode`,
//     `homeMobileNetworkCode`, `iccid`, `imei`, `imei2`, `meid`, `personalHotspotEnabled`,
//     `voiceRoamingEnabled`, `roaming`, `lastLoggedInUsernameSelfService`,
//     `lastLoggedInUsernameSelfServiceTimestamp`, `lastLoggedInUsernameMdm`,
//     `lastLoggedInUsernameMdmTimestamp`.
//     Example: `sort=displayName:desc,username:asc`.
//   - filter: Query in the RSQL format, allowing to filter mobile device collection. Default filter is empty query
//   - returning all results for the requested page.
//     Fields allowed in the query: `airPlayPassword`, `appAnalyticsEnabled`, `assetTag`,
//     `availableSpaceMb`, `batteryLevel`, `bluetoothLowEnergyCapable`, `bluetoothMacAddress`,
//     `capacityMb`, `declarativeDeviceManagementEnabled`, `deviceId`, `deviceLocatorServiceEnabled`,
//     `devicePhoneNumber`, `diagnosticAndUsageReportingEnabled`, `displayName`, `doNotDisturbEnabled`,
//     `exchangeDeviceId`, `cloudBackupEnabled`, `osBuild`, `osSupplementalBuildVersion`, `osVersion`,
//     `osRapidSecurityResponse`, `ipAddress`, `itunesStoreAccountActive`, `mobileDeviceId`,
//     `managementId`, `languages`, `lastContactDate`, `lastInventoryUpdateDate`, `locales`,
//     `locationServicesForSelfServiceMobileEnabled`, `lostModeEnabled`, `managed`, `model`,
//     `modelIdentifier`, `modelNumber`, `modemFirmwareVersion`, `preferredVoiceNumber`, `quotaSize`,
//     `residentUsers`, `serialNumber`, `sharedIpad`, `supervised`, `tethered`, `timeZone`, `udid`,
//     `usedSpacePercentage`, `wifiMacAddress`, `building`, `department`, `emailAddress`, `fullName`,
//     `userPhoneNumber`, `position`, `room`, `username`, `appleCareId`, `lifeExpectancyYears`, `poNumber`,
//     `purchasePrice`, `purchasedOrLeased`, `purchasingAccount`, `purchasingContact`, `vendor`,
//     `activationLockEnabled`, `awaitingConfiguration`, `blockEncryptionCapable`, `dataProtection`,
//     `fileEncryptionCapable`, `lockdownModeEnabled`, `passcodeCompliant`, `passcodeCompliantWithProfile`,
//     `passcodeLockGracePeriodEnforcedSeconds`, `passcodePresent`, `returnToServiceEnabled`,
//     `carrierSettingsVersion`, `currentCarrierNetwork`, `currentMobileCountryCode`,
//     `currentMobileNetworkCode`, `dataRoamingEnabled`, `eid`, `network`, `homeMobileCountryCode`,
//     `homeMobileNetworkCode`, `iccid`, `imei`, `imei2`, `meid`, `personalHotspotEnabled`, `roaming`,
//     `lastLoggedInUsernameSelfService`, `lastLoggedInUsernameSelfServiceTimestamp`,
//     `lastLoggedInUsernameMdm`, `lastLoggedInUsernameMdmTimestamp`, `groupId`, `groupName`.
//     This param can be combined with paging and sorting. Example: `filter=displayName=="iPad"`.
func (c *Client) ListMobileDevicesDetailV2(ctx context.Context, section []string, sort []string, filter string) ([]MobileDeviceResponse, error) {
	prefix := c.transport.APIPrefix("pro", "v2")
	return client.ListAllPages(ctx, 2000, func(ctx context.Context, page, pageSize int) ([]MobileDeviceResponse, bool, error) {
		params := url.Values{}
		params.Set("page", strconv.Itoa(page))
		params.Set("page-size", strconv.Itoa(pageSize))
		if len(section) > 0 {
			params.Set("section", strings.Join(section, ","))
		}
		if len(sort) > 0 {
			params.Set("sort", strings.Join(sort, ","))
		}
		if filter != "" {
			params.Set("filter", filter)
		}

		endpoint := prefix + "/mobile-devices/detail"
		if encoded := params.Encode(); encoded != "" {
			endpoint += "?" + encoded
		}
		var result struct {
			TotalCount int                    `json:"totalCount"`
			Results    []MobileDeviceResponse `json:"results"`
		}
		if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
			return nil, false, err
		}
		hasNext := (page+1)*pageSize < result.TotalCount
		return result.Results, hasNext, nil
	})
}

// ListMobileDevicesV2 get Mobile Device objects.
//
// Required privileges: devices:read. Legacy Jamf Pro privilege name(s): Read Mobile Devices.
//
// Parameters:
//   - sort: Sorting criteria in the format: property:asc/desc. Default sort is id:asc. Multiple sort criteria
//     are supported and must be separated with a comma. Example: sort=date:desc,name:asc.
func (c *Client) ListMobileDevicesV2(ctx context.Context, sort []string) ([]MobileDeviceV2, error) {
	prefix := c.transport.APIPrefix("pro", "v2")
	return client.ListAllPages(ctx, 2000, func(ctx context.Context, page, pageSize int) ([]MobileDeviceV2, bool, error) {
		params := url.Values{}
		params.Set("page", strconv.Itoa(page))
		params.Set("page-size", strconv.Itoa(pageSize))
		if len(sort) > 0 {
			params.Set("sort", strings.Join(sort, ","))
		}

		endpoint := prefix + "/mobile-devices"
		if encoded := params.Encode(); encoded != "" {
			endpoint += "?" + encoded
		}
		var result struct {
			TotalCount int              `json:"totalCount"`
			Results    []MobileDeviceV2 `json:"results"`
		}
		if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
			return nil, false, err
		}
		hasNext := (page+1)*pageSize < result.TotalCount
		return result.Results, hasNext, nil
	})
}

// GetMobileDeviceV2 get Mobile Device.
//
// Required privileges: devices:read. Legacy Jamf Pro privilege name(s): Read Mobile Devices.
//
// Parameters:
//   - id: instance id of mobile device record.
func (c *Client) GetMobileDeviceV2(ctx context.Context, id string) (*MobileDeviceV2, error) {
	prefix := c.transport.APIPrefix("pro", "v2")
	var result MobileDeviceV2
	endpoint := fmt.Sprintf("%s/mobile-devices/%s", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetMobileDeviceV2(%s): %w", id, err)
	}
	return &result, nil
}

// PatchMobileDeviceV2 update fields on a mobile device that are allowed to be modified by users.
//
// Required privileges: devices:update. Legacy Jamf Pro privilege name(s): Update Mobile Devices.
//
// Parameters:
//   - id: instance id of mobile device record.
func (c *Client) PatchMobileDeviceV2(ctx context.Context, id string, request *UpdateMobileDeviceV2) (*MobileDeviceDetailsV2, error) {
	prefix := c.transport.APIPrefix("pro", "v2")
	var result MobileDeviceDetailsV2
	endpoint := fmt.Sprintf("%s/mobile-devices/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoWithContentType(ctx, http.MethodPatch, endpoint, request, "application/json", http.StatusOK, &result); err != nil {
		return nil, fmt.Errorf("PatchMobileDeviceV2(%s): %w", id, err)
	}
	return &result, nil
}

// GetMobileDeviceDetailV2 get Mobile Device.
//
// Required privileges: devices:read. Legacy Jamf Pro privilege name(s): Read Mobile Devices.
//
// Parameters:
//   - id: instance id of mobile device record.
func (c *Client) GetMobileDeviceDetailV2(ctx context.Context, id string) (*MobileDeviceDetailsGetV2, error) {
	prefix := c.transport.APIPrefix("pro", "v2")
	var result MobileDeviceDetailsGetV2
	endpoint := fmt.Sprintf("%s/mobile-devices/%s/detail", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetMobileDeviceDetailV2(%s): %w", id, err)
	}
	return &result, nil
}

// EraseMobileDeviceV2 erase a Mobile Device.
//
// Required privileges: destructive-device-actions:execute. Legacy Jamf Pro privilege name(s): Send Mobile Device Remote Wipe Command.
//
// Parameters:
//   - id: Id of the Mobile Device to erase.
func (c *Client) EraseMobileDeviceV2(ctx context.Context, id string, request *EraseDeviceMobileDeviceRequest) (*EraseDeviceMobileDeviceResponse, error) {
	prefix := c.transport.APIPrefix("pro", "v2")
	var result EraseDeviceMobileDeviceResponse
	endpoint := fmt.Sprintf("%s/mobile-devices/%s/erase", prefix, url.PathEscape(id))
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusOK, &result); err != nil {
		return nil, fmt.Errorf("EraseMobileDeviceV2(%s): %w", id, err)
	}
	return &result, nil
}

// ListMobileDevicePairedDevicesV2 return paginated Mobile Device Inventory records of all paired devices for the device.
//
// Required privileges: devices:read. Legacy Jamf Pro privilege name(s): Read Mobile Devices.
//
// Parameters:
//   - id: instance id of mobile device record.
//   - section: section of mobile device details, if not specified, Paired Devices section data is returned.
//     Multiple section parameters are supported, e.g. section=GENERAL&section=HARDWARE.
//     Allowed values: see the MobileDeviceSection constants.
//   - sort: Sorting criteria in the format: property:asc/desc. Default sort is displayName:asc. Multiple sort
//     criteria are supported and must be separated with a comma.
//     Fields allowed in the sort: `airPlayPassword`, `appAnalyticsEnabled`, `assetTag`,
//     `availableSpaceMb`, `batteryLevel`, `bluetoothLowEnergyCapable`, `bluetoothMacAddress`,
//     `capacityMb`, `lostModeEnabledDate`, `declarativeDeviceManagementEnabled`, `deviceId`,
//     `deviceLocatorServiceEnabled`, `devicePhoneNumber`, `diagnosticAndUsageReportingEnabled`,
//     `displayName`, `doNotDisturbEnabled`, `enrollmentSessionTokenValid`, `osBuild`,
//     `osSupplementalBuildVersion`, `osVersion`, `osRapidSecurityResponse`, `ipAddress`,
//     `itunesStoreAccountActive`, `mobileDeviceId`, `languages`, `lastContactDate`, `lastEnrolledDate`,
//     `lastCloudBackupDate`, `lastInventoryUpdateDate`, `locales`, `lostModeEnabled`, `managed`,
//     `mdmProfileExpirationDate`, `model`, `modelIdentifier`, `modelNumber`, `modemFirmwareVersion`,
//     `preferredVoiceNumber`, `serialNumber`, `supervised`, `timeZone`, `udid`, `usedSpacePercentage`,
//     `wifiMacAddress`, `deviceOwnershipType`, `building`, `department`, `emailAddress`, `fullName`,
//     `userPhoneNumber`, `position`, `room`, `username`, `appleCareId`,
//     `leaseExpirationDate`,`lifeExpectancyYears`, `poDate`, `poNumber`, `purchasePrice`,
//     `purchasedOrLeased`, `purchasingAccount`, `purchasingContact`, `vendor`, `warrantyExpirationDate`,
//     `activationLockEnabled`, `blockEncryptionCapable`, `dataProtection`, `fileEncryptionCapable`,
//     `hardwareEncryptionSupported`, `jailbreakStatus`, `passcodeCompliant`,
//     `passcodeCompliantWithProfile`, `passcodeLockGracePeriodEnforcedSeconds`, `passcodePresent`,
//     `carrierSettingsVersion`, `cellularTechnology`, `currentCarrierNetwork`, `currentMobileCountryCode`,
//     `currentMobileNetworkCode`, `dataRoamingEnabled`, `eid`, `network`, `homeMobileCountryCode`,
//     `homeMobileNetworkCode`, `iccid`, `imei`, `imei2`, `meid`, `personalHotspotEnabled`,
//     `voiceRoamingEnabled`, `roaming`, `lastLoggedInUsernameSelfService`,
//     `lastLoggedInUsernameSelfServiceTimestamp`, `lastLoggedInUsernameMdm`,
//     `lastLoggedInUsernameMdmTimestamp`.
//     Example: `sort=displayName:desc,username:asc`.
//   - filter: Query in the RSQL format, allowing to filter mobile device collection. Default filter is empty query
//   - returning all results for the requested page.
//     Fields allowed in the query: `airPlayPassword`, `appAnalyticsEnabled`, `assetTag`,
//     `availableSpaceMb`, `batteryLevel`, `bluetoothLowEnergyCapable`, `bluetoothMacAddress`,
//     `capacityMb`, `declarativeDeviceManagementEnabled`, `deviceId`, `deviceLocatorServiceEnabled`,
//     `devicePhoneNumber`, `diagnosticAndUsageReportingEnabled`, `displayName`, `doNotDisturbEnabled`,
//     `osBuild`, `osSupplementalBuildVersion`, `osVersion`, `osRapidSecurityResponse`, `ipAddress`,
//     `itunesStoreAccountActive`, `mobileDeviceId`, `languages`, `lastContactDate`,
//     `lastInventoryUpdateDate`, `locales`, `lostModeEnabled`, `managed`, `model`, `modelIdentifier`,
//     `modelNumber`, `modemFirmwareVersion`, `preferredVoiceNumber`, `serialNumber`, `supervised`,
//     `timeZone`, `udid`, `usedSpacePercentage`, `wifiMacAddress`, `building`, `department`,
//     `emailAddress`, `fullName`, `userPhoneNumber`, `position`, `room`, `username`, `appleCareId`,
//     `lifeExpectancyYears`, `poNumber`, `purchasePrice`, `purchasedOrLeased`, `purchasingAccount`,
//     `purchasingContact`, `vendor`, `activationLockEnabled`, `blockEncryptionCapable`, `dataProtection`,
//     `fileEncryptionCapable`, `passcodeCompliant`, `passcodeCompliantWithProfile`,
//     `passcodeLockGracePeriodEnforcedSeconds`, `passcodePresent`, `carrierSettingsVersion`,
//     `currentCarrierNetwork`, `currentMobileCountryCode`, `currentMobileNetworkCode`,
//     `dataRoamingEnabled`, `eid`, `network`, `homeMobileCountryCode`, `homeMobileNetworkCode`, `iccid`,
//     `imei`, `imei2`, `meid`, `personalHotspotEnabled`, `roaming`, `lastLoggedInUsernameSelfService`,
//     `lastLoggedInUsernameSelfServiceTimestamp`, `lastLoggedInUsernameMdm`,
//     `lastLoggedInUsernameMdmTimestamp`, `groupId`, `groupName`.
//     This param can be combined with paging and sorting. Example: `filter=displayName=="iPad"`.
func (c *Client) ListMobileDevicePairedDevicesV2(ctx context.Context, id string, section []string, sort []string, filter string) ([]MobileDeviceResponse, error) {
	prefix := c.transport.APIPrefix("pro", "v2")
	return client.ListAllPages(ctx, 2000, func(ctx context.Context, page, pageSize int) ([]MobileDeviceResponse, bool, error) {
		params := url.Values{}
		params.Set("page", strconv.Itoa(page))
		params.Set("page-size", strconv.Itoa(pageSize))
		if len(section) > 0 {
			params.Set("section", strings.Join(section, ","))
		}
		if len(sort) > 0 {
			params.Set("sort", strings.Join(sort, ","))
		}
		if filter != "" {
			params.Set("filter", filter)
		}

		endpoint := fmt.Sprintf("%s/mobile-devices/%s/paired-devices", prefix, url.PathEscape(id))
		if encoded := params.Encode(); encoded != "" {
			endpoint += "?" + encoded
		}
		var result struct {
			TotalCount int                    `json:"totalCount"`
			Results    []MobileDeviceResponse `json:"results"`
		}
		if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
			return nil, false, err
		}
		hasNext := (page+1)*pageSize < result.TotalCount
		return result.Results, hasNext, nil
	})
}

// UnmanageMobileDeviceV2 unmanage a Mobile Device.
//
// Required privileges: destructive-device-actions:execute. Legacy Jamf Pro privilege name(s): Unmanage Mobile Devices.
//
// Parameters:
//   - id: Id of the mobile device to remove the MDM profile from.
func (c *Client) UnmanageMobileDeviceV2(ctx context.Context, id string) (*UnmanageMobileDeviceResponse, error) {
	prefix := c.transport.APIPrefix("pro", "v2")
	var result UnmanageMobileDeviceResponse
	endpoint := fmt.Sprintf("%s/mobile-devices/%s/unmanage", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodPost, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("UnmanageMobileDeviceV2(%s): %w", id, err)
	}
	return &result, nil
}

// ResolveMobileDeviceDetailV2IDByName looks up a MobileDeviceDetailV2 by its displayName field and returns the ID. Returns *APIResponseError with HasStatus(404) when no match exists, or *AmbiguousMatchError when multiple resources share the name.
func (c *Client) ResolveMobileDeviceDetailV2IDByName(ctx context.Context, name string) (string, error) {
	prefix := c.transport.APIPrefix("pro", "v2")
	listPath := prefix + "/mobile-devices/detail?section=GENERAL"
	id, _, err := c.transport.ResolveByNameFiltered(ctx, listPath, "", "displayName", "general.displayName", "mobileDeviceId", name)
	if err != nil {
		return "", fmt.Errorf("ResolveMobileDeviceDetailV2IDByName(%s): %w", name, err)
	}
	return id, nil
}

// ResolveMobileDeviceDetailV2ByName looks up a MobileDeviceDetailV2 by its displayName field and returns the decoded resource. Shares the same HTTP call as the ID-only variant; error semantics are identical.
func (c *Client) ResolveMobileDeviceDetailV2ByName(ctx context.Context, name string) (*MobileDeviceResponse, error) {
	prefix := c.transport.APIPrefix("pro", "v2")
	listPath := prefix + "/mobile-devices/detail?section=GENERAL"
	_, raw, err := c.transport.ResolveByNameFiltered(ctx, listPath, "", "displayName", "general.displayName", "mobileDeviceId", name)
	if err != nil {
		return nil, fmt.Errorf("ResolveMobileDeviceDetailV2ByName(%s): %w", name, err)
	}
	var out MobileDeviceResponse
	if err := json.Unmarshal(raw, &out); err != nil {
		return nil, fmt.Errorf("ResolveMobileDeviceDetailV2ByName(%s): decoding matched element: %w", name, err)
	}
	return &out, nil
}

// ResolveMobileDeviceDetailV2IDBySerialNumber looks up a MobileDeviceDetailV2 by its serialNumber field and returns the ID. Returns *APIResponseError with HasStatus(404) when no match exists, or *AmbiguousMatchError when multiple resources share the name.
func (c *Client) ResolveMobileDeviceDetailV2IDBySerialNumber(ctx context.Context, name string) (string, error) {
	prefix := c.transport.APIPrefix("pro", "v2")
	listPath := prefix + "/mobile-devices/detail?section=HARDWARE"
	id, _, err := c.transport.ResolveByNameFiltered(ctx, listPath, "", "serialNumber", "hardware.serialNumber", "mobileDeviceId", name)
	if err != nil {
		return "", fmt.Errorf("ResolveMobileDeviceDetailV2IDBySerialNumber(%s): %w", name, err)
	}
	return id, nil
}

// ResolveMobileDeviceDetailV2BySerialNumber looks up a MobileDeviceDetailV2 by its serialNumber field and returns the decoded resource. Shares the same HTTP call as the ID-only variant; error semantics are identical.
func (c *Client) ResolveMobileDeviceDetailV2BySerialNumber(ctx context.Context, name string) (*MobileDeviceResponse, error) {
	prefix := c.transport.APIPrefix("pro", "v2")
	listPath := prefix + "/mobile-devices/detail?section=HARDWARE"
	_, raw, err := c.transport.ResolveByNameFiltered(ctx, listPath, "", "serialNumber", "hardware.serialNumber", "mobileDeviceId", name)
	if err != nil {
		return nil, fmt.Errorf("ResolveMobileDeviceDetailV2BySerialNumber(%s): %w", name, err)
	}
	var out MobileDeviceResponse
	if err := json.Unmarshal(raw, &out); err != nil {
		return nil, fmt.Errorf("ResolveMobileDeviceDetailV2BySerialNumber(%s): decoding matched element: %w", name, err)
	}
	return &out, nil
}

// ResolveMobileDeviceDetailV2IDByUDID looks up a MobileDeviceDetailV2 by its udid field and returns the ID. Returns *APIResponseError with HasStatus(404) when no match exists, or *AmbiguousMatchError when multiple resources share the name.
func (c *Client) ResolveMobileDeviceDetailV2IDByUDID(ctx context.Context, name string) (string, error) {
	prefix := c.transport.APIPrefix("pro", "v2")
	listPath := prefix + "/mobile-devices/detail?section=GENERAL"
	id, _, err := c.transport.ResolveByNameFiltered(ctx, listPath, "", "udid", "general.udid", "mobileDeviceId", name)
	if err != nil {
		return "", fmt.Errorf("ResolveMobileDeviceDetailV2IDByUDID(%s): %w", name, err)
	}
	return id, nil
}

// ResolveMobileDeviceDetailV2ByUDID looks up a MobileDeviceDetailV2 by its udid field and returns the decoded resource. Shares the same HTTP call as the ID-only variant; error semantics are identical.
func (c *Client) ResolveMobileDeviceDetailV2ByUDID(ctx context.Context, name string) (*MobileDeviceResponse, error) {
	prefix := c.transport.APIPrefix("pro", "v2")
	listPath := prefix + "/mobile-devices/detail?section=GENERAL"
	_, raw, err := c.transport.ResolveByNameFiltered(ctx, listPath, "", "udid", "general.udid", "mobileDeviceId", name)
	if err != nil {
		return nil, fmt.Errorf("ResolveMobileDeviceDetailV2ByUDID(%s): %w", name, err)
	}
	var out MobileDeviceResponse
	if err := json.Unmarshal(raw, &out); err != nil {
		return nil, fmt.Errorf("ResolveMobileDeviceDetailV2ByUDID(%s): decoding matched element: %w", name, err)
	}
	return &out, nil
}
