// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package pro

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"github.com/jamf/jamfplatform-go-sdk/internal/client"
)

// ListPackagesV1 retrieve Packages.
//
// Required privileges: packages:read. Legacy Jamf Pro privilege name(s): Read Packages.
//
// Parameters:
//   - sort: Sorts results by one or more criteria, following the format property:asc/desc. Default sort is
//     ID:asc. If using multiple criteria, separate with commas.
//   - filter: Filters results. Use RSQL format for query. Allows for many fields, including ID, name, etc. Can be
//     combined with paging and sorting. Fields allowed in the query: id, fileName, packageName,
//     categoryId, info, notes, manifestFileName, cloudTransferStatus. Default filter is an empty query and
//     returns all results from the requested page.
func (c *Client) ListPackagesV1(ctx context.Context, sort []string, filter string) ([]Package, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	return client.ListAllPages(ctx, 2000, func(ctx context.Context, page, pageSize int) ([]Package, bool, error) {
		params := url.Values{}
		params.Set("page", strconv.Itoa(page))
		params.Set("page-size", strconv.Itoa(pageSize))
		if len(sort) > 0 {
			params.Set("sort", strings.Join(sort, ","))
		}
		if filter != "" {
			params.Set("filter", filter)
		}

		endpoint := prefix + "/packages"
		if encoded := params.Encode(); encoded != "" {
			endpoint += "?" + encoded
		}
		var result struct {
			TotalCount int       `json:"totalCount"`
			Results    []Package `json:"results"`
		}
		if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
			return nil, false, err
		}
		hasNext := (page+1)*pageSize < result.TotalCount
		return result.Results, hasNext, nil
	})
}

// CreatePackageV1 create package.
//
// Required privileges: packages:create. Legacy Jamf Pro privilege name(s): Create Packages.
func (c *Client) CreatePackageV1(ctx context.Context, request *Package) (*HrefResponse, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result HrefResponse
	endpoint := prefix + "/packages"
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("CreatePackageV1: %w", err)
	}
	return &result, nil
}

// GetPackageV1 get specified Package object.
//
// Required privileges: packages:read. Legacy Jamf Pro privilege name(s): Read Packages.
//
// Parameters:
//   - id: instance id of package.
func (c *Client) GetPackageV1(ctx context.Context, id string) (*Package, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result Package
	endpoint := fmt.Sprintf("%s/packages/%s", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetPackageV1(%s): %w", id, err)
	}
	return &result, nil
}

// UpdatePackageV1 update specified package object.
//
// Required privileges: packages:update. Legacy Jamf Pro privilege name(s): Update Packages.
//
// Parameters:
//   - id: Instance ID of package.
func (c *Client) UpdatePackageV1(ctx context.Context, id string, request *Package) (*Package, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result Package
	endpoint := fmt.Sprintf("%s/packages/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoWithContentType(ctx, http.MethodPut, endpoint, request, "application/json", http.StatusOK, &result); err != nil {
		return nil, fmt.Errorf("UpdatePackageV1(%s): %w", id, err)
	}
	return &result, nil
}

// DeletePackageV1 remove specified package.
//
// Required privileges: packages:delete. Legacy Jamf Pro privilege name(s): Delete Packages.
//
// Parameters:
//   - id: Instance ID of package.
func (c *Client) DeletePackageV1(ctx context.Context, id string) error {
	prefix := c.transport.APIPrefix("pro", "v1")
	endpoint := fmt.Sprintf("%s/packages/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusNoContent, nil); err != nil {
		return fmt.Errorf("DeletePackageV1(%s): %w", id, err)
	}
	return nil
}

// UploadPackageV1 upload package.
//
// Required privileges: packages:read, packages:update. Legacy Jamf Pro privilege name(s): Update Packages, Read Packages.
// All of them are required, not alternatives.
// The scoped and legacy lists are independent sets, not pairs: do not match them by position.
//
// Parameters:
//   - id: instance id of package.
//
// For file parts, pass an *os.File or *bytes.Reader (anything that
// implements io.Seeker) so the SDK can precompute an exact
// Content-Length and retry once on a 429/Retry-After. A plain
// io.Reader is accepted too but the upload falls back to chunked
// transfer encoding and is not retried on 429.
func (c *Client) UploadPackageV1(ctx context.Context, id string, fileFilename string, file io.Reader) (*HrefResponse, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result HrefResponse
	endpoint := fmt.Sprintf("%s/packages/%s/upload", prefix, url.PathEscape(id))
	parts := []client.MultipartField{
		{Name: "file", Filename: fileFilename, Content: file},
	}
	if err := c.transport.DoMultipart(ctx, http.MethodPost, endpoint, parts, http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("UploadPackageV1(%s): %w", id, err)
	}
	return &result, nil
}

// DeleteMultiplePackagesV1 delete multiple packages at once.
//
// Required privileges: packages:delete. Legacy Jamf Pro privilege name(s): Delete Packages.
func (c *Client) DeleteMultiplePackagesV1(ctx context.Context, request *Ids) error {
	prefix := c.transport.APIPrefix("pro", "v1")
	endpoint := prefix + "/packages/delete-multiple"
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusNoContent, nil); err != nil {
		return fmt.Errorf("DeleteMultiplePackagesV1: %w", err)
	}
	return nil
}

// ExportPackagesV1 export Packages collection.
//
// Required privileges: packages:read. Legacy Jamf Pro privilege name(s): Read Packages.
//
// Parameters:
//   - exportFields: Export fields parameter, used to change default order or ignore some of the response properties.
//     Default is empty array, which means that all fields of the response entity will be serialized.
//     Example: export-fields=id,username.
//   - exportLabels: Export labels parameter, used to customize fieldnames/columns in the exported file. Default is empty
//     array, which means that response properties names will be used. Number of the provided labels must
//     match the number of export-fields Example: export-labels=identifier,name with matching:
//     export-fields=id,username.
//   - sort: Sorts results by one or more criteria, following the format property:asc/desc. Default sort is
//     ID:asc. If using multiple criteria, separate with commas.
//   - filter: Filters results. Use RSQL format for query. Allows for many fields, including ID, name, etc. Can be
//     combined with paging and sorting. Default filter is an empty query and returns all results from the
//     requested page.
func (c *Client) ExportPackagesV1(ctx context.Context, request *ExportParameters, exportFields []string, exportLabels []string, sort []string, filter string) ([]byte, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result []byte
	endpoint := prefix + "/packages/export"
	params := url.Values{}
	if len(exportFields) > 0 {
		params.Set("export-fields", strings.Join(exportFields, ","))
	}
	if len(exportLabels) > 0 {
		params.Set("export-labels", strings.Join(exportLabels, ","))
	}
	if len(sort) > 0 {
		params.Set("sort", strings.Join(sort, ","))
	}
	if filter != "" {
		params.Set("filter", filter)
	}
	if encoded := params.Encode(); encoded != "" {
		endpoint += "?" + encoded
	}
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusOK, &result); err != nil {
		return nil, fmt.Errorf("ExportPackagesV1: %w", err)
	}
	return result, nil
}

// ListPackageHistoryV1 get specified Package History object.
//
// Required privileges: packages:read. Legacy Jamf Pro privilege name(s): Read Packages.
//
// Parameters:
//   - id: Instance ID of package history.
//   - sort: Sorts results by one or more criteria, following the format property:asc/desc. Default sort is
//     ID:asc. If using multiple criteria, separate with commas.
//   - filter: Filters results. Use RSQL format for query. Allows for many fields, including ID, name, etc. Can be
//     combined with paging and sorting. Default filter is an empty query and returns all results from the
//     requested page.
func (c *Client) ListPackageHistoryV1(ctx context.Context, id string, sort []string, filter string) ([]ObjectHistory, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	return client.ListAllPages(ctx, 2000, func(ctx context.Context, page, pageSize int) ([]ObjectHistory, bool, error) {
		params := url.Values{}
		params.Set("page", strconv.Itoa(page))
		params.Set("page-size", strconv.Itoa(pageSize))
		if len(sort) > 0 {
			params.Set("sort", strings.Join(sort, ","))
		}
		if filter != "" {
			params.Set("filter", filter)
		}

		endpoint := fmt.Sprintf("%s/packages/%s/history", prefix, url.PathEscape(id))
		if encoded := params.Encode(); encoded != "" {
			endpoint += "?" + encoded
		}
		var result struct {
			TotalCount int             `json:"totalCount"`
			Results    []ObjectHistory `json:"results"`
		}
		if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
			return nil, false, err
		}
		hasNext := (page+1)*pageSize < result.TotalCount
		return result.Results, hasNext, nil
	})
}

// CreatePackageHistoryNoteV1 add specified Package history object notes.
//
// Required privileges: packages:update. Legacy Jamf Pro privilege name(s): Update Packages.
//
// Parameters:
//   - id: Instance ID of package history.
func (c *Client) CreatePackageHistoryNoteV1(ctx context.Context, id string, request *ObjectHistoryNote) (*ObjectHistory, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result ObjectHistory
	endpoint := fmt.Sprintf("%s/packages/%s/history", prefix, url.PathEscape(id))
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("CreatePackageHistoryNoteV1(%s): %w", id, err)
	}
	return &result, nil
}

// ExportPackageHistoryV1 export history object collection in specified format for specified Packages.
//
// Required privileges: packages:read. Legacy Jamf Pro privilege name(s): Read Packages.
//
// Parameters:
//   - id: Instance ID of package history note.
//   - exportFields: Export fields parameter, used to change default order or ignore some of the response properties.
//     Default is empty array, which means that all fields of the response entity will be serialized.
//     Example: export-fields=id,username.
//   - exportLabels: Export labels parameter, used to customize fieldnames/columns in the exported file. Default is empty
//     array, which means that response properties names will be used. Number of the provided labels must
//     match the number of export-fields Example: export-labels=identifier,name with matching:
//     export-fields=id,username.
//   - sort: Sorts results by one or more criteria, following the format property:asc/desc. Default sort is
//     ID:asc. If using multiple criteria, separate with commas.
//   - filter: Filters results. Use RSQL format for query. Allows for many fields, including ID, name, etc. Can be
//     combined with paging and sorting. Default filter is an empty query and returns all results from the
//     requested page.
func (c *Client) ExportPackageHistoryV1(ctx context.Context, id string, request *ExportParameters, exportFields []string, exportLabels []string, sort []string, filter string) ([]byte, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result []byte
	endpoint := fmt.Sprintf("%s/packages/%s/history/export", prefix, url.PathEscape(id))
	params := url.Values{}
	if len(exportFields) > 0 {
		params.Set("export-fields", strings.Join(exportFields, ","))
	}
	if len(exportLabels) > 0 {
		params.Set("export-labels", strings.Join(exportLabels, ","))
	}
	if len(sort) > 0 {
		params.Set("sort", strings.Join(sort, ","))
	}
	if filter != "" {
		params.Set("filter", filter)
	}
	if encoded := params.Encode(); encoded != "" {
		endpoint += "?" + encoded
	}
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusOK, &result); err != nil {
		return nil, fmt.Errorf("ExportPackageHistoryV1(%s): %w", id, err)
	}
	return result, nil
}

// UploadPackageManifestV1 add a manifest to a package.
//
// Required privileges: packages:read, packages:update. Legacy Jamf Pro privilege name(s): Update Packages, Read Packages.
// All of them are required, not alternatives.
// The scoped and legacy lists are independent sets, not pairs: do not match them by position.
//
// Parameters:
//   - id: Id of the package the manifest should be assigned to.
//
// For file parts, pass an *os.File or *bytes.Reader (anything that
// implements io.Seeker) so the SDK can precompute an exact
// Content-Length and retry once on a 429/Retry-After. A plain
// io.Reader is accepted too but the upload falls back to chunked
// transfer encoding and is not retried on 429.
func (c *Client) UploadPackageManifestV1(ctx context.Context, id string, fileFilename string, file io.Reader) (*Package, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result Package
	endpoint := fmt.Sprintf("%s/packages/%s/manifest", prefix, url.PathEscape(id))
	parts := []client.MultipartField{
		{Name: "file", Filename: fileFilename, Content: file},
	}
	if err := c.transport.DoMultipart(ctx, http.MethodPost, endpoint, parts, http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("UploadPackageManifestV1(%s): %w", id, err)
	}
	return &result, nil
}

// DeletePackageManifestV1 delete the manifest for a specified package.
//
// Required privileges: packages:read, packages:update. Legacy Jamf Pro privilege name(s): Update Packages, Read Packages.
// All of them are required, not alternatives.
// The scoped and legacy lists are independent sets, not pairs: do not match them by position.
//
// Parameters:
//   - id: Id of the package to delete manifest from.
func (c *Client) DeletePackageManifestV1(ctx context.Context, id string) error {
	prefix := c.transport.APIPrefix("pro", "v1")
	endpoint := fmt.Sprintf("%s/packages/%s/manifest", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusNoContent, nil); err != nil {
		return fmt.Errorf("DeletePackageManifestV1(%s): %w", id, err)
	}
	return nil
}

// ResolvePackageV1IDByName looks up a PackageV1 by its packageName field and returns the ID. Returns *APIResponseError with HasStatus(404) when no match exists, or *AmbiguousMatchError when multiple resources share the name.
func (c *Client) ResolvePackageV1IDByName(ctx context.Context, name string) (string, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	listPath := prefix + "/packages"
	id, _, err := c.transport.ResolveByNameFiltered(ctx, listPath, "", "packageName", "packageName", "id", name)
	if err != nil {
		return "", fmt.Errorf("ResolvePackageV1IDByName(%s): %w", name, err)
	}
	return id, nil
}

// ResolvePackageV1ByName looks up a PackageV1 by its packageName field and returns the decoded resource. Shares the same HTTP call as the ID-only variant; error semantics are identical.
func (c *Client) ResolvePackageV1ByName(ctx context.Context, name string) (*Package, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	listPath := prefix + "/packages"
	_, raw, err := c.transport.ResolveByNameFiltered(ctx, listPath, "", "packageName", "packageName", "id", name)
	if err != nil {
		return nil, fmt.Errorf("ResolvePackageV1ByName(%s): %w", name, err)
	}
	var out Package
	if err := json.Unmarshal(raw, &out); err != nil {
		return nil, fmt.Errorf("ResolvePackageV1ByName(%s): decoding matched element: %w", name, err)
	}
	return &out, nil
}

// ApplyPackageV1 creates or updates a PackageV1 by name. If a resource with the specified name exists, it is updated; if not found, a new resource is created. Returns the resource ID, whether it was created (true) or updated (false), and any error. An *AmbiguousMatchError is returned if multiple resources match the name.
func (c *Client) ApplyPackageV1(ctx context.Context, request *Package) (string, bool, error) {
	name := request.PackageName
	if name == "" {
		return "", false, fmt.Errorf("ApplyPackageV1: PackageName must not be empty")
	}
	id, err := c.ResolvePackageV1IDByName(ctx, name)
	if err != nil {
		if apiErr := client.AsAPIError(err); apiErr != nil && apiErr.HasStatus(404) {
			resp, createErr := c.CreatePackageV1(ctx, request)
			if createErr != nil {
				return "", false, fmt.Errorf("ApplyPackageV1: create: %w", createErr)
			}
			return resp.ID, true, nil
		}
		return "", false, fmt.Errorf("ApplyPackageV1: resolve: %w", err)
	}
	_, err = c.UpdatePackageV1(ctx, id, request)
	if err != nil {
		return "", false, fmt.Errorf("ApplyPackageV1: update(%s): %w", id, err)
	}
	return id, false, nil
}
