// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package pro

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"github.com/jamf/jamfplatform-go-sdk/internal/client"
)

// ListPatchSoftwareTitleConfigurationsV3 retrieve Patch Software Title Configurations.
//
// Required privileges: patch-management-software-titles:read. Legacy Jamf Pro privilege name(s): Read Patch Management Software Titles.
func (c *Client) ListPatchSoftwareTitleConfigurationsV3(ctx context.Context) ([]PatchSoftwareTitleConfiguration, error) {
	prefix := c.transport.APIPrefix("pro", "v3")
	var result []PatchSoftwareTitleConfiguration
	endpoint := prefix + "/patch-software-title-configurations"
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("ListPatchSoftwareTitleConfigurationsV3: %w", err)
	}
	return result, nil
}

// CreatePatchSoftwareTitleConfigurationV3 create Patch Software Title Configurations.
//
// Required privileges: patch-management-software-titles:create. Legacy Jamf Pro privilege name(s): Create Patch Management Software Titles.
func (c *Client) CreatePatchSoftwareTitleConfigurationV3(ctx context.Context, request *PatchSoftwareTitleConfigurationBase) (*HrefResponse, error) {
	prefix := c.transport.APIPrefix("pro", "v3")
	var result HrefResponse
	endpoint := prefix + "/patch-software-title-configurations"
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("CreatePatchSoftwareTitleConfigurationV3: %w", err)
	}
	return &result, nil
}

// GetPatchSoftwareTitleConfigurationV3 retrieve Patch Software Title Configurations with the supplied id.
//
// Required privileges: patch-management-software-titles:read. Legacy Jamf Pro privilege name(s): Read Patch Management Software Titles.
//
// Parameters:
//   - id: Patch Software Title Configurations identifier.
func (c *Client) GetPatchSoftwareTitleConfigurationV3(ctx context.Context, id string) (*PatchSoftwareTitleConfiguration, error) {
	prefix := c.transport.APIPrefix("pro", "v3")
	var result PatchSoftwareTitleConfiguration
	endpoint := fmt.Sprintf("%s/patch-software-title-configurations/%s", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetPatchSoftwareTitleConfigurationV3(%s): %w", id, err)
	}
	return &result, nil
}

// DeletePatchSoftwareTitleConfigurationV3 delete Patch Software Title Configurations with the supplied id.
//
// Required privileges: patch-management-software-titles:delete. Legacy Jamf Pro privilege name(s): Delete Patch Management Software Titles.
//
// Parameters:
//   - id: Patch Software Title Configurations identifier.
func (c *Client) DeletePatchSoftwareTitleConfigurationV3(ctx context.Context, id string) error {
	prefix := c.transport.APIPrefix("pro", "v3")
	endpoint := fmt.Sprintf("%s/patch-software-title-configurations/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusNoContent, nil); err != nil {
		return fmt.Errorf("DeletePatchSoftwareTitleConfigurationV3(%s): %w", id, err)
	}
	return nil
}

// UpdatePatchSoftwareTitleConfigurationV3 update Patch Software Title Configurations.
//
// Required privileges: patch-management-software-titles:update. Legacy Jamf Pro privilege name(s): Update Patch Management Software Titles.
//
// Parameters:
//   - id: Patch Software Title Configurations identifier.
func (c *Client) UpdatePatchSoftwareTitleConfigurationV3(ctx context.Context, id string, request *PatchSoftwareTitleConfigurationPatch) (*PatchSoftwareTitleConfiguration, error) {
	prefix := c.transport.APIPrefix("pro", "v3")
	var result PatchSoftwareTitleConfiguration
	endpoint := fmt.Sprintf("%s/patch-software-title-configurations/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoWithContentType(ctx, http.MethodPatch, endpoint, request, "application/merge-patch+json", http.StatusOK, &result); err != nil {
		return nil, fmt.Errorf("UpdatePatchSoftwareTitleConfigurationV3(%s): %w", id, err)
	}
	return &result, nil
}

// GetPatchSoftwareTitleDashboardStatusV3 return whether or not the requested software title configuration is on the dashboard.
//
// Required privileges: patch-management-software-titles:read. Legacy Jamf Pro privilege name(s): Read Patch Management Software Titles.
//
// Parameters:
//   - id: software title configuration id.
func (c *Client) GetPatchSoftwareTitleDashboardStatusV3(ctx context.Context, id string) (*SoftwareTitleConfigurationOnDashboard, error) {
	prefix := c.transport.APIPrefix("pro", "v3")
	var result SoftwareTitleConfigurationOnDashboard
	endpoint := fmt.Sprintf("%s/patch-software-title-configurations/%s/dashboard", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetPatchSoftwareTitleDashboardStatusV3(%s): %w", id, err)
	}
	return &result, nil
}

// AddPatchSoftwareTitleToDashboardV3 add a software title configuration to the dashboard.
//
// Required privileges: patch-management-software-titles:read. Legacy Jamf Pro privilege name(s): Read Patch Management Software Titles.
//
// Parameters:
//   - id: software title configuration id.
func (c *Client) AddPatchSoftwareTitleToDashboardV3(ctx context.Context, id string) error {
	prefix := c.transport.APIPrefix("pro", "v3")
	endpoint := fmt.Sprintf("%s/patch-software-title-configurations/%s/dashboard", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodPost, endpoint, nil, http.StatusNoContent, nil); err != nil {
		return fmt.Errorf("AddPatchSoftwareTitleToDashboardV3(%s): %w", id, err)
	}
	return nil
}

// RemovePatchSoftwareTitleFromDashboardV3 remove a software title configuration from the dashboard.
//
// Required privileges: patch-management-software-titles:read. Legacy Jamf Pro privilege name(s): Read Patch Management Software Titles.
//
// Parameters:
//   - id: software title configuration id.
func (c *Client) RemovePatchSoftwareTitleFromDashboardV3(ctx context.Context, id string) error {
	prefix := c.transport.APIPrefix("pro", "v3")
	endpoint := fmt.Sprintf("%s/patch-software-title-configurations/%s/dashboard", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusNoContent, nil); err != nil {
		return fmt.Errorf("RemovePatchSoftwareTitleFromDashboardV3(%s): %w", id, err)
	}
	return nil
}

// ListPatchSoftwareTitleDefinitionsV3 retrieve Patch Software Title Definitions with the supplied id.
//
// Required privileges: patch-management-software-titles:read. Legacy Jamf Pro privilege name(s): Read Patch Management Software Titles.
//
// Parameters:
//   - id: Patch Software Title identifier.
//   - sort: Sorting criteria in the format: property:asc/desc. Default sort is absoluteOrderId:asc. Multiple
//     sort criteria are supported and must be separated with a comma.
//   - filter: Query in the RSQL format, allowing to filter Patch Software Title Definition collection. Default
//     filter is empty query - returning all results for the requested page. Fields allowed in the query:
//     id, version, minimumOperatingSystem, releaseDate, reboot, standalone and absoluteOrderId. This param
//     can be combined with paging and sorting.
func (c *Client) ListPatchSoftwareTitleDefinitionsV3(ctx context.Context, id string, sort []string, filter string) ([]PatchSoftwareTitleDefinition, error) {
	prefix := c.transport.APIPrefix("pro", "v3")
	return client.ListAllPages(ctx, 2000, func(ctx context.Context, page, pageSize int) ([]PatchSoftwareTitleDefinition, bool, error) {
		params := url.Values{}
		params.Set("page", strconv.Itoa(page))
		params.Set("page-size", strconv.Itoa(pageSize))
		if len(sort) > 0 {
			params.Set("sort", strings.Join(sort, ","))
		}
		if filter != "" {
			params.Set("filter", filter)
		}

		endpoint := fmt.Sprintf("%s/patch-software-title-configurations/%s/definitions", prefix, url.PathEscape(id))
		if encoded := params.Encode(); encoded != "" {
			endpoint += "?" + encoded
		}
		var result struct {
			TotalCount int                            `json:"totalCount"`
			Results    []PatchSoftwareTitleDefinition `json:"results"`
		}
		if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
			return nil, false, err
		}
		hasNext := (page+1)*pageSize < result.TotalCount
		return result.Results, hasNext, nil
	})
}

// GetPatchSoftwareTitleDependenciesV3 retrieve list of Patch Software Title Configuration Dependencies.
//
// Required privileges: patch-management-software-titles:read. Legacy Jamf Pro privilege name(s): Read Patch Management Software Titles.
//
// Parameters:
//   - id: Patch Software Title Configuration Id.
func (c *Client) GetPatchSoftwareTitleDependenciesV3(ctx context.Context, id string) (*PatchSoftwareTitleConfigurationDependencies, error) {
	prefix := c.transport.APIPrefix("pro", "v3")
	var result PatchSoftwareTitleConfigurationDependencies
	endpoint := fmt.Sprintf("%s/patch-software-title-configurations/%s/dependencies", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetPatchSoftwareTitleDependenciesV3(%s): %w", id, err)
	}
	return &result, nil
}

// ExportPatchSoftwareTitleReportV3 export Patch Reporting Data.
//
// Required privileges: patch-management-software-titles:read. Legacy Jamf Pro privilege name(s): Read Patch Management Software Titles.
//
// Parameters:
//   - id: Patch Software Title Configurations identifier.
//   - filter: Query in the RSQL format, allowing to filter Patch Report collection on version equality only.
//     Default filter is empty query - returning all results for the requested page. Fields allowed in the
//     query: version. Comparators allowed in the query: ==, != This param can be combined with paging and
//     sorting.
//   - columnsToExport: List of column names to export.
//   - accept: File.
//     Allowed values, from the operation's declared response content types: text/csv, text/tab.
//     Required in practice: the server answers 400 when this is omitted, although the spec marks the
//     parameter optional. Passing the zero value omits it.
func (c *Client) ExportPatchSoftwareTitleReportV3(ctx context.Context, id string, filter string, columnsToExport []string, accept string) ([]byte, error) {
	prefix := c.transport.APIPrefix("pro", "v3")
	var result []byte
	endpoint := fmt.Sprintf("%s/patch-software-title-configurations/%s/export-report", prefix, url.PathEscape(id))
	params := url.Values{}
	if filter != "" {
		params.Set("filter", filter)
	}
	if len(columnsToExport) > 0 {
		params.Set("columns-to-export", strings.Join(columnsToExport, ","))
	}
	if encoded := params.Encode(); encoded != "" {
		endpoint += "?" + encoded
	}
	headers := http.Header{}
	if accept != "" {
		headers.Set("Accept", accept)
	}
	if err := c.transport.DoWithOptions(ctx, http.MethodGet, endpoint, nil, client.RequestOptions{Headers: headers}, &result); err != nil {
		return nil, fmt.Errorf("ExportPatchSoftwareTitleReportV3(%s): %w", id, err)
	}
	return result, nil
}

// ListPatchSoftwareTitleExtensionAttributesV3 retrieve Software Title Extension Attributes with the supplied id.
//
// Required privileges: patch-management-software-titles:read. Legacy Jamf Pro privilege name(s): Read Patch Management Software Titles.
//
// Parameters:
//   - id: Patch Software Title identifier.
func (c *Client) ListPatchSoftwareTitleExtensionAttributesV3(ctx context.Context, id string) ([]PatchSoftwareTitleExtensionAttributes, error) {
	prefix := c.transport.APIPrefix("pro", "v3")
	var result []PatchSoftwareTitleExtensionAttributes
	endpoint := fmt.Sprintf("%s/patch-software-title-configurations/%s/extension-attributes", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("ListPatchSoftwareTitleExtensionAttributesV3(%s): %w", id, err)
	}
	return result, nil
}

// ListPatchSoftwareTitleHistoryV3 get specified Patch Software Title Configuration history object.
//
// Required privileges: patch-management-software-titles:read. Legacy Jamf Pro privilege name(s): Read Patch Management Software Titles.
//
// Parameters:
//   - id: Patch Software Title Configuration Id.
//   - sort: Sorting criteria in the format: property:asc/desc. Default sort is date:desc. Multiple sort criteria
//     are supported and must be separated with a comma.
//   - filter: Query in the RSQL format, allowing to filter history notes collection. Default filter is empty query
//   - returning all results for the requested page. Fields allowed in the query: username, date, note,
//     details. This param can be combined with paging and sorting. Example: filter=username!=admin and
//     details==*disabled* and date<2019-12-15.
func (c *Client) ListPatchSoftwareTitleHistoryV3(ctx context.Context, id string, sort []string, filter string) ([]ObjectHistory, error) {
	prefix := c.transport.APIPrefix("pro", "v3")
	return client.ListAllPages(ctx, 2000, func(ctx context.Context, page, pageSize int) ([]ObjectHistory, bool, error) {
		params := url.Values{}
		params.Set("page", strconv.Itoa(page))
		params.Set("page-size", strconv.Itoa(pageSize))
		if len(sort) > 0 {
			params.Set("sort", strings.Join(sort, ","))
		}
		if filter != "" {
			params.Set("filter", filter)
		}

		endpoint := fmt.Sprintf("%s/patch-software-title-configurations/%s/history", prefix, url.PathEscape(id))
		if encoded := params.Encode(); encoded != "" {
			endpoint += "?" + encoded
		}
		var result struct {
			TotalCount int             `json:"totalCount"`
			Results    []ObjectHistory `json:"results"`
		}
		if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
			return nil, false, err
		}
		hasNext := (page+1)*pageSize < result.TotalCount
		return result.Results, hasNext, nil
	})
}

// CreatePatchSoftwareTitleHistoryNoteV3 add Patch Software Title Configuration history object notes.
//
// Required privileges: patch-management-software-titles:update. Legacy Jamf Pro privilege name(s): Update Patch Management Software Titles.
//
// Parameters:
//   - id: Patch Software Title Configuration Id.
func (c *Client) CreatePatchSoftwareTitleHistoryNoteV3(ctx context.Context, id string, request *ObjectHistoryNote) (*HrefResponse, error) {
	prefix := c.transport.APIPrefix("pro", "v3")
	var result HrefResponse
	endpoint := fmt.Sprintf("%s/patch-software-title-configurations/%s/history", prefix, url.PathEscape(id))
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("CreatePatchSoftwareTitleHistoryNoteV3(%s): %w", id, err)
	}
	return &result, nil
}

// ListPatchSoftwareTitlePatchReportV3 retrieve Patch Software Title Configuration Patch Report.
//
// Required privileges: patch-management-software-titles:read. Legacy Jamf Pro privilege name(s): Read Patch Management Software Titles.
//
// Parameters:
//   - id: Patch Software Title Configurations identifier.
//   - sort: Sorting criteria in the format: property:asc/desc. Default sort is computerName:asc. Multiple sort
//     criteria are supported and must be separated with a comma. Supported fields: computerName, deviceId,
//     username, operatingSystemVersion, lastCheckIn, buildingName, departmentName, siteName, version.
//   - filter: Query in the RSQL format, allowing to filter Patch Report collection on version equality only.
//     Default filter is empty query - returning all results for the requested page. Fields allowed in the
//     query: version. Comparators allowed in the query: ==, != This param can be combined with paging and
//     sorting.
func (c *Client) ListPatchSoftwareTitlePatchReportV3(ctx context.Context, id string, sort []string, filter string) ([]PatchReportV3, error) {
	prefix := c.transport.APIPrefix("pro", "v3")
	return client.ListAllPages(ctx, 2000, func(ctx context.Context, page, pageSize int) ([]PatchReportV3, bool, error) {
		params := url.Values{}
		params.Set("page", strconv.Itoa(page))
		params.Set("page-size", strconv.Itoa(pageSize))
		if len(sort) > 0 {
			params.Set("sort", strings.Join(sort, ","))
		}
		if filter != "" {
			params.Set("filter", filter)
		}

		endpoint := fmt.Sprintf("%s/patch-software-title-configurations/%s/patch-report", prefix, url.PathEscape(id))
		if encoded := params.Encode(); encoded != "" {
			endpoint += "?" + encoded
		}
		var result struct {
			TotalCount int             `json:"totalCount"`
			Results    []PatchReportV3 `json:"results"`
		}
		if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
			return nil, false, err
		}
		hasNext := (page+1)*pageSize < result.TotalCount
		return result.Results, hasNext, nil
	})
}

// GetPatchSoftwareTitlePatchSummaryV3 return Active Patch Summary.
//
// Required privileges: patch-management-software-titles:read. Legacy Jamf Pro privilege name(s): Read Patch Management Software Titles.
//
// Parameters:
//   - id: Patch id.
func (c *Client) GetPatchSoftwareTitlePatchSummaryV3(ctx context.Context, id string) (*PatchSummary, error) {
	prefix := c.transport.APIPrefix("pro", "v3")
	var result PatchSummary
	endpoint := fmt.Sprintf("%s/patch-software-title-configurations/%s/patch-summary", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetPatchSoftwareTitlePatchSummaryV3(%s): %w", id, err)
	}
	return &result, nil
}

// ListPatchSoftwareTitlePatchSummaryVersionsV3 returns patch versions.
//
// Required privileges: patch-management-software-titles:read. Legacy Jamf Pro privilege name(s): Read Patch Management Software Titles.
//
// Parameters:
//   - id: Patch id.
func (c *Client) ListPatchSoftwareTitlePatchSummaryVersionsV3(ctx context.Context, id string) ([]PatchSummaryVersion, error) {
	prefix := c.transport.APIPrefix("pro", "v3")
	var result []PatchSummaryVersion
	endpoint := fmt.Sprintf("%s/patch-software-title-configurations/%s/patch-summary/versions", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("ListPatchSoftwareTitlePatchSummaryVersionsV3(%s): %w", id, err)
	}
	return result, nil
}

// ResolvePatchSoftwareTitleConfigurationV3IDByName looks up a PatchSoftwareTitleConfigurationV3 by its displayName field and returns the ID. Returns *APIResponseError with HasStatus(404) when no match exists, or *AmbiguousMatchError when multiple resources share the name.
func (c *Client) ResolvePatchSoftwareTitleConfigurationV3IDByName(ctx context.Context, name string) (string, error) {
	prefix := c.transport.APIPrefix("pro", "v3")
	listPath := prefix + "/patch-software-title-configurations"
	id, _, err := c.transport.ResolveByNameClient(ctx, listPath, "", "", "displayName", "id", name)
	if err != nil {
		return "", fmt.Errorf("ResolvePatchSoftwareTitleConfigurationV3IDByName(%s): %w", name, err)
	}
	return id, nil
}

// ResolvePatchSoftwareTitleConfigurationV3ByName looks up a PatchSoftwareTitleConfigurationV3 by its displayName field and returns the decoded resource. Shares the same HTTP call as the ID-only variant; error semantics are identical.
func (c *Client) ResolvePatchSoftwareTitleConfigurationV3ByName(ctx context.Context, name string) (*PatchSoftwareTitleConfiguration, error) {
	prefix := c.transport.APIPrefix("pro", "v3")
	listPath := prefix + "/patch-software-title-configurations"
	_, raw, err := c.transport.ResolveByNameClient(ctx, listPath, "", "", "displayName", "id", name)
	if err != nil {
		return nil, fmt.Errorf("ResolvePatchSoftwareTitleConfigurationV3ByName(%s): %w", name, err)
	}
	var out PatchSoftwareTitleConfiguration
	if err := json.Unmarshal(raw, &out); err != nil {
		return nil, fmt.Errorf("ResolvePatchSoftwareTitleConfigurationV3ByName(%s): decoding matched element: %w", name, err)
	}
	return &out, nil
}

// ApplyPatchSoftwareTitleConfigurationV3 creates or updates a PatchSoftwareTitleConfigurationV3 by name. If a resource with the specified name exists, it is updated; if not found, a new resource is created. Returns the resource ID, whether it was created (true) or updated (false), and any error. An *AmbiguousMatchError is returned if multiple resources match the name.
func (c *Client) ApplyPatchSoftwareTitleConfigurationV3(ctx context.Context, request *PatchSoftwareTitleConfigurationBase) (string, bool, error) {
	name := request.DisplayName
	if name == "" {
		return "", false, fmt.Errorf("ApplyPatchSoftwareTitleConfigurationV3: DisplayName must not be empty")
	}
	id, err := c.ResolvePatchSoftwareTitleConfigurationV3IDByName(ctx, name)
	if err != nil {
		if apiErr := client.AsAPIError(err); apiErr != nil && apiErr.HasStatus(404) {
			resp, createErr := c.CreatePatchSoftwareTitleConfigurationV3(ctx, request)
			if createErr != nil {
				return "", false, fmt.Errorf("ApplyPatchSoftwareTitleConfigurationV3: create: %w", createErr)
			}
			return resp.ID, true, nil
		}
		return "", false, fmt.Errorf("ApplyPatchSoftwareTitleConfigurationV3: resolve: %w", err)
	}
	// Convert create request to update type via JSON round-trip.
	data, marshalErr := json.Marshal(request)
	if marshalErr != nil {
		return "", false, fmt.Errorf("ApplyPatchSoftwareTitleConfigurationV3: marshal for update(%s): %w", id, marshalErr)
	}
	var updateReq PatchSoftwareTitleConfigurationPatch
	if unmarshalErr := json.Unmarshal(data, &updateReq); unmarshalErr != nil {
		return "", false, fmt.Errorf("ApplyPatchSoftwareTitleConfigurationV3: unmarshal for update(%s): %w", id, unmarshalErr)
	}
	_, err = c.UpdatePatchSoftwareTitleConfigurationV3(ctx, id, &updateReq)
	if err != nil {
		return "", false, fmt.Errorf("ApplyPatchSoftwareTitleConfigurationV3: update(%s): %w", id, err)
	}
	return id, false, nil
}
