// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package pro

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"github.com/jamf/jamfplatform-go-sdk/internal/client"
)

// ListPatchPoliciesV2 retrieve Patch Policies.
//
// Required privileges: patch-policies:read. Legacy Jamf Pro privilege name(s): Read Patch Policies.
//
// Parameters:
//   - sort: Sorting criteria in the format: property:asc/desc. Default sort is id:asc. Multiple sort criteria
//     are supported and must be separated with a comma.
//   - filter: Query in the RSQL format, allowing to filter Patch Policy collection. Default filter is empty query
//   - returning all results for the requested page. Fields allowed in the query: id, policyName,
//     policyEnabled, policyTargetVersion, policyDeploymentMethod, softwareTitle,
//     softwareTitleConfigurationId, pending, completed, deferred, and failed. This param can be combined
//     with paging and sorting.
func (c *Client) ListPatchPoliciesV2(ctx context.Context, sort []string, filter string) ([]PatchPolicyListView, error) {
	prefix := c.transport.APIPrefix("pro", "v2")
	return client.ListAllPages(ctx, 2000, func(ctx context.Context, page, pageSize int) ([]PatchPolicyListView, bool, error) {
		params := url.Values{}
		params.Set("page", strconv.Itoa(page))
		params.Set("page-size", strconv.Itoa(pageSize))
		if len(sort) > 0 {
			params.Set("sort", strings.Join(sort, ","))
		}
		if filter != "" {
			params.Set("filter", filter)
		}

		endpoint := prefix + "/patch-policies"
		if encoded := params.Encode(); encoded != "" {
			endpoint += "?" + encoded
		}
		var result struct {
			TotalCount int                   `json:"totalCount"`
			Results    []PatchPolicyListView `json:"results"`
		}
		if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
			return nil, false, err
		}
		hasNext := (page+1)*pageSize < result.TotalCount
		return result.Results, hasNext, nil
	})
}

// ListPatchPolicyDetailsV2 retrieve Patch Policies.
//
// Required privileges: patch-policies:read. Legacy Jamf Pro privilege name(s): Read Patch Policies.
//
// Parameters:
//   - sort: Sorting criteria in the format: property:asc/desc. Default sort is id:asc. Multiple sort criteria
//     are supported and must be separated with a comma.
//   - filter: Query in the RSQL format, allowing to filter Patch Policy collection. Default filter is empty query
//   - returning all results for the requested page. Fields allowed in the query: id, name, enabled,
//     targetPatchVersion, deploymentMethod, softwareTitleId, softwareTitleConfigurationId,
//     killAppsDelayMinutes, killAppsMessage, isDowngrade, isPatchUnknownVersion, notificationHeader,
//     selfServiceEnforceDeadline, selfServiceDeadline, installButtonText, selfServiceDescription, iconId,
//     reminderFrequency, reminderEnabled. This param can be combined with paging and sorting.
func (c *Client) ListPatchPolicyDetailsV2(ctx context.Context, sort []string, filter string) ([]PatchPolicyDetail, error) {
	prefix := c.transport.APIPrefix("pro", "v2")
	return client.ListAllPages(ctx, 2000, func(ctx context.Context, page, pageSize int) ([]PatchPolicyDetail, bool, error) {
		params := url.Values{}
		params.Set("page", strconv.Itoa(page))
		params.Set("page-size", strconv.Itoa(pageSize))
		if len(sort) > 0 {
			params.Set("sort", strings.Join(sort, ","))
		}
		if filter != "" {
			params.Set("filter", filter)
		}

		endpoint := prefix + "/patch-policies/policy-details"
		if encoded := params.Encode(); encoded != "" {
			endpoint += "?" + encoded
		}
		var result struct {
			TotalCount int                 `json:"totalCount"`
			Results    []PatchPolicyDetail `json:"results"`
		}
		if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
			return nil, false, err
		}
		hasNext := (page+1)*pageSize < result.TotalCount
		return result.Results, hasNext, nil
	})
}

// GetPatchPolicyDashboardStatusV2 return whether or not the requested patch policy is on the dashboard.
//
// Required privileges: patch-policies:read. Legacy Jamf Pro privilege name(s): Read Patch Policies.
//
// Parameters:
//   - id: patch policy id.
func (c *Client) GetPatchPolicyDashboardStatusV2(ctx context.Context, id string) (*PatchPolicyV2OnDashboard, error) {
	prefix := c.transport.APIPrefix("pro", "v2")
	var result PatchPolicyV2OnDashboard
	endpoint := fmt.Sprintf("%s/patch-policies/%s/dashboard", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetPatchPolicyDashboardStatusV2(%s): %w", id, err)
	}
	return &result, nil
}

// AddPatchPolicyToDashboardV2 add a patch policy to the dashboard.
//
// Required privileges: patch-policies:read. Legacy Jamf Pro privilege name(s): Read Patch Policies.
//
// Parameters:
//   - id: patch policy id.
func (c *Client) AddPatchPolicyToDashboardV2(ctx context.Context, id string) error {
	prefix := c.transport.APIPrefix("pro", "v2")
	endpoint := fmt.Sprintf("%s/patch-policies/%s/dashboard", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodPost, endpoint, nil, http.StatusNoContent, nil); err != nil {
		return fmt.Errorf("AddPatchPolicyToDashboardV2(%s): %w", id, err)
	}
	return nil
}

// RemovePatchPolicyFromDashboardV2 remove a patch policy from the dashboard.
//
// Required privileges: patch-policies:read. Legacy Jamf Pro privilege name(s): Read Patch Policies.
//
// Parameters:
//   - id: patch policy id.
func (c *Client) RemovePatchPolicyFromDashboardV2(ctx context.Context, id string) error {
	prefix := c.transport.APIPrefix("pro", "v2")
	endpoint := fmt.Sprintf("%s/patch-policies/%s/dashboard", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusNoContent, nil); err != nil {
		return fmt.Errorf("RemovePatchPolicyFromDashboardV2(%s): %w", id, err)
	}
	return nil
}

// ResolvePatchPolicyV2IDByName looks up a PatchPolicyV2 by its policyName field and returns the ID. Returns *APIResponseError with HasStatus(404) when no match exists, or *AmbiguousMatchError when multiple resources share the name.
func (c *Client) ResolvePatchPolicyV2IDByName(ctx context.Context, name string) (string, error) {
	prefix := c.transport.APIPrefix("pro", "v2")
	listPath := prefix + "/patch-policies"
	id, _, err := c.transport.ResolveByNameFiltered(ctx, listPath, "", "policyName", "policyName", "id", name)
	if err != nil {
		return "", fmt.Errorf("ResolvePatchPolicyV2IDByName(%s): %w", name, err)
	}
	return id, nil
}

// ResolvePatchPolicyV2ByName looks up a PatchPolicyV2 by its policyName field and returns the decoded resource. Shares the same HTTP call as the ID-only variant; error semantics are identical.
func (c *Client) ResolvePatchPolicyV2ByName(ctx context.Context, name string) (*PatchPolicyListView, error) {
	prefix := c.transport.APIPrefix("pro", "v2")
	listPath := prefix + "/patch-policies"
	_, raw, err := c.transport.ResolveByNameFiltered(ctx, listPath, "", "policyName", "policyName", "id", name)
	if err != nil {
		return nil, fmt.Errorf("ResolvePatchPolicyV2ByName(%s): %w", name, err)
	}
	var out PatchPolicyListView
	if err := json.Unmarshal(raw, &out); err != nil {
		return nil, fmt.Errorf("ResolvePatchPolicyV2ByName(%s): decoding matched element: %w", name, err)
	}
	return &out, nil
}
