// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package pro

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"github.com/jamf/jamfplatform-go-sdk/internal/client"
)

// ListIOSBrandingConfigurationsV1 search for sorted and paged iOS branding configurations.
//
// Required privileges: self-service:read. Legacy Jamf Pro privilege name(s): Read Self Service Branding Configuration.
//
// Parameters:
//   - sort: Sorting criteria in the format: property:asc/desc. Default sort is id:asc. Multiple sort criteria
//     are supported and must be separated with a comma. Example: sort=id:desc,brandingName:asc.
func (c *Client) ListIOSBrandingConfigurationsV1(ctx context.Context, sort []string) ([]IosBrandingConfiguration, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	return client.ListAllPages(ctx, 2000, func(ctx context.Context, page, pageSize int) ([]IosBrandingConfiguration, bool, error) {
		params := url.Values{}
		params.Set("page", strconv.Itoa(page))
		params.Set("page-size", strconv.Itoa(pageSize))
		if len(sort) > 0 {
			params.Set("sort", strings.Join(sort, ","))
		}

		endpoint := prefix + "/self-service/branding/ios"
		if encoded := params.Encode(); encoded != "" {
			endpoint += "?" + encoded
		}
		var result struct {
			TotalCount int                        `json:"totalCount"`
			Results    []IosBrandingConfiguration `json:"results"`
		}
		if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
			return nil, false, err
		}
		hasNext := (page+1)*pageSize < result.TotalCount
		return result.Results, hasNext, nil
	})
}

// CreateIOSBrandingConfigurationV1 create a Self Service iOS branding configuration with the supplied.
//
// Required privileges: self-service:create. Legacy Jamf Pro privilege name(s): Create Self Service Branding Configuration.
func (c *Client) CreateIOSBrandingConfigurationV1(ctx context.Context, request *IosBrandingConfiguration) (*HrefResponse, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result HrefResponse
	endpoint := prefix + "/self-service/branding/ios"
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("CreateIOSBrandingConfigurationV1: %w", err)
	}
	return &result, nil
}

// GetIOSBrandingConfigurationV1 read a single Self Service iOS branding configuration indicated by the provided id.
//
// Required privileges: self-service:read. Legacy Jamf Pro privilege name(s): Read Self Service Branding Configuration.
//
// Parameters:
//   - id: id of iOS branding configuration.
func (c *Client) GetIOSBrandingConfigurationV1(ctx context.Context, id string) (*IosBrandingConfiguration, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result IosBrandingConfiguration
	endpoint := fmt.Sprintf("%s/self-service/branding/ios/%s", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetIOSBrandingConfigurationV1(%s): %w", id, err)
	}
	return &result, nil
}

// UpdateIOSBrandingConfigurationV1 update a Self Service iOS branding configuration with the supplied details.
//
// Required privileges: self-service:update. Legacy Jamf Pro privilege name(s): Update Self Service Branding Configuration.
//
// Parameters:
//   - id: id of iOS branding configuration.
func (c *Client) UpdateIOSBrandingConfigurationV1(ctx context.Context, id string, request *IosBrandingConfiguration) (*IosBrandingConfiguration, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	var result IosBrandingConfiguration
	endpoint := fmt.Sprintf("%s/self-service/branding/ios/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoWithContentType(ctx, http.MethodPut, endpoint, request, "application/json", http.StatusOK, &result); err != nil {
		return nil, fmt.Errorf("UpdateIOSBrandingConfigurationV1(%s): %w", id, err)
	}
	return &result, nil
}

// DeleteIOSBrandingConfigurationV1 delete the Self Service iOS branding configuration indicated by the provided id.
//
// Required privileges: self-service:delete. Legacy Jamf Pro privilege name(s): Delete Self Service Branding Configuration.
//
// Parameters:
//   - id: id of iOS branding configuration.
func (c *Client) DeleteIOSBrandingConfigurationV1(ctx context.Context, id string) error {
	prefix := c.transport.APIPrefix("pro", "v1")
	endpoint := fmt.Sprintf("%s/self-service/branding/ios/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusNoContent, nil); err != nil {
		return fmt.Errorf("DeleteIOSBrandingConfigurationV1(%s): %w", id, err)
	}
	return nil
}

// ResolveIOSBrandingConfigurationV1IDByName looks up a IOSBrandingConfigurationV1 by its brandingName field and returns the ID. Returns *APIResponseError with HasStatus(404) when no match exists, or *AmbiguousMatchError when multiple resources share the name.
func (c *Client) ResolveIOSBrandingConfigurationV1IDByName(ctx context.Context, name string) (string, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	listPath := prefix + "/self-service/branding/ios"
	id, _, err := c.transport.ResolveByNameClientPaged(ctx, listPath, "", "", "brandingName", "id", name)
	if err != nil {
		return "", fmt.Errorf("ResolveIOSBrandingConfigurationV1IDByName(%s): %w", name, err)
	}
	return id, nil
}

// ResolveIOSBrandingConfigurationV1ByName looks up a IOSBrandingConfigurationV1 by its brandingName field and returns the decoded resource. Shares the same HTTP call as the ID-only variant; error semantics are identical.
func (c *Client) ResolveIOSBrandingConfigurationV1ByName(ctx context.Context, name string) (*IosBrandingConfiguration, error) {
	prefix := c.transport.APIPrefix("pro", "v1")
	listPath := prefix + "/self-service/branding/ios"
	_, raw, err := c.transport.ResolveByNameClientPaged(ctx, listPath, "", "", "brandingName", "id", name)
	if err != nil {
		return nil, fmt.Errorf("ResolveIOSBrandingConfigurationV1ByName(%s): %w", name, err)
	}
	var out IosBrandingConfiguration
	if err := json.Unmarshal(raw, &out); err != nil {
		return nil, fmt.Errorf("ResolveIOSBrandingConfigurationV1ByName(%s): decoding matched element: %w", name, err)
	}
	return &out, nil
}

// ApplyIOSBrandingConfigurationV1 creates or updates a IOSBrandingConfigurationV1 by name. If a resource with the specified name exists, it is updated; if not found, a new resource is created. Returns the resource ID, whether it was created (true) or updated (false), and any error. An *AmbiguousMatchError is returned if multiple resources match the name.
func (c *Client) ApplyIOSBrandingConfigurationV1(ctx context.Context, request *IosBrandingConfiguration) (string, bool, error) {
	name := request.BrandingName
	if name == "" {
		return "", false, fmt.Errorf("ApplyIOSBrandingConfigurationV1: BrandingName must not be empty")
	}
	id, err := c.ResolveIOSBrandingConfigurationV1IDByName(ctx, name)
	if err != nil {
		if apiErr := client.AsAPIError(err); apiErr != nil && apiErr.HasStatus(404) {
			resp, createErr := c.CreateIOSBrandingConfigurationV1(ctx, request)
			if createErr != nil {
				return "", false, fmt.Errorf("ApplyIOSBrandingConfigurationV1: create: %w", createErr)
			}
			return resp.ID, true, nil
		}
		return "", false, fmt.Errorf("ApplyIOSBrandingConfigurationV1: resolve: %w", err)
	}
	_, err = c.UpdateIOSBrandingConfigurationV1(ctx, id, request)
	if err != nil {
		return "", false, fmt.Errorf("ApplyIOSBrandingConfigurationV1: update(%s): %w", id, err)
	}
	return id, false, nil
}
