// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package pro

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"

	"github.com/jamf/jamfplatform-go-sdk/internal/client"
)

// CreateTeamViewerConfigurationPreview create Team Viewer Remote Administration connection configuration.
//
// Required privileges: remote-administration:create. Legacy Jamf Pro privilege name(s): Create Remote Administration.
func (c *Client) CreateTeamViewerConfigurationPreview(ctx context.Context, request *ConnectionConfigurationCandidateRequest) (*HrefResponse, error) {
	prefix := c.transport.APIPrefix("pro", "")
	var result HrefResponse
	endpoint := prefix + "/preview/remote-administration-configurations/team-viewer"
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("CreateTeamViewerConfigurationPreview: %w", err)
	}
	return &result, nil
}

// GetTeamViewerConfigurationPreview get Team Viewer Remote Administration connection configuration.
//
// Required privileges: remote-administration:read. Legacy Jamf Pro privilege name(s): Read Remote Administration.
//
// Parameters:
//   - id: ID of the Team Viewer connection configuration.
func (c *Client) GetTeamViewerConfigurationPreview(ctx context.Context, id string) (*ConnectionConfigurationResponse, error) {
	prefix := c.transport.APIPrefix("pro", "")
	var result ConnectionConfigurationResponse
	endpoint := fmt.Sprintf("%s/preview/remote-administration-configurations/team-viewer/%s", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetTeamViewerConfigurationPreview(%s): %w", id, err)
	}
	return &result, nil
}

// UpdateTeamViewerConfigurationPreview update Team Viewer Remote Administration connection configuration.
//
// Required privileges: remote-administration:update. Legacy Jamf Pro privilege name(s): Update Remote Administration.
//
// Parameters:
//   - id: ID of the Team Viewer connection configuration.
func (c *Client) UpdateTeamViewerConfigurationPreview(ctx context.Context, id string, request *ConnectionConfigurationUpdateRequest) (*ConnectionConfigurationResponse, error) {
	prefix := c.transport.APIPrefix("pro", "")
	var result ConnectionConfigurationResponse
	endpoint := fmt.Sprintf("%s/preview/remote-administration-configurations/team-viewer/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoWithContentType(ctx, http.MethodPatch, endpoint, request, "application/json", http.StatusOK, &result); err != nil {
		return nil, fmt.Errorf("UpdateTeamViewerConfigurationPreview(%s): %w", id, err)
	}
	return &result, nil
}

// DeleteTeamViewerConfigurationPreview delete Team Viewer Remote Administration connection configuration.
//
// Required privileges: remote-administration:delete. Legacy Jamf Pro privilege name(s): Delete Remote Administration.
//
// Parameters:
//   - id: ID of the Team Viewer connection configuration.
func (c *Client) DeleteTeamViewerConfigurationPreview(ctx context.Context, id string) error {
	prefix := c.transport.APIPrefix("pro", "")
	endpoint := fmt.Sprintf("%s/preview/remote-administration-configurations/team-viewer/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusNoContent, nil); err != nil {
		return fmt.Errorf("DeleteTeamViewerConfigurationPreview(%s): %w", id, err)
	}
	return nil
}

// GetTeamViewerConfigurationStatusPreview get Team Viewer Remote Administration connection status.
//
// Required privileges: remote-administration:read. Legacy Jamf Pro privilege name(s): Read Remote Administration.
//
// Parameters:
//   - id: ID of the Team Viewer connection configuration.
func (c *Client) GetTeamViewerConfigurationStatusPreview(ctx context.Context, id string) (*ConnectionConfigurationStatusResponse, error) {
	prefix := c.transport.APIPrefix("pro", "")
	var result ConnectionConfigurationStatusResponse
	endpoint := fmt.Sprintf("%s/preview/remote-administration-configurations/team-viewer/%s/status", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetTeamViewerConfigurationStatusPreview(%s): %w", id, err)
	}
	return &result, nil
}

// ListTeamViewerSessionsPreview get a paginated list of sessions.
//
// Required privileges: remote-administration:read. Legacy Jamf Pro privilege name(s): Read Remote Administration.
//
// Parameters:
//   - configurationID: ID of the Team Viewer connection configuration.
//   - filter: Query in the RSQL format, allowing to filter sessions collection. Default filter is empty query -
//     returning all results for the requested page.
//     Fields allowed in the query: `deviceId`, `deviceType`, `state`.
//     This param can be combined with paging.
func (c *Client) ListTeamViewerSessionsPreview(ctx context.Context, configurationID string, filter string) ([]SessionDetails, error) {
	prefix := c.transport.APIPrefix("pro", "")
	return client.ListAllPages(ctx, 2000, func(ctx context.Context, page, pageSize int) ([]SessionDetails, bool, error) {
		params := url.Values{}
		params.Set("page", strconv.Itoa(page))
		params.Set("page-size", strconv.Itoa(pageSize))
		if filter != "" {
			params.Set("filter", filter)
		}

		endpoint := fmt.Sprintf("%s/preview/remote-administration-configurations/team-viewer/%s/sessions", prefix, url.PathEscape(configurationID))
		if encoded := params.Encode(); encoded != "" {
			endpoint += "?" + encoded
		}
		var result struct {
			TotalCount int              `json:"totalCount"`
			Results    []SessionDetails `json:"results"`
		}
		if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
			return nil, false, err
		}
		hasNext := (page+1)*pageSize < result.TotalCount
		return result.Results, hasNext, nil
	})
}

// CreateTeamViewerSessionPreview create a new session.
//
// Required privileges: remote-administration:create. Legacy Jamf Pro privilege name(s): Create Remote Administration.
//
// Parameters:
//   - configurationID: ID of the Team Viewer connection configuration.
func (c *Client) CreateTeamViewerSessionPreview(ctx context.Context, configurationID string, request *SessionCandidateRequest) (*HrefResponse, error) {
	prefix := c.transport.APIPrefix("pro", "")
	var result HrefResponse
	endpoint := fmt.Sprintf("%s/preview/remote-administration-configurations/team-viewer/%s/sessions", prefix, url.PathEscape(configurationID))
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("CreateTeamViewerSessionPreview(%s): %w", configurationID, err)
	}
	return &result, nil
}

// GetTeamViewerSessionPreview get a session by its ID.
//
// Required privileges: remote-administration:read. Legacy Jamf Pro privilege name(s): Read Remote Administration.
//
// Parameters:
//   - configurationID: ID of the Team Viewer connection configuration.
//   - sessionID: ID of the Team Viewer session.
func (c *Client) GetTeamViewerSessionPreview(ctx context.Context, configurationID string, sessionID string) (*SessionDetails, error) {
	prefix := c.transport.APIPrefix("pro", "")
	var result SessionDetails
	endpoint := fmt.Sprintf("%s/preview/remote-administration-configurations/team-viewer/%s/sessions/%s", prefix, url.PathEscape(configurationID), url.PathEscape(sessionID))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetTeamViewerSessionPreview(%s): %w", configurationID, err)
	}
	return &result, nil
}

// GetTeamViewerSessionStatusPreview get a session status by its ID.
//
// Required privileges: remote-administration:read. Legacy Jamf Pro privilege name(s): Read Remote Administration.
//
// Parameters:
//   - configurationID: ID of the Team Viewer connection configuration.
//   - sessionID: ID of the Team Viewer session.
func (c *Client) GetTeamViewerSessionStatusPreview(ctx context.Context, configurationID string, sessionID string) (*SessionStatus, error) {
	prefix := c.transport.APIPrefix("pro", "")
	var result SessionStatus
	endpoint := fmt.Sprintf("%s/preview/remote-administration-configurations/team-viewer/%s/sessions/%s/status", prefix, url.PathEscape(configurationID), url.PathEscape(sessionID))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetTeamViewerSessionStatusPreview(%s): %w", configurationID, err)
	}
	return &result, nil
}

// CloseTeamViewerSessionPreview close a session.
//
// Required privileges: remote-administration:update. Legacy Jamf Pro privilege name(s): Update Remote Administration.
//
// Parameters:
//   - configurationID: ID of the Team Viewer connection configuration.
//   - sessionID: ID of the Team Viewer session.
func (c *Client) CloseTeamViewerSessionPreview(ctx context.Context, configurationID string, sessionID string) error {
	prefix := c.transport.APIPrefix("pro", "")
	endpoint := fmt.Sprintf("%s/preview/remote-administration-configurations/team-viewer/%s/sessions/%s/close", prefix, url.PathEscape(configurationID), url.PathEscape(sessionID))
	if err := c.transport.DoExpect(ctx, http.MethodPost, endpoint, nil, http.StatusNoContent, nil); err != nil {
		return fmt.Errorf("CloseTeamViewerSessionPreview(%s): %w", configurationID, err)
	}
	return nil
}

// ResendTeamViewerSessionNotificationPreview resend nofications for a session.
//
// Required privileges: remote-administration:update. Legacy Jamf Pro privilege name(s): Update Remote Administration.
//
// Parameters:
//   - configurationID: ID of the Team Viewer connection configuration.
//   - sessionID: ID of the Team Viewer session.
func (c *Client) ResendTeamViewerSessionNotificationPreview(ctx context.Context, configurationID string, sessionID string) error {
	prefix := c.transport.APIPrefix("pro", "")
	endpoint := fmt.Sprintf("%s/preview/remote-administration-configurations/team-viewer/%s/sessions/%s/resend-notification", prefix, url.PathEscape(configurationID), url.PathEscape(sessionID))
	if err := c.transport.DoExpect(ctx, http.MethodPost, endpoint, nil, http.StatusNoContent, nil); err != nil {
		return fmt.Errorf("ResendTeamViewerSessionNotificationPreview(%s): %w", configurationID, err)
	}
	return nil
}
