// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package devicegroups

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/jamf/jamfplatform-go-sdk/internal/client"
)

// ListDeviceGroupsForDevice get device groups for a device.
//
// Required privileges: device-groups:read.
//
// Parameters:
//   - deviceID: The ID of the device, in UUID format.
func (c *Client) ListDeviceGroupsForDevice(ctx context.Context, deviceID string) ([]DeviceGroupMemberOfRepresentationV1, error) {
	prefix := c.transport.APIPrefix("device-groups", "v1")
	endpoint := fmt.Sprintf("%s/devices/%s/device-groups", prefix, url.PathEscape(deviceID))

	results, err := client.UnwrapResults[DeviceGroupMemberOfRepresentationV1](ctx, c.transport, http.MethodGet, endpoint, "results")
	if err != nil {
		return nil, fmt.Errorf("ListDeviceGroupsForDevice(%s): %w", deviceID, err)
	}
	return results, nil
}
