// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package aigovernance

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"github.com/Jamf-Concepts/jamfplatform-go-sdk/internal/client"
)

// ListPolicies list active AI governance policies for the tenant.
//
// Preview: this endpoint is marked preview in the Jamf API spec; its request and response shapes may change without warning, and successful responses carry a Jamf-Preview: true header.
//
// Required privileges: ai-policies:read.
//
// Parameters:
//   - sort: Sorting criteria in the format: property:(asc|desc). Supported properties: createdAt, updatedAt,
//     name.
//   - schemaDrift: When true, return only policies whose stored schemaVersion differs from the current tool schema
//     version.
func (c *Client) ListPolicies(ctx context.Context, sort []string, schemaDrift bool) ([]PolicySummary, error) {
	prefix := c.transport.APIPrefix("ai/governance/policies", "v1")
	return client.ListAllPages(ctx, 100, func(ctx context.Context, page, pageSize int) ([]PolicySummary, bool, error) {
		params := url.Values{}
		params.Set("page", strconv.Itoa(page))
		params.Set("page-size", strconv.Itoa(pageSize))
		if len(sort) > 0 {
			params.Set("sort", strings.Join(sort, ","))
		}
		if schemaDrift {
			params.Set("schema-drift", "true")
		}

		endpoint := prefix + "/policies"
		if encoded := params.Encode(); encoded != "" {
			endpoint += "?" + encoded
		}
		var result struct {
			TotalCount int             `json:"totalCount"`
			Results    []PolicySummary `json:"results"`
		}
		if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
			return nil, false, err
		}
		hasNext := (page+1)*pageSize < result.TotalCount
		return result.Results, hasNext, nil
	})
}

// CreatePolicy create a new AI governance policy.
//
// Preview: this endpoint is marked preview in the Jamf API spec; its request and response shapes may change without warning, and successful responses carry a Jamf-Preview: true header.
//
// Required privileges: ai-policies:create.
func (c *Client) CreatePolicy(ctx context.Context, request *CreatePolicyRequest) (*CreatedResponse, error) {
	prefix := c.transport.APIPrefix("ai/governance/policies", "v1")
	var result CreatedResponse
	endpoint := prefix + "/policies"
	if err := c.transport.DoWithContentType(ctx, http.MethodPost, endpoint, request, "application/json", http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("CreatePolicy: %w", err)
	}
	return &result, nil
}

// GetPolicy get a policy by ID.
//
// Preview: this endpoint is marked preview in the Jamf API spec; its request and response shapes may change without warning, and successful responses carry a Jamf-Preview: true header.
//
// Required privileges: ai-policies:read.
//
// Parameters:
//   - policyID: Policy ID.
func (c *Client) GetPolicy(ctx context.Context, policyID string) (*PolicyDetail, error) {
	prefix := c.transport.APIPrefix("ai/governance/policies", "v1")
	var result PolicyDetail
	endpoint := fmt.Sprintf("%s/policies/%s", prefix, url.PathEscape(policyID))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetPolicy(%s): %w", policyID, err)
	}
	return &result, nil
}

// UpdatePolicy save draft settings for an existing policy.
//
// Preview: this endpoint is marked preview in the Jamf API spec; its request and response shapes may change without warning, and successful responses carry a Jamf-Preview: true header.
//
// Required privileges: ai-policies:update.
//
// Parameters:
//   - policyID: Policy ID.
//   - ifMatch: Optimistic-lock precondition. Supply the ETag from a prior GET (e.g. `"7"`) to make the update
//     conditional on the policy still being at that version; a mismatch yields 409
//     (POLICY_VERSION_CONFLICT). A weak validator (`W/"7"`) is also accepted. Omit the header or send `*`
//     for an unconditional update.
func (c *Client) UpdatePolicy(ctx context.Context, policyID string, request *UpdatePolicyRequest, ifMatch string) error {
	prefix := c.transport.APIPrefix("ai/governance/policies", "v1")
	endpoint := fmt.Sprintf("%s/policies/%s", prefix, url.PathEscape(policyID))
	headers := http.Header{}
	if ifMatch != "" {
		headers.Set("If-Match", ifMatch)
	}
	if err := c.transport.DoWithOptions(ctx, http.MethodPatch, endpoint, request, client.RequestOptions{ExpectedStatus: http.StatusNoContent, ContentType: "application/json", Headers: headers}, nil); err != nil {
		return fmt.Errorf("UpdatePolicy(%s): %w", policyID, err)
	}
	return nil
}

// ArchivePolicy archive an AI governance policy (soft delete).
//
// Preview: this endpoint is marked preview in the Jamf API spec; its request and response shapes may change without warning, and successful responses carry a Jamf-Preview: true header.
//
// Required privileges: ai-policies:delete.
//
// Parameters:
//   - policyID: Policy ID.
func (c *Client) ArchivePolicy(ctx context.Context, policyID string) error {
	prefix := c.transport.APIPrefix("ai/governance/policies", "v1")
	endpoint := fmt.Sprintf("%s/policies/%s", prefix, url.PathEscape(policyID))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusNoContent, nil); err != nil {
		return fmt.Errorf("ArchivePolicy(%s): %w", policyID, err)
	}
	return nil
}

// GetPolicyDeployment get deployment state for a policy.
//
// Preview: this endpoint is marked preview in the Jamf API spec; its request and response shapes may change without warning, and successful responses carry a Jamf-Preview: true header.
//
// Required privileges: ai-policies:read.
//
// Parameters:
//   - policyID: Policy ID.
func (c *Client) GetPolicyDeployment(ctx context.Context, policyID string) (*PolicyDeploymentResponse, error) {
	prefix := c.transport.APIPrefix("ai/governance/policies", "v1")
	var result PolicyDeploymentResponse
	endpoint := fmt.Sprintf("%s/policies/%s/deployment", prefix, url.PathEscape(policyID))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetPolicyDeployment(%s): %w", policyID, err)
	}
	return &result, nil
}

// PublishPolicy publish current draft settings as a new immutable PolicyVersion.
//
// Preview: this endpoint is marked preview in the Jamf API spec; its request and response shapes may change without warning, and successful responses carry a Jamf-Preview: true header.
//
// Required privileges: ai-policies:update.
//
// Parameters:
//   - policyID: Policy ID.
func (c *Client) PublishPolicy(ctx context.Context, policyID string) (*PublishResponse, error) {
	prefix := c.transport.APIPrefix("ai/governance/policies", "v1")
	var result PublishResponse
	endpoint := fmt.Sprintf("%s/policies/%s/publish", prefix, url.PathEscape(policyID))
	if err := c.transport.DoExpect(ctx, http.MethodPost, endpoint, nil, http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("PublishPolicy(%s): %w", policyID, err)
	}
	return &result, nil
}

// ListPolicyVersions list all versions for a policy.
//
// Preview: this endpoint is marked preview in the Jamf API spec; its request and response shapes may change without warning, and successful responses carry a Jamf-Preview: true header.
//
// Required privileges: ai-policies:read.
//
// Parameters:
//   - policyID: Policy ID.
func (c *Client) ListPolicyVersions(ctx context.Context, policyID string) ([]PolicyVersion, error) {
	prefix := c.transport.APIPrefix("ai/governance/policies", "v1")
	return client.ListAllPages(ctx, 100, func(ctx context.Context, page, pageSize int) ([]PolicyVersion, bool, error) {
		params := url.Values{}
		params.Set("page", strconv.Itoa(page))
		params.Set("page-size", strconv.Itoa(pageSize))

		endpoint := fmt.Sprintf("%s/policies/%s/versions", prefix, url.PathEscape(policyID))
		if encoded := params.Encode(); encoded != "" {
			endpoint += "?" + encoded
		}
		var result struct {
			TotalCount int             `json:"totalCount"`
			Results    []PolicyVersion `json:"results"`
		}
		if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
			return nil, false, err
		}
		hasNext := (page+1)*pageSize < result.TotalCount
		return result.Results, hasNext, nil
	})
}

// GetPolicyVersion get a specific policy version.
//
// Preview: this endpoint is marked preview in the Jamf API spec; its request and response shapes may change without warning, and successful responses carry a Jamf-Preview: true header.
//
// Required privileges: ai-policies:read.
//
// Parameters:
//   - policyID: Policy ID.
//   - versionNumber: Published version number (1-based, increments on each publish).
func (c *Client) GetPolicyVersion(ctx context.Context, policyID string, versionNumber string) (*PolicyVersion, error) {
	prefix := c.transport.APIPrefix("ai/governance/policies", "v1")
	var result PolicyVersion
	endpoint := fmt.Sprintf("%s/policies/%s/versions/%s", prefix, url.PathEscape(policyID), url.PathEscape(versionNumber))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetPolicyVersion(%s): %w", policyID, err)
	}
	return &result, nil
}
