// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package audit

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"github.com/jamf/jamfplatform-go-sdk/internal/client"
)

// ListAuditEvents filter audit events.
//
// Required privileges: audit:read.
//
// Parameters:
//   - since: Inclusive lower bound on event time (ISO-8601, required).
//   - until: Inclusive upper bound on event time (ISO-8601); defaults to now.
//   - actor: Actor id to filter by. The `|` in auth0 identifiers must be URI-encoded as `%7C`.
//   - auditSource: Event sources to include (comma-separated, max 50).
//   - auditType: Event types to include (comma-separated, max 50). Supports trailing wildcards like `blueprint.*`.
//   - resourceID: Resource ids to include (comma-separated, max 50).
func (c *Client) ListAuditEvents(ctx context.Context, since string, until string, actor string, auditSource []string, auditType []string, resourceID []string) ([]AuditEnvelope, error) {
	prefix := c.transport.APIPrefix("audit", "v1")
	return client.ListAllCursorPages(ctx, 100, func(ctx context.Context, cursor string, pageSize int) ([]AuditEnvelope, string, error) {
		params := url.Values{}
		params.Set("page-size", strconv.Itoa(pageSize))
		if cursor != "" {
			params.Set("cursor", cursor)
		}
		params.Set("since", since)
		if until != "" {
			params.Set("until", until)
		}
		if actor != "" {
			params.Set("actor", actor)
		}
		if len(auditSource) > 0 {
			params.Set("audit-source", strings.Join(auditSource, ","))
		}
		if len(auditType) > 0 {
			params.Set("audit-type", strings.Join(auditType, ","))
		}
		if len(resourceID) > 0 {
			params.Set("resource-id", strings.Join(resourceID, ","))
		}

		endpoint := prefix + "/audit"
		if encoded := params.Encode(); encoded != "" {
			endpoint += "?" + encoded
		}

		var result struct {
			Results    []AuditEnvelope `json:"items"`
			NextCursor string          `json:"nextCursor"`
		}
		if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
			return nil, "", err
		}
		return result.Results, result.NextCursor, nil
	})
}

// GetResourceLineage get resource lineage.
//
// Required privileges: audit:read.
//
// Parameters:
//   - resourceID: Resource identifier (1-256 characters).
//   - auditType: Optional event type filter. Supports trailing wildcards like `blueprint.*`.
//   - since: Optional lower bound on event time (ISO-8601).
//   - until: Optional upper bound on event time (ISO-8601).
func (c *Client) GetResourceLineage(ctx context.Context, resourceID string, auditType string, since string, until string) ([]TransactionGroup, error) {
	prefix := c.transport.APIPrefix("audit", "v1")
	return client.ListAllCursorPages(ctx, 100, func(ctx context.Context, cursor string, pageSize int) ([]TransactionGroup, string, error) {
		params := url.Values{}
		params.Set("page-size", strconv.Itoa(pageSize))
		if cursor != "" {
			params.Set("cursor", cursor)
		}
		if auditType != "" {
			params.Set("audit-type", auditType)
		}
		if since != "" {
			params.Set("since", since)
		}
		if until != "" {
			params.Set("until", until)
		}

		endpoint := fmt.Sprintf("%s/audit/resources/%s/lineage", prefix, url.PathEscape(resourceID))
		if encoded := params.Encode(); encoded != "" {
			endpoint += "?" + encoded
		}

		var result struct {
			Results    []TransactionGroup `json:"transactions"`
			NextCursor string             `json:"nextCursor"`
		}
		if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
			return nil, "", err
		}
		return result.Results, result.NextCursor, nil
	})
}

// ListAuditSources discover audit sources.
//
// Required privileges: audit:read.
//
// Parameters:
//   - since: Optional lower bound on event time (ISO-8601). Defaults to 90 days ago.
func (c *Client) ListAuditSources(ctx context.Context, since string) ([]AuditSourceInfo, error) {
	prefix := c.transport.APIPrefix("audit", "v1")
	var result []AuditSourceInfo
	endpoint := prefix + "/audit/sources"
	params := url.Values{}
	if since != "" {
		params.Set("since", since)
	}
	if encoded := params.Encode(); encoded != "" {
		endpoint += "?" + encoded
	}
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("ListAuditSources: %w", err)
	}
	return result, nil
}

// GetTransactionTimeline get transaction timeline.
//
// Required privileges: audit:read.
//
// Parameters:
//   - txID: Transaction id (UUID).
func (c *Client) GetTransactionTimeline(ctx context.Context, txID string) ([]AuditEnvelope, error) {
	prefix := c.transport.APIPrefix("audit", "v1")
	var result []AuditEnvelope
	endpoint := fmt.Sprintf("%s/audit/transactions/%s", prefix, url.PathEscape(txID))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetTransactionTimeline(%s): %w", txID, err)
	}
	return result, nil
}
