// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package proclassic

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"

	"github.com/jamf/jamfplatform-go-sdk/internal/client"
)

// GetDirectoryBindingByID finds directory bindings by ID.
//
// Required privileges: directory-bindings:read.
//
// Parameters:
//   - id: ID value to filter by.
func (c *Client) GetDirectoryBindingByID(ctx context.Context, id string) (*DirectoryBinding, error) {
	prefix := c.transport.APIPrefix("proclassic", "")
	var result DirectoryBinding
	endpoint := fmt.Sprintf("%s/directorybindings/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetDirectoryBindingByID(%s): %w", id, err)
	}
	return &result, nil
}

// CreateDirectoryBindingByID creates a new directory binding by ID.
//
// Required privileges: directory-bindings:create.
//
// Parameters:
//   - id: ID value to filter by.
func (c *Client) CreateDirectoryBindingByID(ctx context.Context, id string, request *DirectoryBinding) (*DirectoryBinding, error) {
	prefix := c.transport.APIPrefix("proclassic", "")
	var result DirectoryBinding
	endpoint := fmt.Sprintf("%s/directorybindings/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodPost, endpoint, request, http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("CreateDirectoryBindingByID(%s): %w", id, err)
	}
	return &result, nil
}

// UpdateDirectoryBindingByID updates an existing directory binding by ID.
//
// Required privileges: directory-bindings:update.
//
// Parameters:
//   - id: ID value to filter by.
func (c *Client) UpdateDirectoryBindingByID(ctx context.Context, id string, request *DirectoryBinding) error {
	prefix := c.transport.APIPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/directorybindings/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodPut, endpoint, request, http.StatusCreated, nil); err != nil {
		return fmt.Errorf("UpdateDirectoryBindingByID(%s): %w", id, err)
	}
	return nil
}

// DeleteDirectoryBindingByID deletes a directory binding by ID.
//
// Required privileges: directory-bindings:delete.
//
// Parameters:
//   - id: ID value to filter by.
func (c *Client) DeleteDirectoryBindingByID(ctx context.Context, id string) error {
	prefix := c.transport.APIPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/directorybindings/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusOK, nil); err != nil {
		return fmt.Errorf("DeleteDirectoryBindingByID(%s): %w", id, err)
	}
	return nil
}

// GetDirectoryBindingByName finds directory bindings by name.
//
// Required privileges: directory-bindings:read.
//
// Parameters:
//   - name: Name to filter by.
func (c *Client) GetDirectoryBindingByName(ctx context.Context, name string) (*DirectoryBinding, error) {
	prefix := c.transport.APIPrefix("proclassic", "")
	var result DirectoryBinding
	endpoint := fmt.Sprintf("%s/directorybindings/name/%s", prefix, url.PathEscape(name))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetDirectoryBindingByName(%s): %w", name, err)
	}
	return &result, nil
}

// UpdateDirectoryBindingByName updates an existing directory binding by name.
//
// Required privileges: directory-bindings:update.
//
// Parameters:
//   - name: Name value to filter by.
func (c *Client) UpdateDirectoryBindingByName(ctx context.Context, name string, request *DirectoryBinding) error {
	prefix := c.transport.APIPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/directorybindings/name/%s", prefix, url.PathEscape(name))
	if err := c.transport.DoExpect(ctx, http.MethodPut, endpoint, request, http.StatusCreated, nil); err != nil {
		return fmt.Errorf("UpdateDirectoryBindingByName(%s): %w", name, err)
	}
	return nil
}

// DeleteDirectoryBindingByName deletes a directory binding by name.
//
// Required privileges: directory-bindings:delete.
//
// Parameters:
//   - name: Name value to filter by.
func (c *Client) DeleteDirectoryBindingByName(ctx context.Context, name string) error {
	prefix := c.transport.APIPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/directorybindings/name/%s", prefix, url.PathEscape(name))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusOK, nil); err != nil {
		return fmt.Errorf("DeleteDirectoryBindingByName(%s): %w", name, err)
	}
	return nil
}

// ListDirectoryBindings finds all directory bindings.
//
// Required privileges: directory-bindings:read.
func (c *Client) ListDirectoryBindings(ctx context.Context) (*DirectoryBindings, error) {
	prefix := c.transport.APIPrefix("proclassic", "")
	var result DirectoryBindings
	endpoint := prefix + "/directorybindings"
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("ListDirectoryBindings: %w", err)
	}
	return &result, nil
}

// CreateDirectoryBindingByName creates a new directory binding by ID.
//
// Required privileges: directory-bindings:create.
//
// Parameters:
//   - name: ID value to filter by.
func (c *Client) CreateDirectoryBindingByName(ctx context.Context, name string, request *DirectoryBinding) error {
	prefix := c.transport.APIPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/directorybindings/name/%s", prefix, url.PathEscape(name))
	if err := c.transport.DoExpect(ctx, http.MethodPost, endpoint, request, http.StatusCreated, nil); err != nil {
		return fmt.Errorf("CreateDirectoryBindingByName(%s): %w", name, err)
	}
	return nil
}

// ResolveDirectoryBindingIDByName looks up a DirectoryBinding by name via GetDirectoryBindingByName and returns its ID as a string. Returns an error when the underlying call returns a nil ID.
func (c *Client) ResolveDirectoryBindingIDByName(ctx context.Context, name string) (string, error) {
	r, err := c.GetDirectoryBindingByName(ctx, name)
	if err != nil {
		return "", fmt.Errorf("ResolveDirectoryBindingIDByName(%s): %w", name, err)
	}
	if r == nil || r.ID == nil {
		return "", fmt.Errorf("ResolveDirectoryBindingIDByName(%s): response missing id", name)
	}
	return strconv.Itoa(*r.ID), nil
}

// ResolveDirectoryBindingByName looks up a DirectoryBinding by name. Alias for GetDirectoryBindingByName; present so callers can use the same Resolve<X>ByName spelling across all resources regardless of resolver mode.
func (c *Client) ResolveDirectoryBindingByName(ctx context.Context, name string) (*DirectoryBinding, error) {
	return c.GetDirectoryBindingByName(ctx, name)
}

// ApplyDirectoryBinding creates or updates a DirectoryBinding by name. If a resource with the specified name exists, it is updated; if not found, a new resource is created. Returns the resource ID, whether it was created (true) or updated (false), and any error. An *AmbiguousMatchError is returned if multiple resources match the name.
func (c *Client) ApplyDirectoryBinding(ctx context.Context, request *DirectoryBinding) (string, bool, error) {
	var name string
	if request.Name != nil {
		name = *request.Name
	}
	if name == "" {
		return "", false, fmt.Errorf("ApplyDirectoryBinding: Name must not be empty")
	}
	id, err := c.ResolveDirectoryBindingIDByName(ctx, name)
	if err != nil {
		if apiErr := client.AsAPIError(err); apiErr != nil && apiErr.HasStatus(404) {
			resp, createErr := c.CreateDirectoryBindingByID(ctx, "0", request)
			if createErr != nil {
				return "", false, fmt.Errorf("ApplyDirectoryBinding: create: %w", createErr)
			}
			return fmt.Sprintf("%d", *resp.ID), true, nil
		}
		return "", false, fmt.Errorf("ApplyDirectoryBinding: resolve: %w", err)
	}
	err = c.UpdateDirectoryBindingByID(ctx, id, request)
	if err != nil {
		return "", false, fmt.Errorf("ApplyDirectoryBinding: update(%s): %w", id, err)
	}
	return id, false, nil
}
