// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package proclassic

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"

	"github.com/jamf/jamfplatform-go-sdk/internal/client"
)

// GetDockItemByID finds dock items by ID.
//
// Required privileges: dock-items:read.
//
// Parameters:
//   - id: ID value to filter by.
func (c *Client) GetDockItemByID(ctx context.Context, id string) (*DockItem, error) {
	prefix := c.transport.APIPrefix("proclassic", "")
	var result DockItem
	endpoint := fmt.Sprintf("%s/dockitems/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetDockItemByID(%s): %w", id, err)
	}
	return &result, nil
}

// CreateDockItemByID creates a new dock item by ID.
//
// Required privileges: dock-items:create.
//
// Parameters:
//   - id: ID value to filter by.
func (c *Client) CreateDockItemByID(ctx context.Context, id string, request *DockItem) (*DockItem, error) {
	prefix := c.transport.APIPrefix("proclassic", "")
	var result DockItem
	endpoint := fmt.Sprintf("%s/dockitems/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodPost, endpoint, request, http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("CreateDockItemByID(%s): %w", id, err)
	}
	return &result, nil
}

// UpdateDockItemByID updates an existing dock item by ID.
//
// Required privileges: dock-items:update.
//
// Parameters:
//   - id: ID value to filter by.
func (c *Client) UpdateDockItemByID(ctx context.Context, id string, request *DockItem) error {
	prefix := c.transport.APIPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/dockitems/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodPut, endpoint, request, http.StatusCreated, nil); err != nil {
		return fmt.Errorf("UpdateDockItemByID(%s): %w", id, err)
	}
	return nil
}

// DeleteDockItemByID deletes a dock item by ID.
//
// Required privileges: dock-items:delete.
//
// Parameters:
//   - id: ID value to filter by.
func (c *Client) DeleteDockItemByID(ctx context.Context, id string) error {
	prefix := c.transport.APIPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/dockitems/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusOK, nil); err != nil {
		return fmt.Errorf("DeleteDockItemByID(%s): %w", id, err)
	}
	return nil
}

// GetDockItemByName finds dock items by name.
//
// Required privileges: dock-items:read.
//
// Parameters:
//   - name: Name to filter by.
func (c *Client) GetDockItemByName(ctx context.Context, name string) (*DockItem, error) {
	prefix := c.transport.APIPrefix("proclassic", "")
	var result DockItem
	endpoint := fmt.Sprintf("%s/dockitems/name/%s", prefix, url.PathEscape(name))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetDockItemByName(%s): %w", name, err)
	}
	return &result, nil
}

// UpdateDockItemByName updates an existing dock item by name.
//
// Required privileges: dock-items:update.
//
// Parameters:
//   - name: Name value to filter by.
func (c *Client) UpdateDockItemByName(ctx context.Context, name string, request *DockItem) error {
	prefix := c.transport.APIPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/dockitems/name/%s", prefix, url.PathEscape(name))
	if err := c.transport.DoExpect(ctx, http.MethodPut, endpoint, request, http.StatusCreated, nil); err != nil {
		return fmt.Errorf("UpdateDockItemByName(%s): %w", name, err)
	}
	return nil
}

// DeleteDockItemByName deletes a dock item by name.
//
// Required privileges: dock-items:delete.
//
// Parameters:
//   - name: Name value to filter by.
func (c *Client) DeleteDockItemByName(ctx context.Context, name string) error {
	prefix := c.transport.APIPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/dockitems/name/%s", prefix, url.PathEscape(name))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusOK, nil); err != nil {
		return fmt.Errorf("DeleteDockItemByName(%s): %w", name, err)
	}
	return nil
}

// ListDockItems finds all dock items.
//
// Required privileges: dock-items:read.
func (c *Client) ListDockItems(ctx context.Context) (*DockItems, error) {
	prefix := c.transport.APIPrefix("proclassic", "")
	var result DockItems
	endpoint := prefix + "/dockitems"
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("ListDockItems: %w", err)
	}
	return &result, nil
}

// CreateDockItemByName creates a new dock item by ID.
//
// Required privileges: dock-items:create.
//
// Parameters:
//   - name: ID value to filter by.
func (c *Client) CreateDockItemByName(ctx context.Context, name string, request *DockItem) error {
	prefix := c.transport.APIPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/dockitems/name/%s", prefix, url.PathEscape(name))
	if err := c.transport.DoExpect(ctx, http.MethodPost, endpoint, request, http.StatusCreated, nil); err != nil {
		return fmt.Errorf("CreateDockItemByName(%s): %w", name, err)
	}
	return nil
}

// ResolveDockItemIDByName looks up a DockItem by name via GetDockItemByName and returns its ID as a string. Returns an error when the underlying call returns a nil ID.
func (c *Client) ResolveDockItemIDByName(ctx context.Context, name string) (string, error) {
	r, err := c.GetDockItemByName(ctx, name)
	if err != nil {
		return "", fmt.Errorf("ResolveDockItemIDByName(%s): %w", name, err)
	}
	if r == nil || r.ID == nil {
		return "", fmt.Errorf("ResolveDockItemIDByName(%s): response missing id", name)
	}
	return strconv.Itoa(*r.ID), nil
}

// ResolveDockItemByName looks up a DockItem by name. Alias for GetDockItemByName; present so callers can use the same Resolve<X>ByName spelling across all resources regardless of resolver mode.
func (c *Client) ResolveDockItemByName(ctx context.Context, name string) (*DockItem, error) {
	return c.GetDockItemByName(ctx, name)
}

// ApplyDockItem creates or updates a DockItem by name. If a resource with the specified name exists, it is updated; if not found, a new resource is created. Returns the resource ID, whether it was created (true) or updated (false), and any error. An *AmbiguousMatchError is returned if multiple resources match the name.
func (c *Client) ApplyDockItem(ctx context.Context, request *DockItem) (string, bool, error) {
	var name string
	if request.Name != nil {
		name = *request.Name
	}
	if name == "" {
		return "", false, fmt.Errorf("ApplyDockItem: Name must not be empty")
	}
	id, err := c.ResolveDockItemIDByName(ctx, name)
	if err != nil {
		if apiErr := client.AsAPIError(err); apiErr != nil && apiErr.HasStatus(404) {
			resp, createErr := c.CreateDockItemByID(ctx, "0", request)
			if createErr != nil {
				return "", false, fmt.Errorf("ApplyDockItem: create: %w", createErr)
			}
			return fmt.Sprintf("%d", *resp.ID), true, nil
		}
		return "", false, fmt.Errorf("ApplyDockItem: resolve: %w", err)
	}
	err = c.UpdateDockItemByID(ctx, id, request)
	if err != nil {
		return "", false, fmt.Errorf("ApplyDockItem: update(%s): %w", id, err)
	}
	return id, false, nil
}
