// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package proclassic

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"

	"github.com/jamf/jamfplatform-go-sdk/internal/client"
)

// GetEbookByID finds ebooks by ID.
//
// Required privileges: ebooks:read.
//
// Parameters:
//   - id: ID value to filter by.
func (c *Client) GetEbookByID(ctx context.Context, id string) (*Ebook, error) {
	prefix := c.transport.APIPrefix("proclassic", "")
	var result Ebook
	endpoint := fmt.Sprintf("%s/ebooks/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetEbookByID(%s): %w", id, err)
	}
	return &result, nil
}

// CreateEbookByID creates a new ebook by ID.
//
// Required privileges: ebooks:create.
//
// Parameters:
//   - id: ID value to filter by.
func (c *Client) CreateEbookByID(ctx context.Context, id string, request *EbookPost) (*Ebook, error) {
	prefix := c.transport.APIPrefix("proclassic", "")
	var result Ebook
	endpoint := fmt.Sprintf("%s/ebooks/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodPost, endpoint, request, http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("CreateEbookByID(%s): %w", id, err)
	}
	return &result, nil
}

// UpdateEbookByID updates an existing ebook by ID.
//
// Required privileges: ebooks:update.
//
// Parameters:
//   - id: ID value to filter by.
func (c *Client) UpdateEbookByID(ctx context.Context, id string, request *EbookPost) error {
	prefix := c.transport.APIPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/ebooks/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodPut, endpoint, request, http.StatusCreated, nil); err != nil {
		return fmt.Errorf("UpdateEbookByID(%s): %w", id, err)
	}
	return nil
}

// DeleteEbookByID deletes an ebook by ID.
//
// Required privileges: ebooks:delete.
//
// Parameters:
//   - id: ID value to filter by.
func (c *Client) DeleteEbookByID(ctx context.Context, id string) error {
	prefix := c.transport.APIPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/ebooks/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusOK, nil); err != nil {
		return fmt.Errorf("DeleteEbookByID(%s): %w", id, err)
	}
	return nil
}

// GetEbookByName finds ebooks by name.
//
// Required privileges: ebooks:read.
//
// Parameters:
//   - name: Name to filter by.
func (c *Client) GetEbookByName(ctx context.Context, name string) (*Ebook, error) {
	prefix := c.transport.APIPrefix("proclassic", "")
	var result Ebook
	endpoint := fmt.Sprintf("%s/ebooks/name/%s", prefix, url.PathEscape(name))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetEbookByName(%s): %w", name, err)
	}
	return &result, nil
}

// UpdateEbookByName updates an existing ebook by name.
//
// Required privileges: ebooks:update.
//
// Parameters:
//   - name: Name value to filter by.
func (c *Client) UpdateEbookByName(ctx context.Context, name string, request *EbookPost) error {
	prefix := c.transport.APIPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/ebooks/name/%s", prefix, url.PathEscape(name))
	if err := c.transport.DoExpect(ctx, http.MethodPut, endpoint, request, http.StatusCreated, nil); err != nil {
		return fmt.Errorf("UpdateEbookByName(%s): %w", name, err)
	}
	return nil
}

// DeleteEbookByName deletes an ebook by name.
//
// Required privileges: ebooks:delete.
//
// Parameters:
//   - name: Name value to filter by.
func (c *Client) DeleteEbookByName(ctx context.Context, name string) error {
	prefix := c.transport.APIPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/ebooks/name/%s", prefix, url.PathEscape(name))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusOK, nil); err != nil {
		return fmt.Errorf("DeleteEbookByName(%s): %w", name, err)
	}
	return nil
}

// ListEbooks finds all ebooks.
//
// Required privileges: ebooks:read.
func (c *Client) ListEbooks(ctx context.Context) (*Ebooks, error) {
	prefix := c.transport.APIPrefix("proclassic", "")
	var result Ebooks
	endpoint := prefix + "/ebooks"
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("ListEbooks: %w", err)
	}
	return &result, nil
}

// GetEbookByIDSubset finds a subset of data for an ebook by ID.
//
// Required privileges: ebooks:read.
//
// Parameters:
//   - id: ID to filter by.
//   - subset: Subset to filter by.
//     Allowed values: "General", "Scope", "SelfService".
func (c *Client) GetEbookByIDSubset(ctx context.Context, id string, subset string) (*Ebook, error) {
	prefix := c.transport.APIPrefix("proclassic", "")
	var result Ebook
	endpoint := fmt.Sprintf("%s/ebooks/id/%s/subset/%s", prefix, url.PathEscape(id), url.PathEscape(subset))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetEbookByIDSubset(%s): %w", id, err)
	}
	return &result, nil
}

// CreateEbookByName creates a new ebook by ID.
//
// Required privileges: ebooks:create.
//
// Parameters:
//   - name: ID value to filter by.
func (c *Client) CreateEbookByName(ctx context.Context, name string, request *EbookPost) error {
	prefix := c.transport.APIPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/ebooks/name/%s", prefix, url.PathEscape(name))
	if err := c.transport.DoExpect(ctx, http.MethodPost, endpoint, request, http.StatusCreated, nil); err != nil {
		return fmt.Errorf("CreateEbookByName(%s): %w", name, err)
	}
	return nil
}

// ResolveEbookIDByName looks up a Ebook by name via GetEbookByName and returns its ID as a string. Returns an error when the underlying call returns a nil ID.
func (c *Client) ResolveEbookIDByName(ctx context.Context, name string) (string, error) {
	r, err := c.GetEbookByName(ctx, name)
	if err != nil {
		return "", fmt.Errorf("ResolveEbookIDByName(%s): %w", name, err)
	}
	if r == nil || r.General == nil || r.General.ID == nil {
		return "", fmt.Errorf("ResolveEbookIDByName(%s): response missing id", name)
	}
	return strconv.Itoa(*r.General.ID), nil
}

// ResolveEbookByName looks up a Ebook by name. Alias for GetEbookByName; present so callers can use the same Resolve<X>ByName spelling across all resources regardless of resolver mode.
func (c *Client) ResolveEbookByName(ctx context.Context, name string) (*Ebook, error) {
	return c.GetEbookByName(ctx, name)
}

// ApplyEbook creates or updates a Ebook by name. If a resource with the specified name exists, it is updated; if not found, a new resource is created. Returns the resource ID, whether it was created (true) or updated (false), and any error. An *AmbiguousMatchError is returned if multiple resources match the name.
func (c *Client) ApplyEbook(ctx context.Context, request *EbookPost) (string, bool, error) {
	var name string
	if request.General != nil && request.General.Name != nil {
		name = *request.General.Name
	}
	if name == "" {
		return "", false, fmt.Errorf("ApplyEbook: Name must not be empty")
	}
	id, err := c.ResolveEbookIDByName(ctx, name)
	if err != nil {
		if apiErr := client.AsAPIError(err); apiErr != nil && apiErr.HasStatus(404) {
			resp, createErr := c.CreateEbookByID(ctx, "0", request)
			if createErr != nil {
				return "", false, fmt.Errorf("ApplyEbook: create: %w", createErr)
			}
			return fmt.Sprintf("%d", *resp.ID), true, nil
		}
		return "", false, fmt.Errorf("ApplyEbook: resolve: %w", err)
	}
	err = c.UpdateEbookByID(ctx, id, request)
	if err != nil {
		return "", false, fmt.Errorf("ApplyEbook: update(%s): %w", id, err)
	}
	return id, false, nil
}
