// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package proclassic

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"

	"github.com/jamf/jamfplatform-go-sdk/internal/client"
)

// GetMacApplicationByID finds mac applications by ID.
//
// Required privileges: applications:read.
//
// Parameters:
//   - id: ID value to filter by.
func (c *Client) GetMacApplicationByID(ctx context.Context, id string) (*MacApplication, error) {
	prefix := c.transport.APIPrefix("proclassic", "")
	var result MacApplication
	endpoint := fmt.Sprintf("%s/macapplications/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetMacApplicationByID(%s): %w", id, err)
	}
	return &result, nil
}

// CreateMacApplicationByID creates a new mac application by ID.
//
// Required privileges: applications:create.
//
// Parameters:
//   - id: ID value to filter by.
func (c *Client) CreateMacApplicationByID(ctx context.Context, id string, request *MacApplication) (*MacApplication, error) {
	prefix := c.transport.APIPrefix("proclassic", "")
	var result MacApplication
	endpoint := fmt.Sprintf("%s/macapplications/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodPost, endpoint, request, http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("CreateMacApplicationByID(%s): %w", id, err)
	}
	return &result, nil
}

// UpdateMacApplicationByID updates an existing mac application by ID.
//
// Required privileges: applications:update.
//
// Parameters:
//   - id: ID value to filter by.
func (c *Client) UpdateMacApplicationByID(ctx context.Context, id string, request *MacApplication) error {
	prefix := c.transport.APIPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/macapplications/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodPut, endpoint, request, http.StatusCreated, nil); err != nil {
		return fmt.Errorf("UpdateMacApplicationByID(%s): %w", id, err)
	}
	return nil
}

// DeleteMacApplicationByID deletes a mac application by ID.
//
// Required privileges: applications:delete.
//
// Parameters:
//   - id: ID value to filter by.
func (c *Client) DeleteMacApplicationByID(ctx context.Context, id string) error {
	prefix := c.transport.APIPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/macapplications/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusOK, nil); err != nil {
		return fmt.Errorf("DeleteMacApplicationByID(%s): %w", id, err)
	}
	return nil
}

// GetMacApplicationByName finds mac applications by name.
//
// Required privileges: applications:read.
//
// Parameters:
//   - name: Name to filter by.
func (c *Client) GetMacApplicationByName(ctx context.Context, name string) (*MacApplication, error) {
	prefix := c.transport.APIPrefix("proclassic", "")
	var result MacApplication
	endpoint := fmt.Sprintf("%s/macapplications/name/%s", prefix, url.PathEscape(name))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetMacApplicationByName(%s): %w", name, err)
	}
	return &result, nil
}

// UpdateMacApplicationByName updates an existing mac application by name.
//
// Required privileges: applications:update.
//
// Parameters:
//   - name: Name value to filter by.
func (c *Client) UpdateMacApplicationByName(ctx context.Context, name string, request *MacApplication) error {
	prefix := c.transport.APIPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/macapplications/name/%s", prefix, url.PathEscape(name))
	if err := c.transport.DoExpect(ctx, http.MethodPut, endpoint, request, http.StatusCreated, nil); err != nil {
		return fmt.Errorf("UpdateMacApplicationByName(%s): %w", name, err)
	}
	return nil
}

// DeleteMacApplicationByName deletes a mac application by name.
//
// Required privileges: applications:delete.
//
// Parameters:
//   - name: Name value to filter by.
func (c *Client) DeleteMacApplicationByName(ctx context.Context, name string) error {
	prefix := c.transport.APIPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/macapplications/name/%s", prefix, url.PathEscape(name))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusOK, nil); err != nil {
		return fmt.Errorf("DeleteMacApplicationByName(%s): %w", name, err)
	}
	return nil
}

// ListMacApplications finds all mac applications.
//
// Required privileges: applications:read.
func (c *Client) ListMacApplications(ctx context.Context) (*MacApplications, error) {
	prefix := c.transport.APIPrefix("proclassic", "")
	var result MacApplications
	endpoint := prefix + "/macapplications"
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("ListMacApplications: %w", err)
	}
	return &result, nil
}

// GetMacApplicationByIDSubset finds a subset of date for a mac application by ID.
//
// Required privileges: applications:read.
//
// Parameters:
//   - id: ID to filter by.
//   - subset: Subset to filter by.
//     Allowed values: "General", "Scope", "SelfService", "VPPCodes", "VPP".
func (c *Client) GetMacApplicationByIDSubset(ctx context.Context, id string, subset string) (*MacApplication, error) {
	prefix := c.transport.APIPrefix("proclassic", "")
	var result MacApplication
	endpoint := fmt.Sprintf("%s/macapplications/id/%s/subset/%s", prefix, url.PathEscape(id), url.PathEscape(subset))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetMacApplicationByIDSubset(%s): %w", id, err)
	}
	return &result, nil
}

// GetMacApplicationByNameSubset finds a subset of data for mac applications by name.
//
// Required privileges: applications:read.
//
// Parameters:
//   - name: Name to filter by.
//   - subset: Subset to filter by.
//     Allowed values: "General", "Scope", "SelfService", "VPPCodes", "VPP".
func (c *Client) GetMacApplicationByNameSubset(ctx context.Context, name string, subset string) (*MacApplication, error) {
	prefix := c.transport.APIPrefix("proclassic", "")
	var result MacApplication
	endpoint := fmt.Sprintf("%s/macapplications/name/%s/subset/%s", prefix, url.PathEscape(name), url.PathEscape(subset))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetMacApplicationByNameSubset(%s): %w", name, err)
	}
	return &result, nil
}

// CreateMacApplicationByName creates a new mac application by ID.
//
// Required privileges: applications:create.
//
// Parameters:
//   - name: ID value to filter by.
func (c *Client) CreateMacApplicationByName(ctx context.Context, name string, request *MacApplication) error {
	prefix := c.transport.APIPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/macapplications/name/%s", prefix, url.PathEscape(name))
	if err := c.transport.DoExpect(ctx, http.MethodPost, endpoint, request, http.StatusCreated, nil); err != nil {
		return fmt.Errorf("CreateMacApplicationByName(%s): %w", name, err)
	}
	return nil
}

// ResolveMacApplicationIDByName looks up a MacApplication by name via GetMacApplicationByName and returns its ID as a string. Returns an error when the underlying call returns a nil ID.
func (c *Client) ResolveMacApplicationIDByName(ctx context.Context, name string) (string, error) {
	r, err := c.GetMacApplicationByName(ctx, name)
	if err != nil {
		return "", fmt.Errorf("ResolveMacApplicationIDByName(%s): %w", name, err)
	}
	if r == nil || r.General == nil || r.General.ID == nil {
		return "", fmt.Errorf("ResolveMacApplicationIDByName(%s): response missing id", name)
	}
	return strconv.Itoa(*r.General.ID), nil
}

// ResolveMacApplicationByName looks up a MacApplication by name. Alias for GetMacApplicationByName; present so callers can use the same Resolve<X>ByName spelling across all resources regardless of resolver mode.
func (c *Client) ResolveMacApplicationByName(ctx context.Context, name string) (*MacApplication, error) {
	return c.GetMacApplicationByName(ctx, name)
}

// ApplyMacApplication creates or updates a MacApplication by name. If a resource with the specified name exists, it is updated; if not found, a new resource is created. Returns the resource ID, whether it was created (true) or updated (false), and any error. An *AmbiguousMatchError is returned if multiple resources match the name.
func (c *Client) ApplyMacApplication(ctx context.Context, request *MacApplication) (string, bool, error) {
	var name string
	if request.General != nil && request.General.Name != nil {
		name = *request.General.Name
	}
	if name == "" {
		return "", false, fmt.Errorf("ApplyMacApplication: Name must not be empty")
	}
	id, err := c.ResolveMacApplicationIDByName(ctx, name)
	if err != nil {
		if apiErr := client.AsAPIError(err); apiErr != nil && apiErr.HasStatus(404) {
			resp, createErr := c.CreateMacApplicationByID(ctx, "0", request)
			if createErr != nil {
				return "", false, fmt.Errorf("ApplyMacApplication: create: %w", createErr)
			}
			return fmt.Sprintf("%d", *resp.ID), true, nil
		}
		return "", false, fmt.Errorf("ApplyMacApplication: resolve: %w", err)
	}
	err = c.UpdateMacApplicationByID(ctx, id, request)
	if err != nil {
		return "", false, fmt.Errorf("ApplyMacApplication: update(%s): %w", id, err)
	}
	return id, false, nil
}
