// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package proclassic

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"

	"github.com/jamf/jamfplatform-go-sdk/internal/client"
)

// GetMobileDeviceProvisioningProfileByID finds a mobile device provisioning profiles by id.
//
// Required privileges: provisioning-profiles:read.
//
// Parameters:
//   - id: Id value to filter by.
func (c *Client) GetMobileDeviceProvisioningProfileByID(ctx context.Context, id string) (*MobileDeviceProvisioningProfile, error) {
	prefix := c.transport.APIPrefix("proclassic", "")
	var result MobileDeviceProvisioningProfile
	endpoint := fmt.Sprintf("%s/mobiledeviceprovisioningprofiles/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetMobileDeviceProvisioningProfileByID(%s): %w", id, err)
	}
	return &result, nil
}

// CreateMobileDeviceProvisioningProfileByID creates a mobile device provisioning profiles by id.
//
// Required privileges: provisioning-profiles:create.
//
// Parameters:
//   - id: Id value to filter by.
func (c *Client) CreateMobileDeviceProvisioningProfileByID(ctx context.Context, id string, request *MobileDeviceProvisioningProfile) (*MobileDeviceProvisioningProfile, error) {
	prefix := c.transport.APIPrefix("proclassic", "")
	var result MobileDeviceProvisioningProfile
	endpoint := fmt.Sprintf("%s/mobiledeviceprovisioningprofiles/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodPost, endpoint, request, http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("CreateMobileDeviceProvisioningProfileByID(%s): %w", id, err)
	}
	return &result, nil
}

// UpdateMobileDeviceProvisioningProfileByID updates an existing mobile device provisioning profiles by id.
//
// Required privileges: provisioning-profiles:update.
//
// Parameters:
//   - id: Id value to filter by.
func (c *Client) UpdateMobileDeviceProvisioningProfileByID(ctx context.Context, id string, request *MobileDeviceProvisioningProfile) (*MobileDeviceProvisioningProfile, error) {
	prefix := c.transport.APIPrefix("proclassic", "")
	var result MobileDeviceProvisioningProfile
	endpoint := fmt.Sprintf("%s/mobiledeviceprovisioningprofiles/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodPut, endpoint, request, http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("UpdateMobileDeviceProvisioningProfileByID(%s): %w", id, err)
	}
	return &result, nil
}

// DeleteMobileDeviceProvisioningProfileByID deletes a mobile device provisioning profiles by id.
//
// Required privileges: provisioning-profiles:delete.
//
// Parameters:
//   - id: Id value to filter by.
func (c *Client) DeleteMobileDeviceProvisioningProfileByID(ctx context.Context, id string) error {
	prefix := c.transport.APIPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/mobiledeviceprovisioningprofiles/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusOK, nil); err != nil {
		return fmt.Errorf("DeleteMobileDeviceProvisioningProfileByID(%s): %w", id, err)
	}
	return nil
}

// GetMobileDeviceProvisioningProfileByName finds a mobile device provisioning profiles by name.
//
// Required privileges: provisioning-profiles:read.
//
// Parameters:
//   - name: Name value to filter by.
func (c *Client) GetMobileDeviceProvisioningProfileByName(ctx context.Context, name string) (*MobileDeviceProvisioningProfile, error) {
	prefix := c.transport.APIPrefix("proclassic", "")
	var result MobileDeviceProvisioningProfile
	endpoint := fmt.Sprintf("%s/mobiledeviceprovisioningprofiles/name/%s", prefix, url.PathEscape(name))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetMobileDeviceProvisioningProfileByName(%s): %w", name, err)
	}
	return &result, nil
}

// DeleteMobileDeviceProvisioningProfileByName deletes a mobile device provisioning profiles by name.
//
// Required privileges: provisioning-profiles:delete.
//
// Parameters:
//   - name: Name value to filter by.
func (c *Client) DeleteMobileDeviceProvisioningProfileByName(ctx context.Context, name string) error {
	prefix := c.transport.APIPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/mobiledeviceprovisioningprofiles/name/%s", prefix, url.PathEscape(name))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusOK, nil); err != nil {
		return fmt.Errorf("DeleteMobileDeviceProvisioningProfileByName(%s): %w", name, err)
	}
	return nil
}

// GetMobileDeviceProvisioningProfileByUUID finds a mobile device provisioning profiles by uuid.
//
// Required privileges: provisioning-profiles:read.
//
// Parameters:
//   - uuid: Uuid value to filter by.
func (c *Client) GetMobileDeviceProvisioningProfileByUUID(ctx context.Context, uuid string) (*MobileDeviceProvisioningProfile, error) {
	prefix := c.transport.APIPrefix("proclassic", "")
	var result MobileDeviceProvisioningProfile
	endpoint := fmt.Sprintf("%s/mobiledeviceprovisioningprofiles/uuid/%s", prefix, url.PathEscape(uuid))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetMobileDeviceProvisioningProfileByUUID(%s): %w", uuid, err)
	}
	return &result, nil
}

// DeleteMobileDeviceProvisioningProfileByUUID deletes a mobile device provisioning profiles by uuid.
//
// Required privileges: provisioning-profiles:delete.
//
// Parameters:
//   - uuid: Uuid value to filter by.
func (c *Client) DeleteMobileDeviceProvisioningProfileByUUID(ctx context.Context, uuid string) error {
	prefix := c.transport.APIPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/mobiledeviceprovisioningprofiles/uuid/%s", prefix, url.PathEscape(uuid))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusOK, nil); err != nil {
		return fmt.Errorf("DeleteMobileDeviceProvisioningProfileByUUID(%s): %w", uuid, err)
	}
	return nil
}

// ListMobileDeviceProvisioningProfiles finds all mobile device provisioning profiles.
//
// Required privileges: provisioning-profiles:read.
func (c *Client) ListMobileDeviceProvisioningProfiles(ctx context.Context) (*MobileDeviceProvisioningProfiles, error) {
	prefix := c.transport.APIPrefix("proclassic", "")
	var result MobileDeviceProvisioningProfiles
	endpoint := prefix + "/mobiledeviceprovisioningprofiles"
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("ListMobileDeviceProvisioningProfiles: %w", err)
	}
	return &result, nil
}

// CreateMobileDeviceProvisioningProfileByName creates a mobile device provisioning profiles by name.
//
// Required privileges: provisioning-profiles:create.
//
// Parameters:
//   - name: Name value to filter by.
func (c *Client) CreateMobileDeviceProvisioningProfileByName(ctx context.Context, name string, request *MobileDeviceProvisioningProfile) (*MobileDeviceProvisioningProfile, error) {
	prefix := c.transport.APIPrefix("proclassic", "")
	var result MobileDeviceProvisioningProfile
	endpoint := fmt.Sprintf("%s/mobiledeviceprovisioningprofiles/name/%s", prefix, url.PathEscape(name))
	if err := c.transport.DoExpect(ctx, http.MethodPost, endpoint, request, http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("CreateMobileDeviceProvisioningProfileByName(%s): %w", name, err)
	}
	return &result, nil
}

// UpdateMobileDeviceProvisioningProfileByName updates an existing mobile device provisioning profiles by name.
//
// Required privileges: provisioning-profiles:update.
//
// Parameters:
//   - name: Name value to filter by.
func (c *Client) UpdateMobileDeviceProvisioningProfileByName(ctx context.Context, name string, request *MobileDeviceProvisioningProfile) (*MobileDeviceProvisioningProfile, error) {
	prefix := c.transport.APIPrefix("proclassic", "")
	var result MobileDeviceProvisioningProfile
	endpoint := fmt.Sprintf("%s/mobiledeviceprovisioningprofiles/name/%s", prefix, url.PathEscape(name))
	if err := c.transport.DoExpect(ctx, http.MethodPut, endpoint, request, http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("UpdateMobileDeviceProvisioningProfileByName(%s): %w", name, err)
	}
	return &result, nil
}

// CreateMobileDeviceProvisioningProfileByUUID creates a mobile device provisioning profiles by uuid.
//
// Required privileges: provisioning-profiles:create.
//
// Parameters:
//   - uuid: Uuid value to filter by.
func (c *Client) CreateMobileDeviceProvisioningProfileByUUID(ctx context.Context, uuid string, request *MobileDeviceProvisioningProfile) (*MobileDeviceProvisioningProfile, error) {
	prefix := c.transport.APIPrefix("proclassic", "")
	var result MobileDeviceProvisioningProfile
	endpoint := fmt.Sprintf("%s/mobiledeviceprovisioningprofiles/uuid/%s", prefix, url.PathEscape(uuid))
	if err := c.transport.DoExpect(ctx, http.MethodPost, endpoint, request, http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("CreateMobileDeviceProvisioningProfileByUUID(%s): %w", uuid, err)
	}
	return &result, nil
}

// UpdateMobileDeviceProvisioningProfileByUUID updates an existing mobile device provisioning profiles by uuid.
//
// Required privileges: provisioning-profiles:update.
//
// Parameters:
//   - uuid: Uuid value to filter by.
func (c *Client) UpdateMobileDeviceProvisioningProfileByUUID(ctx context.Context, uuid string, request *MobileDeviceProvisioningProfile) (*MobileDeviceProvisioningProfile, error) {
	prefix := c.transport.APIPrefix("proclassic", "")
	var result MobileDeviceProvisioningProfile
	endpoint := fmt.Sprintf("%s/mobiledeviceprovisioningprofiles/uuid/%s", prefix, url.PathEscape(uuid))
	if err := c.transport.DoExpect(ctx, http.MethodPut, endpoint, request, http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("UpdateMobileDeviceProvisioningProfileByUUID(%s): %w", uuid, err)
	}
	return &result, nil
}

// GetMobileDeviceProvisioningProfileByIDSubset finds a mobile device provisioning profiles by id.
//
// Required privileges: provisioning-profiles:read.
//
// Parameters:
//   - id: Id value to filter by.
//   - subset: Path parameter subset.
func (c *Client) GetMobileDeviceProvisioningProfileByIDSubset(ctx context.Context, id string, subset string) (*MobileDeviceProvisioningProfile, error) {
	prefix := c.transport.APIPrefix("proclassic", "")
	var result MobileDeviceProvisioningProfile
	endpoint := fmt.Sprintf("%s/mobiledeviceprovisioningprofiles/id/%s/subset/%s", prefix, url.PathEscape(id), url.PathEscape(subset))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetMobileDeviceProvisioningProfileByIDSubset(%s): %w", id, err)
	}
	return &result, nil
}

// ResolveMobileDeviceProvisioningProfileIDByName looks up a MobileDeviceProvisioningProfile by name via GetMobileDeviceProvisioningProfileByName and returns its ID as a string. Returns an error when the underlying call returns a nil ID.
func (c *Client) ResolveMobileDeviceProvisioningProfileIDByName(ctx context.Context, name string) (string, error) {
	r, err := c.GetMobileDeviceProvisioningProfileByName(ctx, name)
	if err != nil {
		return "", fmt.Errorf("ResolveMobileDeviceProvisioningProfileIDByName(%s): %w", name, err)
	}
	if r == nil || r.General == nil || r.General.ID == nil {
		return "", fmt.Errorf("ResolveMobileDeviceProvisioningProfileIDByName(%s): response missing id", name)
	}
	return strconv.Itoa(*r.General.ID), nil
}

// ResolveMobileDeviceProvisioningProfileByName looks up a MobileDeviceProvisioningProfile by name. Alias for GetMobileDeviceProvisioningProfileByName; present so callers can use the same Resolve<X>ByName spelling across all resources regardless of resolver mode.
func (c *Client) ResolveMobileDeviceProvisioningProfileByName(ctx context.Context, name string) (*MobileDeviceProvisioningProfile, error) {
	return c.GetMobileDeviceProvisioningProfileByName(ctx, name)
}

// ApplyMobileDeviceProvisioningProfile creates or updates a MobileDeviceProvisioningProfile by name. If a resource with the specified name exists, it is updated; if not found, a new resource is created. Returns the resource ID, whether it was created (true) or updated (false), and any error. An *AmbiguousMatchError is returned if multiple resources match the name.
func (c *Client) ApplyMobileDeviceProvisioningProfile(ctx context.Context, request *MobileDeviceProvisioningProfile) (string, bool, error) {
	var name string
	if request.General != nil && request.General.Name != nil {
		name = *request.General.Name
	}
	if name == "" {
		return "", false, fmt.Errorf("ApplyMobileDeviceProvisioningProfile: Name must not be empty")
	}
	id, err := c.ResolveMobileDeviceProvisioningProfileIDByName(ctx, name)
	if err != nil {
		if apiErr := client.AsAPIError(err); apiErr != nil && apiErr.HasStatus(404) {
			resp, createErr := c.CreateMobileDeviceProvisioningProfileByID(ctx, "0", request)
			if createErr != nil {
				return "", false, fmt.Errorf("ApplyMobileDeviceProvisioningProfile: create: %w", createErr)
			}
			return fmt.Sprintf("%d", *resp.ID), true, nil
		}
		return "", false, fmt.Errorf("ApplyMobileDeviceProvisioningProfile: resolve: %w", err)
	}
	_, err = c.UpdateMobileDeviceProvisioningProfileByID(ctx, id, request)
	if err != nil {
		return "", false, fmt.Errorf("ApplyMobileDeviceProvisioningProfile: update(%s): %w", id, err)
	}
	return id, false, nil
}
