// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package proclassic

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"

	"github.com/jamf/jamfplatform-go-sdk/internal/client"
)

// GetMobileDeviceGroupByID finds mobile device groups by ID.
//
// Required privileges: device-groups:read.
//
// Parameters:
//   - id: ID value to filter by.
func (c *Client) GetMobileDeviceGroupByID(ctx context.Context, id string) (*MobileDeviceGroup, error) {
	prefix := c.transport.APIPrefix("proclassic", "")
	var result MobileDeviceGroup
	endpoint := fmt.Sprintf("%s/mobiledevicegroups/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetMobileDeviceGroupByID(%s): %w", id, err)
	}
	return &result, nil
}

// CreateMobileDeviceGroupByID creates a new mobile device group by ID.
//
// Required privileges: device-groups:create.
//
// Parameters:
//   - id: ID value to filter by.
func (c *Client) CreateMobileDeviceGroupByID(ctx context.Context, id string, request *MobileDeviceGroup) (*MobileDeviceGroup, error) {
	prefix := c.transport.APIPrefix("proclassic", "")
	var result MobileDeviceGroup
	endpoint := fmt.Sprintf("%s/mobiledevicegroups/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodPost, endpoint, request, http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("CreateMobileDeviceGroupByID(%s): %w", id, err)
	}
	return &result, nil
}

// UpdateMobileDeviceGroupByID updates an existing mobile device group by ID.
//
// Required privileges: device-groups:update.
//
// Parameters:
//   - id: ID value to filter by.
func (c *Client) UpdateMobileDeviceGroupByID(ctx context.Context, id string, request *MobileDeviceGroup) error {
	prefix := c.transport.APIPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/mobiledevicegroups/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodPut, endpoint, request, http.StatusCreated, nil); err != nil {
		return fmt.Errorf("UpdateMobileDeviceGroupByID(%s): %w", id, err)
	}
	return nil
}

// DeleteMobileDeviceGroupByID deletes a mobile device group by ID.
//
// Required privileges: device-groups:delete.
//
// Parameters:
//   - id: ID value to filter by.
func (c *Client) DeleteMobileDeviceGroupByID(ctx context.Context, id string) error {
	prefix := c.transport.APIPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/mobiledevicegroups/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusOK, nil); err != nil {
		return fmt.Errorf("DeleteMobileDeviceGroupByID(%s): %w", id, err)
	}
	return nil
}

// GetMobileDeviceGroupByName finds mobile device groups by name.
//
// Required privileges: device-groups:read.
//
// Parameters:
//   - name: Name to filter by.
func (c *Client) GetMobileDeviceGroupByName(ctx context.Context, name string) (*MobileDeviceGroup, error) {
	prefix := c.transport.APIPrefix("proclassic", "")
	var result MobileDeviceGroup
	endpoint := fmt.Sprintf("%s/mobiledevicegroups/name/%s", prefix, url.PathEscape(name))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetMobileDeviceGroupByName(%s): %w", name, err)
	}
	return &result, nil
}

// UpdateMobileDeviceGroupByName updates an existing mobile device group by name.
//
// Required privileges: device-groups:update.
//
// Parameters:
//   - name: Name value to filter by.
func (c *Client) UpdateMobileDeviceGroupByName(ctx context.Context, name string, request *MobileDeviceGroup) error {
	prefix := c.transport.APIPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/mobiledevicegroups/name/%s", prefix, url.PathEscape(name))
	if err := c.transport.DoExpect(ctx, http.MethodPut, endpoint, request, http.StatusCreated, nil); err != nil {
		return fmt.Errorf("UpdateMobileDeviceGroupByName(%s): %w", name, err)
	}
	return nil
}

// DeleteMobileDeviceGroupByName deletes a mobile device group by name.
//
// Required privileges: device-groups:delete.
//
// Parameters:
//   - name: Name value to filter by.
func (c *Client) DeleteMobileDeviceGroupByName(ctx context.Context, name string) error {
	prefix := c.transport.APIPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/mobiledevicegroups/name/%s", prefix, url.PathEscape(name))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusOK, nil); err != nil {
		return fmt.Errorf("DeleteMobileDeviceGroupByName(%s): %w", name, err)
	}
	return nil
}

// ListMobileDeviceGroups finds all mobile device groups.
//
// Required privileges: device-groups:read.
func (c *Client) ListMobileDeviceGroups(ctx context.Context) (*MobileDeviceGroups, error) {
	prefix := c.transport.APIPrefix("proclassic", "")
	var result MobileDeviceGroups
	endpoint := prefix + "/mobiledevicegroups"
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("ListMobileDeviceGroups: %w", err)
	}
	return &result, nil
}

// CreateMobileDeviceGroupByName creates a new mobile device group by ID.
//
// Required privileges: device-groups:create.
//
// Parameters:
//   - name: ID value to filter by.
func (c *Client) CreateMobileDeviceGroupByName(ctx context.Context, name string, request *MobileDeviceGroup) error {
	prefix := c.transport.APIPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/mobiledevicegroups/name/%s", prefix, url.PathEscape(name))
	if err := c.transport.DoExpect(ctx, http.MethodPost, endpoint, request, http.StatusCreated, nil); err != nil {
		return fmt.Errorf("CreateMobileDeviceGroupByName(%s): %w", name, err)
	}
	return nil
}

// ResolveMobileDeviceGroupIDByName looks up a MobileDeviceGroup by name via GetMobileDeviceGroupByName and returns its ID as a string. Returns an error when the underlying call returns a nil ID.
func (c *Client) ResolveMobileDeviceGroupIDByName(ctx context.Context, name string) (string, error) {
	r, err := c.GetMobileDeviceGroupByName(ctx, name)
	if err != nil {
		return "", fmt.Errorf("ResolveMobileDeviceGroupIDByName(%s): %w", name, err)
	}
	if r == nil || r.ID == nil {
		return "", fmt.Errorf("ResolveMobileDeviceGroupIDByName(%s): response missing id", name)
	}
	return strconv.Itoa(*r.ID), nil
}

// ResolveMobileDeviceGroupByName looks up a MobileDeviceGroup by name. Alias for GetMobileDeviceGroupByName; present so callers can use the same Resolve<X>ByName spelling across all resources regardless of resolver mode.
func (c *Client) ResolveMobileDeviceGroupByName(ctx context.Context, name string) (*MobileDeviceGroup, error) {
	return c.GetMobileDeviceGroupByName(ctx, name)
}

// ApplyMobileDeviceGroup creates or updates a MobileDeviceGroup by name. If a resource with the specified name exists, it is updated; if not found, a new resource is created. Returns the resource ID, whether it was created (true) or updated (false), and any error. An *AmbiguousMatchError is returned if multiple resources match the name.
func (c *Client) ApplyMobileDeviceGroup(ctx context.Context, request *MobileDeviceGroup) (string, bool, error) {
	var name string
	if request.Name != nil {
		name = *request.Name
	}
	if name == "" {
		return "", false, fmt.Errorf("ApplyMobileDeviceGroup: Name must not be empty")
	}
	id, err := c.ResolveMobileDeviceGroupIDByName(ctx, name)
	if err != nil {
		if apiErr := client.AsAPIError(err); apiErr != nil && apiErr.HasStatus(404) {
			resp, createErr := c.CreateMobileDeviceGroupByID(ctx, "0", request)
			if createErr != nil {
				return "", false, fmt.Errorf("ApplyMobileDeviceGroup: create: %w", createErr)
			}
			return fmt.Sprintf("%d", *resp.ID), true, nil
		}
		return "", false, fmt.Errorf("ApplyMobileDeviceGroup: resolve: %w", err)
	}
	err = c.UpdateMobileDeviceGroupByID(ctx, id, request)
	if err != nil {
		return "", false, fmt.Errorf("ApplyMobileDeviceGroup: update(%s): %w", id, err)
	}
	return id, false, nil
}
