// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package proclassic

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"

	"github.com/jamf/jamfplatform-go-sdk/internal/client"
)

// GetUserByID finds users by ID.
//
// Required privileges: users:read.
//
// Parameters:
//   - id: ID value to filter by.
func (c *Client) GetUserByID(ctx context.Context, id string) (*User, error) {
	prefix := c.transport.APIPrefix("proclassic", "")
	var result User
	endpoint := fmt.Sprintf("%s/users/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetUserByID(%s): %w", id, err)
	}
	return &result, nil
}

// CreateUserByID creates a new user by ID.
//
// Required privileges: users:create.
//
// Parameters:
//   - id: ID value to filter by.
func (c *Client) CreateUserByID(ctx context.Context, id string, request *UserPost) (*User, error) {
	prefix := c.transport.APIPrefix("proclassic", "")
	var result User
	endpoint := fmt.Sprintf("%s/users/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodPost, endpoint, request, http.StatusCreated, &result); err != nil {
		return nil, fmt.Errorf("CreateUserByID(%s): %w", id, err)
	}
	return &result, nil
}

// UpdateUserByID updates an existing user by ID.
//
// Required privileges: users:update.
//
// Parameters:
//   - id: ID value to filter by.
func (c *Client) UpdateUserByID(ctx context.Context, id string, request *UserPost) error {
	prefix := c.transport.APIPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/users/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodPut, endpoint, request, http.StatusCreated, nil); err != nil {
		return fmt.Errorf("UpdateUserByID(%s): %w", id, err)
	}
	return nil
}

// DeleteUserByID deletes a user by ID.
//
// Required privileges: users:delete.
//
// Parameters:
//   - id: ID value to filter by.
func (c *Client) DeleteUserByID(ctx context.Context, id string) error {
	prefix := c.transport.APIPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/users/id/%s", prefix, url.PathEscape(id))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusOK, nil); err != nil {
		return fmt.Errorf("DeleteUserByID(%s): %w", id, err)
	}
	return nil
}

// GetUserByName finds users by name.
//
// Required privileges: users:read.
//
// Parameters:
//   - name: Name to filter by.
func (c *Client) GetUserByName(ctx context.Context, name string) (*User, error) {
	prefix := c.transport.APIPrefix("proclassic", "")
	var result User
	endpoint := fmt.Sprintf("%s/users/name/%s", prefix, url.PathEscape(name))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetUserByName(%s): %w", name, err)
	}
	return &result, nil
}

// UpdateUserByName updates an existing user by name.
//
// Required privileges: users:update.
//
// Parameters:
//   - name: Name value to filter by.
func (c *Client) UpdateUserByName(ctx context.Context, name string, request *UserPost) error {
	prefix := c.transport.APIPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/users/name/%s", prefix, url.PathEscape(name))
	if err := c.transport.DoExpect(ctx, http.MethodPut, endpoint, request, http.StatusCreated, nil); err != nil {
		return fmt.Errorf("UpdateUserByName(%s): %w", name, err)
	}
	return nil
}

// DeleteUserByName deletes a user by name.
//
// Required privileges: users:delete.
//
// Parameters:
//   - name: Name value to filter by.
func (c *Client) DeleteUserByName(ctx context.Context, name string) error {
	prefix := c.transport.APIPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/users/name/%s", prefix, url.PathEscape(name))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusOK, nil); err != nil {
		return fmt.Errorf("DeleteUserByName(%s): %w", name, err)
	}
	return nil
}

// GetUserByEmail finds users by email address.
//
// Required privileges: users:read.
//
// Parameters:
//   - email: Email address to filter by.
func (c *Client) GetUserByEmail(ctx context.Context, email string) (*User, error) {
	prefix := c.transport.APIPrefix("proclassic", "")
	var result User
	endpoint := fmt.Sprintf("%s/users/email/%s", prefix, url.PathEscape(email))
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("GetUserByEmail(%s): %w", email, err)
	}
	return &result, nil
}

// ListUsers finds all users.
//
// Required privileges: users:read.
func (c *Client) ListUsers(ctx context.Context) (*Users, error) {
	prefix := c.transport.APIPrefix("proclassic", "")
	var result Users
	endpoint := prefix + "/users"
	if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
		return nil, fmt.Errorf("ListUsers: %w", err)
	}
	return &result, nil
}

// CreateUserByName creates a new user by ID.
//
// Required privileges: users:create.
//
// Parameters:
//   - name: ID value to filter by.
func (c *Client) CreateUserByName(ctx context.Context, name string, request *UserPost) error {
	prefix := c.transport.APIPrefix("proclassic", "")
	endpoint := fmt.Sprintf("%s/users/name/%s", prefix, url.PathEscape(name))
	if err := c.transport.DoExpect(ctx, http.MethodPost, endpoint, request, http.StatusCreated, nil); err != nil {
		return fmt.Errorf("CreateUserByName(%s): %w", name, err)
	}
	return nil
}

// ResolveUserIDByName looks up a User by name via GetUserByName and returns its ID as a string. Returns an error when the underlying call returns a nil ID.
func (c *Client) ResolveUserIDByName(ctx context.Context, name string) (string, error) {
	r, err := c.GetUserByName(ctx, name)
	if err != nil {
		return "", fmt.Errorf("ResolveUserIDByName(%s): %w", name, err)
	}
	if r == nil || r.ID == nil {
		return "", fmt.Errorf("ResolveUserIDByName(%s): response missing id", name)
	}
	return strconv.Itoa(*r.ID), nil
}

// ResolveUserByName looks up a User by name. Alias for GetUserByName; present so callers can use the same Resolve<X>ByName spelling across all resources regardless of resolver mode.
func (c *Client) ResolveUserByName(ctx context.Context, name string) (*User, error) {
	return c.GetUserByName(ctx, name)
}

// ApplyUser creates or updates a User by name. If a resource with the specified name exists, it is updated; if not found, a new resource is created. Returns the resource ID, whether it was created (true) or updated (false), and any error. An *AmbiguousMatchError is returned if multiple resources match the name.
func (c *Client) ApplyUser(ctx context.Context, request *UserPost) (string, bool, error) {
	var name string
	if request.Name != nil {
		name = *request.Name
	}
	if name == "" {
		return "", false, fmt.Errorf("ApplyUser: Name must not be empty")
	}
	id, err := c.ResolveUserIDByName(ctx, name)
	if err != nil {
		if apiErr := client.AsAPIError(err); apiErr != nil && apiErr.HasStatus(404) {
			resp, createErr := c.CreateUserByID(ctx, "0", request)
			if createErr != nil {
				return "", false, fmt.Errorf("ApplyUser: create: %w", createErr)
			}
			return fmt.Sprintf("%d", *resp.ID), true, nil
		}
		return "", false, fmt.Errorf("ApplyUser: resolve: %w", err)
	}
	err = c.UpdateUserByID(ctx, id, request)
	if err != nil {
		return "", false, fmt.Errorf("ApplyUser: update(%s): %w", id, err)
	}
	return id, false, nil
}
