// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package jamfplatform

// JamfProAPIVersion is the Jamf Pro release this SDK was generated from,
// read directly from the info.version field of the openapi-jpapi.json
// spec at generate time. Use it to log/report which API surface the
// linked SDK build targets.
const JamfProAPIVersion = "11.32.0"
