// Code generated by tools/generate; DO NOT EDIT.

// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

package securitycloud

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"

	"github.com/jamf/jamfplatform-go-sdk/internal/client"
)

// ListUemConnectorSyncRunsV1 list sync run history.
//
// Required privileges: uem-connect:read.
//
// Parameters:
//   - configID: The connector configuration identifier.
func (c *Client) ListUemConnectorSyncRunsV1(ctx context.Context, configID string) ([]SyncRun, error) {
	prefix := c.transport.APIPrefix("securitycloud", "")
	return client.ListAllPages(ctx, 100, func(ctx context.Context, page, pageSize int) ([]SyncRun, bool, error) {
		params := url.Values{}
		params.Set("page", strconv.Itoa(page))
		params.Set("page-size", strconv.Itoa(pageSize))

		endpoint := fmt.Sprintf("%s/uem-connect/v1/connectors/%s/sync/runs", prefix, url.PathEscape(configID))
		if encoded := params.Encode(); encoded != "" {
			endpoint += "?" + encoded
		}
		var result struct {
			TotalCount int       `json:"totalCount"`
			Results    []SyncRun `json:"results"`
		}
		if err := c.transport.Do(ctx, http.MethodGet, endpoint, nil, &result); err != nil {
			return nil, false, err
		}
		hasNext := (page+1)*pageSize < result.TotalCount
		return result.Results, hasNext, nil
	})
}

// TriggerUemConnectorSyncV1 trigger sync run.
//
// Required privileges: uem-connect:update.
//
// Parameters:
//   - configID: The connector configuration identifier.
func (c *Client) TriggerUemConnectorSyncV1(ctx context.Context, configID string) error {
	prefix := c.transport.APIPrefix("securitycloud", "")
	endpoint := fmt.Sprintf("%s/uem-connect/v1/connectors/%s/sync/runs", prefix, url.PathEscape(configID))
	if err := c.transport.DoExpect(ctx, http.MethodPost, endpoint, nil, http.StatusAccepted, nil); err != nil {
		return fmt.Errorf("TriggerUemConnectorSyncV1(%s): %w", configID, err)
	}
	return nil
}

// CancelUemConnectorSyncV1 cancel current sync run.
//
// Required privileges: uem-connect:update.
//
// Parameters:
//   - configID: The connector configuration identifier.
func (c *Client) CancelUemConnectorSyncV1(ctx context.Context, configID string) error {
	prefix := c.transport.APIPrefix("securitycloud", "")
	endpoint := fmt.Sprintf("%s/uem-connect/v1/connectors/%s/sync/runs/current", prefix, url.PathEscape(configID))
	if err := c.transport.DoExpect(ctx, http.MethodDelete, endpoint, nil, http.StatusNoContent, nil); err != nil {
		return fmt.Errorf("CancelUemConnectorSyncV1(%s): %w", configID, err)
	}
	return nil
}
